/** Generated automatically from search. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['search'] = fixtures['search'] || {};
        var search = fixtures['search']

        window.fixtures.search.list5 = {
   "total": 22,
   "previous": "/search/domain?max=2&sort=name&order=ASC&offset=0",
   "page": 2,
   "itemType": null,
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/search/domain?max=2&sort=name&order=ASC&offset=4",
   "list": [
      {
         "id": 9,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/9/outgoing"
         },
         "description": "this is a container for the domain for asd libraries",
         "name": "cdtest3",
         "link": "/conceptualDomain/9",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/9/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/9/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/9/incoming"
         },
         "version": 0
      },
      {
         "id": 28,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/28/outgoing"
         },
         "description": "this is a container for the domain for asd libraries",
         "name": "cdtest4",
         "link": "/conceptualDomain/28",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/28/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/28/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/28/incoming"
         },
         "version": 0
      }
   ],
   "offset": 2,
   "success": true,
   "size": 2
}

    })(window)