/** Generated automatically from search. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['search'] = fixtures['search'] || {};
        var search = fixtures['search']

        window.fixtures.search.list6 = {
   "total": 22,
   "previous": "/search/domain?max=2&sort=name&offset=2",
   "page": 2,
   "itemType": null,
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/search/domain?max=2&sort=name&offset=6",
   "list": [
      {
         "id": 26,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/26/outgoing"
         },
         "description": "this is a container for the domain for asd libraries",
         "name": "cdtest5",
         "link": "/conceptualDomain/26",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/26/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/26/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/26/incoming"
         },
         "version": 0
      },
      {
         "id": 23,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/23/outgoing"
         },
         "description": "this is a container for the domain for asd libraries",
         "name": "cdtest6",
         "link": "/conceptualDomain/23",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/23/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/23/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/23/incoming"
         },
         "version": 0
      }
   ],
   "offset": 4,
   "success": true,
   "size": 2
}

    })(window)