/** Generated automatically from search. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['search'] = fixtures['search'] || {};
        var search = fixtures['search']

        window.fixtures.search.list7 = {
   "total": 22,
   "previous": "/search/domain?max=2&offset=2",
   "page": 2,
   "itemType": null,
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/search/domain?max=2&offset=6",
   "list": [
      {
         "id": 15,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/15/outgoing"
         },
         "description": "this is a container for the domain for dgas libraries",
         "name": "cdtest1",
         "link": "/conceptualDomain/15",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/15/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/15/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/15/incoming"
         },
         "version": 0
      },
      {
         "id": 20,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/20/outgoing"
         },
         "description": "this is a container for the domain for ads libraries",
         "name": "cdtest7",
         "link": "/conceptualDomain/20",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/20/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/20/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/20/incoming"
         },
         "version": 0
      }
   ],
   "offset": 4,
   "success": true,
   "size": 2
}

    })(window)