#!/bin/bash

if [ "$#" -lt 3 ]; then
    echo "Executes command in subdirectories where given file exists"
    echo
    echo "Usage: where <file> [run] <command with arguments...>"
    exit 0
fi

set -e

FILE_TO_TEST=$1
KEYWORD=$2

if [ "$KEYWORD" == "run" ]; then
    shift 2
else
    shift
fi


echo "executing in all subdirectories where $FILE_TO_TEST exists: ./$@"

for file in */ .*/ ; do
    if [ -f "$file/$FILE_TO_TEST" ]; then
        cd "$file"
        echo "executing $file$@"
        eval "$@"
	    cd ..
    fi
done
