package org.modelcatalogue.core.search;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static java.util.Collections.addAll;

public class EnglishGrammar {
    final static List<String> QUANTIFIERS = new ArrayList<String>() {{
        add("many");
        add("a few");
        add("several");
        add("few");
        add("a couple of");
        add("none of the");
        add("not much");
        add("a little");
        add("little");
        add("a bit of");
        add("no");
    }};

    private static final List<String> ENGLISH_ARTICLES = new ArrayList<String>() {{
        add("a");
        add("an");
        add("the");
        add("this");
        add("that");
        add("these");
        add("those");
        add("each");
        add("every");
        add("either");
        add("neither");
        add("much");
        add("enough");
        add("which");
        add("what");
        add("some");
        add("any");
    }};

    private static final List<String> ENGLISH_SYMBOLS = new ArrayList<String>() {{
        add("%");
    }};

    private static final List<String> ENGLISH_PUNCTUATION_MARKS = new ArrayList<String>() {{
        add(",");
        add(".");
        add("...");
        add("(");
        add(")");
        add("?");
        add("!");
    }};

    private static final List<String> ENGLISH_CONJUNCTION_SIGNS = new ArrayList<String>() {{
        add("-");
        add("/");
        add("&");
    }};

    private static final List<String> ENGLISH_CARDINAL_NUMBERS = new ArrayList<String>() {{
        add("zero");
        add("one");
        add("two");
        add("three");
        add("four");
        add("five");
        add("six");
        add("seven");
        add("eight");
        add("nine");
        add("ten");
    }};

    private static final List<String> ENGLISH_PRONOUNS = new ArrayList<String>() {{
        add("another");
        add("more");
    }};


    private static final List<String> ENGLISH_ADVERBS = new ArrayList<String>() {{
        add("no");
        add("not");
        add("all");

    }};

    private static final List<String> ENGLISH_CONJUCTIONS = new ArrayList<String>() {{
        add("and");
        add("but");
        add("or");
        add("yet");
        add("for");
        add("nor");
        add("so");
    }};

    private static final List<String> ENGLISH_PREPOSITIONS = new ArrayList<String>() {{
        add("ab");
        add("ab.");
        add("abaat");
        add("abaft");
        add("abaht");
        add("abaout");
        add("abeam");
        add("ablow");
        add("aboard");
        add("aboon");
        add("aboot");
        add("about");
        add("aboutes");
        add("abouts");
        add("above");
        add("above and beyond");
        add("abowt");
        add("abreast");
        add("abroad");
        add("absent");
        add("abt.");
        add("abun");
        add("abune");
        add("according to");
        add("across");
        add("across from");
        add("acrosst");
        add("acrost");
        add("ad");
        add("adjacent");
        add("adown");
        add("affor");
        add("afoor");
        add("afore");
        add("afront");
        add("aftah");
        add("after");
        add("afther");
        add("aftre");
        add("again");
        add("against");
        add("agaynest");
        add("agaynst");
        add("ageinest");
        add("ageinst");
        add("agen");
        add("agenest");
        add("agenst");
        add("ageynest");
        add("ageynst");
        add("agin");
        add("aginst");
        add("ago");
        add("agyen");
        add("ahead of");
        add("ahind");
        add("ahint");
        add("ahn");
        add("ajax");
        add("AKA");
        add("aka");
        add("ala");
        add("alang");
        add("alangst");
        add("all along");
        add("all over");
        add("all up with");
        add("along");
        add("along of");
        add("along the lines of");
        add("alongest");
        add("alongside");
        add("alongst");
        add("aloof");
        add("alow");
        add("amid");
        add("amiddest");
        add("amiddst");
        add("amidest");
        add("amidst");
        add("among");
        add("amonge");
        add("amongest");
        add("amongst");
        add("amoung");
        add("amoungest");
        add("amoungst");
        add("amyddest");
        add("amyddst");
        add("amydst");
        add("an");
        add("anear");
        add("anearst");
        add("anenst");
        add("anent");
        add("anigh");
        add("anighst");
        add("anti");
        add("aout");
        add("ap.");
        add("apart");
        add("apart from");
        add("apres");
        add("après");
        add("aprés");
        add("apropos");
        add("apropos of");
        add("apud");
        add("around");
        add("arter");
        add("as");
        add("as for");
        add("as of");
        add("as opposed to");
        add("as per");
        add("as regards");
        add("as soon as");
        add("as to");
        add("as well as");
        add("aside from");
        add("aslant");
        add("astern of");
        add("astride");
        add("at");
        add("at peace with");
        add("at the expense of");
        add("at the feet of");
        add("at the hand of");
        add("at the hands of");
        add("athwart");
        add("atop");
        add("atween");
        add("atwix");
        add("away from");
        add("awaye");
        add("ayein");
        add("ayen");
        add("ayond");
        add("ayont");
        add("B");
        add("B4");
        add("bang on");
        add("bar");
        add("barring");
        add("bating");
        add("because");
        add("because of");
        add("befo");
        add("befo\'");
        add("befoir");
        add("befor");
        add("before");
        add("befure");
        add("behind");
        add("behinde");
        add("behine");
        add("behither");
        add("belong");
        add("below");
        add("ben");
        add("beneath");
        add("beneathe");
        add("benorth");
        add("beside");
        add("besides");
        add("besyde");
        add("bet");
        add("betune");
        add("between");
        add("betweene");
        add("betwene");
        add("betwixen");
        add("betwixt");
        add("betwyxt");
        add("bewest");
        add("beyant");
        add("beyond");
        add("b\'low");
        add("\'bout");
        add("bout");
        add("bove");
        add("but");
        add("but for");
        add("by");
        add("by dint of");
        add("by means of");
        add("by virtue of");
        add("bye");
        add("C");
        add("came");
        add("care of");
        add("of");
    }};

    public static Set<String> ALL = new HashSet<String>() {{
        addAll(QUANTIFIERS);
        addAll(ENGLISH_ARTICLES);
        addAll(ENGLISH_PUNCTUATION_MARKS);
        addAll(ENGLISH_CONJUNCTION_SIGNS);
        addAll(ENGLISH_PRONOUNS);
        addAll(ENGLISH_CARDINAL_NUMBERS);
        addAll(ENGLISH_CONJUCTIONS);
        addAll(ENGLISH_ADVERBS);
        addAll(ENGLISH_PREPOSITIONS);
        addAll(ENGLISH_SYMBOLS);
    }};
}
