package org.modelcatalogue.gel.export

import static junit.framework.Assert.assertEquals
import static org.modelcatalogue.core.util.test.FileOpener.open
import org.modelcatalogue.core.DataClass
import org.modelcatalogue.core.DataElement

/**
 * Created by rickrees on 18/04/2016.
 */
class RareDiseasePhenotypeChangeLogXlsExporterSpec extends AbstractRareDiseasesExporterSpec {


    String new_guidance_id, new_dataElement_id1, new_dataElement_id2, nestedPheno_id1, nestedPheno_id2, nestedPheno_id3

    // content & file generation test combined as second one fails if run separately
    def "Export rare disease phenotype changelogs to xls"() {
        when:
        buildTestModel(true)
        findDataIds()
        DataClass dataClass = DataClass.findByName('Dataclass Top Level 1 Root')
        makeChanges(dataClass)
        new_guidance_id = DataClass.findByName("New Guidance class").id
        new_dataElement_id1 = DataElement.findByName("New Phenotype DataElement").id
        new_dataElement_id2 = DataElement.findByName("2nd New Phenotype DataElement").id
        nestedPheno_id1 = DataClass.findByName('Nested 1st level Phenotype').id
        nestedPheno_id2 = DataClass.findByName('Nested 2nd level Phenotype').id
        nestedPheno_id3 = DataClass.findByName('Nested 3rd level Phenotype').id

        //test generated content
        List<String> rows = new RareDiseasePhenotypeChangeLogXlsExporter(auditService, dataClassService, performanceUtilService, 5, false).buildContentRows(dataClass)

        //need to prime with header as we're not running the excel part of the exporter here
        String allRows = 'Change reference,Level 2 Disease Group (ID),Level 3 Disease Subtype (ID),Level 4 Specific Disorder (ID),Element hierarchy,Phenotype /Clinical Tests/Guidance,Affected Data Item,Change Type,Current version details,New version details\n'

        rows.each{ row ->
            allRows+= "${row.join(',')}\n"
        }

        println "EXPECTED<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
        println expectedRDPhenotypesCsv
        println ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        println "GOT<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
        println allRows
        println ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"

        File file = temporaryFolder.newFile("${System.currentTimeMillis()}.xlsx")
        //test excel generation
        new RareDiseasePhenotypeChangeLogXlsExporter(auditService, dataClassService, performanceUtilService, 5, false).export(dataClass, file.newOutputStream())

        open file

        then:
        noExceptionThrown()
        assertEquals(expectedRDPhenotypesCsv, allRows) //need to use junit assert as Spock blows up badly on failure (OutOfMem)
    }


    def text = '''{"name":"Max Occurs","relationship":"{archived=false, classification=null, dataModel=null, destination={classifiedName=2nd New Phenotype DataElement (Rare Diseases Test Data Model), dataType=null, dateCreated=2016-04-25T16:41:11Z, description=null, elementType=org.modelcatalogue.core.DataElement, ext={type=orderedMap, values=[]}, id=133, internalModelCatalogueId=http://localhost:8080/catalogue/dataElement/133@0.0.1, lastUpdated=2016-04-25T16:41:12Z, latestVersionId=133, link=/dataElement/133, minimal=true, modelCatalogueId=null, name=2nd New Phenotype DataElement, status=DRAFT, versionCreated=2016-04-25T16:41:11Z, versionNumber=1}, elementType=org.modelcatalogue.core.Relationship, ext={type=orderedMap, values=[{key=Min Occurs, value=0}, {key=Max Occurs, value=2}]}, id=131, inherited=false, source={classifiedName=Phenotype (9) name 1 1 (Rare Diseases Test Data Model), dataModel={classifiedName=Rare Diseases Test Data Model, dateCreated=2016-04-25T16:40:59Z, description=This is a data model for testing Eligibility OR Phenotype and Clinicals tests exports, elementType=org.modelcatalogue.core.DataModel, ext={type=orderedMap, values=[{key=http://www.modelcatalogue.org/metadata/#organization, value=The Organisation}, {key=http://www.modelcatalogue.org/metadata/#reviewers, value=Reviewer One, Reviewer Two, Reviewer Three}, {key=http://www.modelcatalogue.org/metadata/#authors, value=Author One, Author Two, Author Three}, {key=http://www.modelcatalogue.org/metadata/#owner, value=The Owner}]}, id=1, internalModelCatalogueId=http://localhost:8080/catalogue/dataModel/1@0.0.1, lastUpdated=2016-04-25T16:41:00Z, latestVersionId=1, link=/dataModel/1, minimal=true, modelCatalogueId=null, name=Rare Diseases Test Data Model, semanticVersion=0.0.1, status=DRAFT, versionCreated=2016-04-25T16:40:58Z, versionNumber=1}, dateCreated=2016-04-25T16:41:01Z, description=null, elementType=org.modelcatalogue.core.DataClass, ext={type=orderedMap, values=[{key=OBO ID, value=HP:11}]}, id=22, internalModelCatalogueId=http://localhost:8080/catalogue/dataClass/22@0.0.1, lastUpdated=2016-04-25T16:41:12Z, latestVersionId=22, link=/dataClass/22, minimal=true, modelCatalogueId=null, name=Phenotype (9) name 1 1, status=DRAFT, versionCreated=2016-04-25T16:41:01Z, versionNumber=1}, type={id=1, link=/relationshipType/1, name=containment}}","extensionValue":"2"}'''

    def "test extractDeepElement Min Occurs"() {
        given:
        text
        when:
        String value = RareDiseasePhenotypeChangeLogXlsExporter.extractDeepElement(text, 'Min Occurs')

        then:
        '0' == value
    }

    def "test extractDeepElement Max Occurs"() {
        given:
        text
        when:
        String value = RareDiseasePhenotypeChangeLogXlsExporter.extractDeepElement(text, 'Max Occurs')

        then:
        '2' == value
    }

    private String getExpectedRDPhenotypesCsv() {
        return """Change reference,Level 2 Disease Group (ID),Level 3 Disease Subtype (ID),Level 4 Specific Disorder (ID),Element hierarchy,Phenotype /Clinical Tests/Guidance,Affected Data Item,Change Type,Current version details,New version details
,,,,,,Dataclass Top Level 1 Root ($level1_id),New Data Item,,Disorder >>>1<<< Level2 ($level2_id_1)
,,,,,,Dataclass Top Level 1 Root ($level1_id),New Data Item,,Disorder >>>2<<< Level2 ($level2_id_2)
,Disorder >>>1<<< Level2 ($level2_id_1),,,,,Disorder >>>1<<< Level2 ($level2_id_1),New Data Item,,Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1)
,Disorder >>>1<<< Level2 ($level2_id_1),,,,,Disorder >>>1<<< Level2 ($level2_id_1),New Data Item,,Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),,,,Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),New Data Item,,Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,,Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),New Data Item,,Disorder >1< Eligibility Level5 Model 1 Data Element 1 ($eligibLevel5Id_1)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,,Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),New Data Item,,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,,Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),New Data Item,,Disorder >1< Clinical tests Level5 Model 1 Data Element 1 ($clinicalLevel5Id_1)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,,Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),New Data Item,,Disorder >1< Guidance name 1 1 ($level5_guidanceid_1)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (1) name 1 1 (${phenotypeIds[0][0][0]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (2) name 1 1 (${phenotypeIds[0][0][1]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (3) name 1 1 (${phenotypeIds[0][0][2]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (4) name 1 1 (${phenotypeIds[0][0][3]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (5) name 1 1 (${phenotypeIds[0][0][4]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (6) name 1 1 (${phenotypeIds[0][0][5]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (7) name 1 1 (${phenotypeIds[0][0][6]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (8) name 1 1 (${phenotypeIds[0][0][7]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (10) name 1 1 (${phenotypeIds[0][0][9]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (11) name 1 1 (${phenotypeIds[0][0][10]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (12) name 1 1 (${phenotypeIds[0][0][11]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (13) name 1 1 (${phenotypeIds[0][0][12]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (14) name 1 1 (${phenotypeIds[0][0][13]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),New Data Item,,Phenotype (15) name 1 1 (${phenotypeIds[0][0][14]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 1 ($phenotypeLevel5Id_1),Remove Data Item,Phenotype (2) name 1 1 (${phenotypeIds[0][0][1]}),
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (1) name 1 1 (${phenotypeIds[0][0][0]}),New Metadata,,OBO ID: HP:3
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (3) name 1 1 (${phenotypeIds[0][0][2]}),New Metadata,,OBO ID: HP:5
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (4) name 1 1 (${phenotypeIds[0][0][3]}),New Metadata,,OBO ID: HP:6
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (5) changed name (${phenotypeIds[0][0][4]}),New Metadata,,OBO ID: HP:7
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (5) changed name (${phenotypeIds[0][0][4]}),Name Change,Phenotype (5) name 1 1,Phenotype (5) changed name
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (6) name 1 1 (${phenotypeIds[0][0][5]}),New Metadata,,OBO ID: HP:8
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (6) name 1 1 (${phenotypeIds[0][0][5]}),Change Metadata,OBO ID: HP:8,OBO ID: modified OBO ID
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (7) name 1 1 (${phenotypeIds[0][0][6]}),New Metadata,,OBO ID: HP:9
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (7) name 1 1 (${phenotypeIds[0][0][6]}),Remove Metadata,OBO ID: HP:9,
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (8) name 1 1 (${phenotypeIds[0][0][7]}),New Metadata,,OBO ID: HP:10
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (8) name 1 1 (${phenotypeIds[0][0][7]}),New Data Item,,New Phenotype DataElement (${new_dataElement_id1})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]}),New Metadata,,OBO ID: HP:11
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]}),New Data Item,,2nd New Phenotype DataElement (${new_dataElement_id2})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]}),New Metadata,,Min Occurs: 0
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]}),New Metadata,,Max Occurs: 2
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]}),New Metadata,,Min Occurs: 1
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]}),New Metadata,,Max Occurs: 3
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]}),Change Metadata,Min Occurs: 1,Min Occurs: 4
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (9) name 1 1 (${phenotypeIds[0][0][8]}),Change Metadata,Max Occurs: 3,Max Occurs: 5
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (10) name 1 1 (${phenotypeIds[0][0][9]}),New Metadata,,OBO ID: HP:12
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (11) name 1 1 (${phenotypeIds[0][0][10]}),New Metadata,,OBO ID: HP:13
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (12) name 1 1 (${phenotypeIds[0][0][11]}),New Metadata,,OBO ID: HP:14
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (13) name 1 1 (${phenotypeIds[0][0][12]}),New Metadata,,OBO ID: HP:15
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (14) name 1 1 (${phenotypeIds[0][0][13]}),New Metadata,,OBO ID: HP:16
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Phenotype,Phenotype (15) name 1 1 (${phenotypeIds[0][0][14]}),New Metadata,,OBO ID: HP:17
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 1 ($clinicalLevel5Id_1),New Data Item,,Clinical tests (1) name 1 1 (${clinicalTestIds[0][0][0]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 1 ($clinicalLevel5Id_1),New Data Item,,Clinical tests (2) name 1 1 (${clinicalTestIds[0][0][1]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 1 ($clinicalLevel5Id_1),New Data Item,,Clinical tests (3) name 1 1 (${clinicalTestIds[0][0][2]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 1 ($clinicalLevel5Id_1),New Data Item,,Clinical tests (4) name 1 1 (${clinicalTestIds[0][0][3]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 1 ($clinicalLevel5Id_1),New Data Item,,Clinical tests (5) name 1 1 (${clinicalTestIds[0][0][4]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 1 ($level3_id_1),Disorder >>1<< heading Level4 Model Data Element 1 ($level4_id_1),,Guidance,Disorder >1< Guidance name 1 1 ($level5_guidanceid_1),Text change,Guidance description  1 1,new textual description replaces old
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),,,,Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),New Data Item,,Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,,Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),New Data Item,,Disorder >1< Eligibility Level5 Model 1 Data Element 2 ($eligibLevel5Id_2)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,,Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),New Data Item,,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,,Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),New Data Item,,Disorder >1< Clinical tests Level5 Model 1 Data Element 2 ($clinicalLevel5Id_2)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,,Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),New Data Item,,Disorder >1< Guidance name 1 2 ($level5_guidanceid_2)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,,Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),New Data Item,,New Guidance class ($new_guidance_id)
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (1) name 1 2 (${phenotypeIds[0][1][0]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (2) name 1 2 (${phenotypeIds[0][1][1]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (3) name 1 2 (${phenotypeIds[0][1][2]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (4) name 1 2 (${phenotypeIds[0][1][3]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (5) name 1 2 (${phenotypeIds[0][1][4]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (6) name 1 2 (${phenotypeIds[0][1][5]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (7) name 1 2 (${phenotypeIds[0][1][6]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (8) name 1 2 (${phenotypeIds[0][1][7]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (9) name 1 2 (${phenotypeIds[0][1][8]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (10) name 1 2 (${phenotypeIds[0][1][9]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (11) name 1 2 (${phenotypeIds[0][1][10]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (12) name 1 2 (${phenotypeIds[0][1][11]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (13) name 1 2 (${phenotypeIds[0][1][12]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (14) name 1 2 (${phenotypeIds[0][1][13]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Disorder >1< Phenotypes Level5 Model 1 Data Element 2 ($phenotypeLevel5Id_2),New Data Item,,Phenotype (15) name 1 2 (${phenotypeIds[0][1][14]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (1) name 1 2 (${phenotypeIds[0][1][0]}),New Metadata,,OBO ID: HP:4
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (2) name 1 2 (${phenotypeIds[0][1][1]}),New Metadata,,OBO ID: HP:5
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (3) name 1 2 (${phenotypeIds[0][1][2]}),New Metadata,,OBO ID: HP:6
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (4) name 1 2 (${phenotypeIds[0][1][3]}),New Metadata,,OBO ID: HP:7
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (5) name 1 2 (${phenotypeIds[0][1][4]}),New Metadata,,OBO ID: HP:8
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (6) name 1 2 (${phenotypeIds[0][1][5]}),New Metadata,,OBO ID: HP:9
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (7) name 1 2 (${phenotypeIds[0][1][6]}),New Metadata,,OBO ID: HP:10
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (8) name 1 2 (${phenotypeIds[0][1][7]}),New Metadata,,OBO ID: HP:11
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (9) name 1 2 (${phenotypeIds[0][1][8]}),New Metadata,,OBO ID: HP:12
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (10) name 1 2 (${phenotypeIds[0][1][9]}),New Metadata,,OBO ID: HP:13
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (11) name 1 2 (${phenotypeIds[0][1][10]}),New Metadata,,OBO ID: HP:14
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (12) name 1 2 (${phenotypeIds[0][1][11]}),New Metadata,,OBO ID: HP:15
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (13) name 1 2 (${phenotypeIds[0][1][12]}),New Metadata,,OBO ID: HP:16
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (14) name 1 2 (${phenotypeIds[0][1][13]}),New Metadata,,OBO ID: HP:17
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Phenotype,Phenotype (15) name 1 2 (${phenotypeIds[0][1][14]}),New Metadata,,OBO ID: HP:18
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 2 ($clinicalLevel5Id_2),New Data Item,,Clinical tests (1) name 1 2 (${clinicalTestIds[0][1][0]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 2 ($clinicalLevel5Id_2),New Data Item,,Clinical tests (2) name 1 2 (${clinicalTestIds[0][1][1]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 2 ($clinicalLevel5Id_2),New Data Item,,Clinical tests (3) name 1 2 (${clinicalTestIds[0][1][2]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 2 ($clinicalLevel5Id_2),New Data Item,,Clinical tests (4) name 1 2 (${clinicalTestIds[0][1][3]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Clinical tests,Disorder >1< Clinical tests Level5 Model 1 Data Element 2 ($clinicalLevel5Id_2),New Data Item,,Clinical tests (5) name 1 2 (${clinicalTestIds[0][1][4]})
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Clinical tests,Clinical tests (5) name 1 2 (${clinicalTestIds[0][1][4]}),Change Description,,description for Clinical tests (5) name 1 2  has been changed
,Disorder >>>1<<< Level2 ($level2_id_1),Disorder >>>1<<< SubCondition Level3 Model Data Element 2 ($level3_id_2),Disorder >>1<< heading Level4 Model Data Element 2 ($level4_id_2),,Guidance,New Guidance class ($new_guidance_id),Text change,,brand new description
,Disorder >>>2<<< Level2 ($level2_id_2),,,,,Disorder >>>2<<< Level2 ($level2_id_2),New Data Item,,Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3)
,Disorder >>>2<<< Level2 ($level2_id_2),,,,,Disorder >>>2<<< Level2 ($level2_id_2),New Data Item,,Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),,,,Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),New Data Item,,Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,,Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),New Data Item,,Disorder >2< Eligibility Level5 Model 2 Data Element 1 ($eligibLevel5Id_3)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,,Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),New Data Item,,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,,Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),New Data Item,,Disorder >2< Clinical tests Level5 Model 2 Data Element 1 ($clinicalLevel5Id_3)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,,Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),New Data Item,,Disorder >2< Guidance name 2 1 ($level5_guidanceid_3)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (1) name 2 1 (${phenotypeIds[1][0][0]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (2) name 2 1 (${phenotypeIds[1][0][1]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (3) name 2 1 (${phenotypeIds[1][0][2]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (4) name 2 1 (${phenotypeIds[1][0][3]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (5) name 2 1 (${phenotypeIds[1][0][4]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (6) name 2 1 (${phenotypeIds[1][0][5]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (7) name 2 1 (${phenotypeIds[1][0][6]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (8) name 2 1 (${phenotypeIds[1][0][7]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (9) name 2 1 (${phenotypeIds[1][0][8]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (10) name 2 1 (${phenotypeIds[1][0][9]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (11) name 2 1 (${phenotypeIds[1][0][10]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (12) name 2 1 (${phenotypeIds[1][0][11]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (13) name 2 1 (${phenotypeIds[1][0][12]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (14) name 2 1 (${phenotypeIds[1][0][13]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 1 ($phenotypeLevel5Id_3),New Data Item,,Phenotype (15) name 2 1 (${phenotypeIds[1][0][14]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (1) name 2 1 (${phenotypeIds[1][0][0]}),New Metadata,,OBO ID: HP:4
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (2) name 2 1 (${phenotypeIds[1][0][1]}),New Metadata,,OBO ID: HP:5
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (3) name 2 1 (${phenotypeIds[1][0][2]}),New Metadata,,OBO ID: HP:6
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (4) name 2 1 (${phenotypeIds[1][0][3]}),New Metadata,,OBO ID: HP:7
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (5) name 2 1 (${phenotypeIds[1][0][4]}),New Metadata,,OBO ID: HP:8
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (6) name 2 1 (${phenotypeIds[1][0][5]}),New Metadata,,OBO ID: HP:9
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (7) name 2 1 (${phenotypeIds[1][0][6]}),New Metadata,,OBO ID: HP:10
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (8) name 2 1 (${phenotypeIds[1][0][7]}),New Metadata,,OBO ID: HP:11
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (9) name 2 1 (${phenotypeIds[1][0][8]}),New Metadata,,OBO ID: HP:12
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (10) name 2 1 (${phenotypeIds[1][0][9]}),New Metadata,,OBO ID: HP:13
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (11) name 2 1 (${phenotypeIds[1][0][10]}),New Metadata,,OBO ID: HP:14
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (12) name 2 1 (${phenotypeIds[1][0][11]}),New Metadata,,OBO ID: HP:15
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (13) name 2 1 (${phenotypeIds[1][0][12]}),New Metadata,,OBO ID: HP:16
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (14) name 2 1 (${phenotypeIds[1][0][13]}),New Metadata,,OBO ID: HP:17
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Phenotype,Phenotype (15) name 2 1 (${phenotypeIds[1][0][14]}),New Metadata,,OBO ID: HP:18
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 1 ($clinicalLevel5Id_3),New Data Item,,Clinical tests (1) name 2 1 (${clinicalTestIds[1][0][0]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 1 ($clinicalLevel5Id_3),New Data Item,,Clinical tests (2) name 2 1 (${clinicalTestIds[1][0][1]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 1 ($clinicalLevel5Id_3),New Data Item,,Clinical tests (3) name 2 1 (${clinicalTestIds[1][0][2]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 1 ($clinicalLevel5Id_3),New Data Item,,Clinical tests (4) name 2 1 (${clinicalTestIds[1][0][3]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 1 ($level3_id_3),Disorder >>2<< heading Level4 Model Data Element 1 ($level4_id_3),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 1 ($clinicalLevel5Id_3),New Data Item,,Clinical tests (5) name 2 1 (${clinicalTestIds[1][0][4]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),,,,Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),New Data Item,,Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,,Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),New Data Item,,Disorder >2< Eligibility Level5 Model 2 Data Element 2 ($eligibLevel5Id_4)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,,Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),New Data Item,,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,,Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),New Data Item,,Disorder >2< Clinical tests Level5 Model 2 Data Element 2 ($clinicalLevel5Id_4)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,,Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),New Data Item,,Disorder >2< Guidance name 2 2 ($level5_guidanceid_4)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (1) name 2 2 (${phenotypeIds[1][1][0]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (2) name 2 2 (${phenotypeIds[1][1][1]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (3) name 2 2 (${phenotypeIds[1][1][2]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (4) name 2 2 (${phenotypeIds[1][1][3]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (5) name 2 2 (${phenotypeIds[1][1][4]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (6) name 2 2 (${phenotypeIds[1][1][5]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (7) name 2 2 (${phenotypeIds[1][1][6]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (8) name 2 2 (${phenotypeIds[1][1][7]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (9) name 2 2 (${phenotypeIds[1][1][8]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (10) name 2 2 (${phenotypeIds[1][1][9]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (11) name 2 2 (${phenotypeIds[1][1][10]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (12) name 2 2 (${phenotypeIds[1][1][11]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (13) name 2 2 (${phenotypeIds[1][1][12]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (14) name 2 2 (${phenotypeIds[1][1][13]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Disorder >2< Phenotypes Level5 Model 2 Data Element 2 ($phenotypeLevel5Id_4),New Data Item,,Phenotype (15) name 2 2 (${phenotypeIds[1][1][14]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (1) name 2 2 (${phenotypeIds[1][1][0]}),New Metadata,,OBO ID: HP:5
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (2) name 2 2 (${phenotypeIds[1][1][1]}),New Metadata,,OBO ID: HP:6
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (2) name 2 2 (${phenotypeIds[1][1][1]}),Change Description,,description for Phenotype (2) name 2 2 has been changed also
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (3) name 2 2 (${phenotypeIds[1][1][2]}),New Metadata,,OBO ID: HP:7
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (4) name 2 2 (${phenotypeIds[1][1][3]}),New Metadata,,OBO ID: HP:8
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (5) name 2 2 (${phenotypeIds[1][1][4]}),New Metadata,,OBO ID: HP:9
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (5) name 2 2 (${phenotypeIds[1][1][4]}),New Data Item,,Nested 1st level Phenotype ($nestedPheno_id1)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),Phenotype (5) name 2 2 (${phenotypeIds[1][1][4]}),Phenotype,Nested 1st level Phenotype ($nestedPheno_id1),New Data Item,,Nested 2nd level Phenotype ($nestedPheno_id2)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),Phenotype (5) name 2 2 (${phenotypeIds[1][1][4]})->Nested 1st level Phenotype ($nestedPheno_id1),Phenotype,Nested 2nd level Phenotype ($nestedPheno_id2),New Data Item,,Nested 3rd level Phenotype ($nestedPheno_id3)
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (6) name 2 2 (${phenotypeIds[1][1][5]}),New Metadata,,OBO ID: HP:10
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (7) name 2 2 (${phenotypeIds[1][1][6]}),New Metadata,,OBO ID: HP:11
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (8) name 2 2 (${phenotypeIds[1][1][7]}),New Metadata,,OBO ID: HP:12
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (9) name 2 2 (${phenotypeIds[1][1][8]}),New Metadata,,OBO ID: HP:13
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (10) name 2 2 (${phenotypeIds[1][1][9]}),New Metadata,,OBO ID: HP:14
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (11) name 2 2 (${phenotypeIds[1][1][10]}),New Metadata,,OBO ID: HP:15
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (12) name 2 2 (${phenotypeIds[1][1][11]}),New Metadata,,OBO ID: HP:16
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (13) name 2 2 (${phenotypeIds[1][1][12]}),New Metadata,,OBO ID: HP:17
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (14) name 2 2 (${phenotypeIds[1][1][13]}),New Metadata,,OBO ID: HP:18
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Phenotype,Phenotype (15) name 2 2 (${phenotypeIds[1][1][14]}),New Metadata,,OBO ID: HP:19
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 2 ($clinicalLevel5Id_4),New Data Item,,Clinical tests (1) name 2 2 (${clinicalTestIds[1][1][0]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 2 ($clinicalLevel5Id_4),New Data Item,,Clinical tests (2) name 2 2 (${clinicalTestIds[1][1][1]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 2 ($clinicalLevel5Id_4),New Data Item,,Clinical tests (3) name 2 2 (${clinicalTestIds[1][1][2]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 2 ($clinicalLevel5Id_4),New Data Item,,Clinical tests (4) name 2 2 (${clinicalTestIds[1][1][3]})
,Disorder >>>2<<< Level2 ($level2_id_2),Disorder >>>2<<< SubCondition Level3 Model Data Element 2 ($level3_id_4),Disorder >>2<< heading Level4 Model Data Element 2 ($level4_id_4),,Clinical tests,Disorder >2< Clinical tests Level5 Model 2 Data Element 2 ($clinicalLevel5Id_4),New Data Item,,Clinical tests (5) name 2 2 (${clinicalTestIds[1][1][4]})
"""
    }

}
