import org.springframework.http.HttpMethod

class DataModelUrlMappings {

    static mappings = {
        "/dataModel/d3View/$id"(controller: 'dataModel', action: 'd3View')
        "/dataModel/showAssetInAngular/$id"(controller: 'dataModel', action: 'showAssetInAngular', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel"(controller: 'dataModel', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel"(controller: 'dataModel', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/search/$search?"(controller: 'dataModel', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/validate"(controller: 'dataModel', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/validate"(controller: 'dataModel', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id"(controller: 'dataModel', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/availableReportDescriptors"(controller: 'dataModel', action: 'availableReportDescriptors', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id"(controller: 'dataModel', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataModel/$id"(controller: 'dataModel', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/search"(controller: 'dataModel', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type/search"(controller: 'dataModel', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type"(controller: 'dataModel', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type"(controller: 'dataModel', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type"(controller: 'dataModel', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type"(controller: 'dataModel', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataModel/$id/incoming/search"(controller: 'dataModel', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type/search"(controller: 'dataModel', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type"(controller: 'dataModel', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type"(controller: 'dataModel', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type"(controller: 'dataModel', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type"(controller: 'dataModel', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataModel/$id/incoming"(controller: 'dataModel', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/outgoing"(controller: 'dataModel', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/mapping/$destination"(controller: 'dataModel', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/mapping/$destination"(controller: 'dataModel', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataModel/$id/mapping"(controller: 'dataModel', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/typeHierarchy"(controller: 'dataModel', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/history"(controller: 'dataModel', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/path"(controller: 'dataModel', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/archive"(controller: 'dataModel', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/restore"(controller: 'dataModel', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/finalize"(controller: 'dataModel', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/clone/$destinationDataModelId"(controller: 'dataModel', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$source/merge/$destination"(controller: 'dataModel', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/preload"(controller: 'catalogue', action: 'dataModelsForPreload', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/preload"(controller: 'catalogue', action: 'importFromUrl', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/containsOrImports/$other"(controller: 'dataModel', action: 'containsOrImports', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/content"(controller: 'dataModel', action: 'content', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/newVersion"(controller: 'dataModel', action: 'newVersion', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/inventorySpreadsheet"(controller: 'dataModel', action: 'inventorySpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/gridSpreadsheet"(controller: 'dataModel', action: 'gridSpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/excelExporterSpreadsheet"(controller: 'dataModel', action: 'excelExporterSpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/inventoryDoc"(controller: 'dataModel', action: 'inventoryDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/dependents"(controller: 'dataModel', action: 'dependents', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/reindex"(controller: 'dataModel', action: 'reindex', method: HttpMethod.POST)
    }
}
