import org.springframework.http.HttpMethod

class ModelCatalogueCorePluginUrlMappings {

	static mappings = {

        "/api/modelCatalogue/core/forms/generate/$id" (controller: 'formGenerator', action: 'generateForm', method: HttpMethod.GET)
        "/api/modelCatalogue/core/forms/preview/$id" (controller: 'formGenerator', action: 'previewForm', method: HttpMethod.GET)

        "/catalogue/upload" (controller: "dataImport", action: 'upload', method: HttpMethod.POST)

        // Catalogue
        "/catalogue/ext/$key/$value" (controller: 'catalogue', action: 'ext', method: HttpMethod.GET)
        "/catalogue/ext/$key/$value/export" (controller: 'catalogue', action: 'ext', method: HttpMethod.GET)
        "/catalogue/$resource/$id(.${version})?" (controller: 'catalogue', action: 'xref', method: HttpMethod.GET)
        "/catalogue/$resource/$id(.${version})?/export" (controller: 'catalogue', action: 'xref', method: HttpMethod.GET) {
            format = 'xml'
        }

        "/api/modelCatalogue/core/feedback"(controller: 'catalogue', action: 'feedbacks', method: HttpMethod.GET)
        "/api/modelCatalogue/core/feedback/$key"(controller: 'catalogue', action: 'feedback', method: HttpMethod.GET)
        "/api/modelCatalogue/core/logs"(controller: 'logging', action: 'logsToAssets', method: HttpMethod.GET)

        // DataClass
        "/api/modelCatalogue/core/dataClass" (controller: 'dataClass', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass" (controller: 'dataClass', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/search/$search?" (controller: 'dataClass', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/validate" (controller: 'dataClass', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/validate" (controller: 'dataClass', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id" (controller: 'dataClass', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id" (controller: 'dataClass', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataClass/$id" (controller: 'dataClass', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/search" (controller: 'dataClass', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type/search" (controller: 'dataClass', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type" (controller: 'dataClass', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type" (controller: 'dataClass', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type" (controller: 'dataClass', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type" (controller: 'dataClass', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataClass/$id/incoming/search" (controller: 'dataClass', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type/search" (controller: 'dataClass', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type" (controller: 'dataClass', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type" (controller: 'dataClass', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type" (controller: 'dataClass', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type" (controller: 'dataClass', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataClass/$id/incoming" (controller: 'dataClass', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/outgoing" (controller: 'dataClass', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/mapping/$destination" (controller: 'dataClass', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/mapping/$destination" (controller: 'dataClass', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataClass/$id/mapping" (controller: 'dataClass', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/typeHierarchy" (controller: 'dataClass', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/history"(controller: 'dataClass', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/path"(controller: 'dataClass', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/archive"(controller: 'dataClass', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/restore"(controller: 'dataClass', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/finalize"(controller: 'dataClass', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/clone/$destinationDataModelId"(controller: 'dataClass', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$source/merge/$destination"(controller: 'dataClass', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/inventoryDoc"(controller: 'dataClass', action: 'inventoryDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/classificationChangelog"(controller: 'dataClass', action: 'changelogDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/inventorySpreadsheet"(controller: 'dataClass', action: 'inventorySpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/referenceType"(controller: 'dataClass', action: 'referenceTypes', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/content"(controller: 'dataClass', action: 'content', method: HttpMethod.GET)

        // DataClass
        "/api/modelCatalogue/core/model" (controller: 'dataClass', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model" (controller: 'dataClass', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/search/$search?" (controller: 'dataClass', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/validate" (controller: 'dataClass', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/validate" (controller: 'dataClass', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id" (controller: 'dataClass', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id" (controller: 'dataClass', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/model/$id" (controller: 'dataClass', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/model/$id/outgoing/search" (controller: 'dataClass', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/outgoing/$type/search" (controller: 'dataClass', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/outgoing/$type" (controller: 'dataClass', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/outgoing/$type" (controller: 'dataClass', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/outgoing/$type" (controller: 'dataClass', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/model/$id/outgoing/$type" (controller: 'dataClass', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/model/$id/incoming/search" (controller: 'dataClass', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/incoming/$type/search" (controller: 'dataClass', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/incoming/$type" (controller: 'dataClass', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/incoming/$type" (controller: 'dataClass', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/incoming/$type" (controller: 'dataClass', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/model/$id/incoming/$type" (controller: 'dataClass', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/model/$id/incoming" (controller: 'dataClass', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/outgoing" (controller: 'dataClass', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/mapping/$destination" (controller: 'dataClass', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/mapping/$destination" (controller: 'dataClass', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/model/$id/mapping" (controller: 'dataClass', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/typeHierarchy" (controller: 'dataClass', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/history"(controller: 'dataClass', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/path"(controller: 'dataClass', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/archive"(controller: 'dataClass', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/restore"(controller: 'dataClass', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/finalize"(controller: 'dataClass', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/clone/$destinationDataModelId"(controller: 'dataClass', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$source/merge/$destination"(controller: 'dataClass', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/inventoryDoc"(controller: 'dataClass', action: 'inventoryDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/classificationChangelog"(controller: 'dataClass', action: 'changelogDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/inventorySpreadsheet"(controller: 'dataClass', action: 'inventorySpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/referenceType"(controller: 'dataClass', action: 'referenceTypes', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/content"(controller: 'dataClass', action: 'content', method: HttpMethod.GET)

        // RelationshipType
        "/api/modelCatalogue/core/relationshipType" (controller: 'relationshipType', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/relationshipType" (controller: 'relationshipType', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/relationshipType/search/$search?" (controller: 'relationshipType', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/relationshipType/$id/validate" (controller: 'relationshipType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/relationshipType/validate" (controller: 'relationshipType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/relationshipType/$id" (controller: 'relationshipType', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/relationshipType/$id" (controller: 'relationshipType', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/relationshipType/$id" (controller: 'relationshipType', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/relationshipType/elementClasses"(controller: 'relationshipType', action: 'elementClasses', method: HttpMethod.GET)

        // CsvTransformation
        "/api/modelCatalogue/core/csvTransformation" (controller: 'csvTransformation', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/csvTransformation" (controller: 'csvTransformation', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/csvTransformation/search/$search?" (controller: 'csvTransformation', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/csvTransformation/$id/validate" (controller: 'csvTransformation', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/csvTransformation/validate" (controller: 'csvTransformation', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/csvTransformation/$id" (controller: 'csvTransformation', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/csvTransformation/$id" (controller: 'csvTransformation', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/csvTransformation/$id" (controller: 'csvTransformation', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/csvTransformation/$id/transform"(controller: 'csvTransformation', action: 'transform', method: HttpMethod.POST)

        // DataModelPolicy
        "/api/modelCatalogue/core/dataModelPolicy" (controller: 'dataModelPolicy', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModelPolicy" (controller: 'dataModelPolicy', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModelPolicy/search/$search?" (controller: 'dataModelPolicy', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModelPolicy/$id/validate" (controller: 'dataModelPolicy', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModelPolicy/validate" (controller: 'dataModelPolicy', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModelPolicy/$id" (controller: 'dataModelPolicy', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModelPolicy/$id" (controller: 'dataModelPolicy', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataModelPolicy/$id" (controller: 'dataModelPolicy', action: 'delete', method: HttpMethod.DELETE)


        // DataArchitect
        "/api/modelCatalogue/core/dataArchitect/metadataKeyCheck/$key?" (controller: "dataArchitect", action: 'metadataKeyCheck', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataArchitect/getSubModelElements/$modelId?" (controller: "dataArchitect", action: 'getSubModelElements', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataArchitect/findRelationsByMetadataKeys/$key?" (controller: "dataArchitect", action: 'findRelationsByMetadataKeys', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataArchitect/elementsFromCSV" (controller: "dataArchitect", action: "elementsFromCSV", method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataArchitect/modelsFromCSV" (controller: "dataArchitect", action: "modelsFromCSV", method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataArchitect/generateSuggestions" (controller: "dataArchitect", action: "generateSuggestions", method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataArchitect/deleteSuggestions" (controller: "dataArchitect", action: "deleteSuggestions", method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataArchitect/suggestionsNames" (controller: "dataArchitect", action: "suggestionsNames", method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataArchitect/imports/upload" (controller: "dataImport", action: 'upload', method: HttpMethod.POST)


        "/"(view:"index")
        "/load"(view:"load")
        "/api/modelCatalogue/core/search/reindex" (controller:"search", action : 'reindex', method: HttpMethod.POST)
        "/api/modelCatalogue/core/search/$search?" (controller:"search", action : 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/relationship/$id/restore" (controller:"relationship", action : 'restore', method: HttpMethod.POST)
	}
}
