import org.springframework.http.HttpMethod

class ModelCatalogueCorePluginUrlMappings {

	static mappings = {

        "/api/modelCatalogue/core/forms/generate/$id" (controller: 'formGenerator', action: 'generateForm', method: HttpMethod.GET)
        "/api/modelCatalogue/core/forms/preview/$id" (controller: 'formGenerator', action: 'previewForm', method: HttpMethod.GET)

        "/catalogue/upload" (controller: "dataImport", action: 'upload', method: HttpMethod.POST)

        // Catalogue
        "/catalogue/ext/$key/$value" (controller: 'catalogue', action: 'ext', method: HttpMethod.GET)
        "/catalogue/ext/$key/$value/export" (controller: 'catalogue', action: 'ext', method: HttpMethod.GET)
        "/catalogue/$resource/$id(.${version})?" (controller: 'catalogue', action: 'xref', method: HttpMethod.GET)
        "/catalogue/$resource/$id(.${version})?/export" (controller: 'catalogue', action: 'xref', method: HttpMethod.GET) {
            format = 'xml'
        }

        "/api/modelCatalogue/core/feedback"(controller: 'catalogue', action: 'feedbacks', method: HttpMethod.GET)
        "/api/modelCatalogue/core/feedback/$key"(controller: 'catalogue', action: 'feedback', method: HttpMethod.GET)
        "/api/modelCatalogue/core/logs"(controller: 'logging', action: 'logsToAssets', method: HttpMethod.GET)

        // Asset
        "/api/modelCatalogue/core/asset" (controller: 'asset', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset" (controller: 'asset', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/search/$search?" (controller: 'asset', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/validate" (controller: 'asset', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/validate" (controller: 'asset', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id" (controller: 'asset', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id" (controller: 'asset', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/asset/$id" (controller: 'asset', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/asset/$id/outgoing/search" (controller: 'asset', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/outgoing/$type/search" (controller: 'asset', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/outgoing/$type" (controller: 'asset', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/outgoing/$type" (controller: 'asset', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id/outgoing/$type" (controller: 'asset', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/asset/$id/outgoing/$type" (controller: 'asset', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/asset/$id/incoming/search" (controller: 'asset', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/incoming/$type/search" (controller: 'asset', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/incoming/$type" (controller: 'asset', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/incoming/$type" (controller: 'asset', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id/incoming/$type" (controller: 'asset', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/asset/$id/incoming/$type" (controller: 'asset', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/asset/$id/incoming" (controller: 'asset', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/outgoing" (controller: 'asset', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/mapping/$destination" (controller: 'asset', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id/mapping/$destination" (controller: 'asset', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/asset/$id/mapping" (controller: 'asset', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/typeHierarchy" (controller: 'asset', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/history"(controller: 'asset', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/path"(controller: 'asset', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/archive"(controller: 'asset', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id/restore"(controller: 'asset', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id/finalize"(controller: 'asset', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id/clone/$destinationDataModelId"(controller: 'asset', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$source/merge/$destination"(controller: 'asset', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/upload"(controller: 'asset', action: 'upload', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id/upload"(controller: 'asset', action: 'upload', method: HttpMethod.POST)
        "/api/modelCatalogue/core/asset/$id/download"(controller: 'asset', action: 'download', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/content"(controller: 'asset', action: 'content', method: HttpMethod.GET)
        "/api/modelCatalogue/core/asset/$id/validateXml"(controller: 'asset', action: 'validateXml', method: HttpMethod.POST)

        // DataElement
        "/api/modelCatalogue/core/dataElement" (controller: 'dataElement', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement" (controller: 'dataElement', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/search/$search?" (controller: 'dataElement', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/validate" (controller: 'dataElement', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/validate" (controller: 'dataElement', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$id" (controller: 'dataElement', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id" (controller: 'dataElement', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataElement/$id" (controller: 'dataElement', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataElement/$id/outgoing/search" (controller: 'dataElement', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/outgoing/$type/search" (controller: 'dataElement', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/outgoing/$type" (controller: 'dataElement', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/outgoing/$type" (controller: 'dataElement', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$id/outgoing/$type" (controller: 'dataElement', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataElement/$id/outgoing/$type" (controller: 'dataElement', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataElement/$id/incoming/search" (controller: 'dataElement', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/incoming/$type/search" (controller: 'dataElement', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/incoming/$type" (controller: 'dataElement', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/incoming/$type" (controller: 'dataElement', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$id/incoming/$type" (controller: 'dataElement', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataElement/$id/incoming/$type" (controller: 'dataElement', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataElement/$id/incoming" (controller: 'dataElement', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/outgoing" (controller: 'dataElement', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/mapping/$destination" (controller: 'dataElement', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$id/mapping/$destination" (controller: 'dataElement', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataElement/$id/mapping" (controller: 'dataElement', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/typeHierarchy" (controller: 'dataElement', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/history"(controller: 'dataElement', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/path"(controller: 'dataElement', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataElement/$id/archive"(controller: 'dataElement', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$id/restore"(controller: 'dataElement', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$id/finalize"(controller: 'dataElement', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$id/clone/$destinationDataModelId"(controller: 'dataElement', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$source/merge/$destination"(controller: 'dataElement', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataElement/$id/content"(controller: 'dataElement', action: 'content', method: HttpMethod.GET)

        // DataClass
        "/api/modelCatalogue/core/dataClass" (controller: 'dataClass', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass" (controller: 'dataClass', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/search/$search?" (controller: 'dataClass', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/validate" (controller: 'dataClass', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/validate" (controller: 'dataClass', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id" (controller: 'dataClass', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id" (controller: 'dataClass', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataClass/$id" (controller: 'dataClass', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/search" (controller: 'dataClass', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type/search" (controller: 'dataClass', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type" (controller: 'dataClass', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type" (controller: 'dataClass', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type" (controller: 'dataClass', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataClass/$id/outgoing/$type" (controller: 'dataClass', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataClass/$id/incoming/search" (controller: 'dataClass', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type/search" (controller: 'dataClass', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type" (controller: 'dataClass', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type" (controller: 'dataClass', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type" (controller: 'dataClass', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataClass/$id/incoming/$type" (controller: 'dataClass', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataClass/$id/incoming" (controller: 'dataClass', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/outgoing" (controller: 'dataClass', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/mapping/$destination" (controller: 'dataClass', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/mapping/$destination" (controller: 'dataClass', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataClass/$id/mapping" (controller: 'dataClass', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/typeHierarchy" (controller: 'dataClass', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/history"(controller: 'dataClass', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/path"(controller: 'dataClass', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/archive"(controller: 'dataClass', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/restore"(controller: 'dataClass', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/finalize"(controller: 'dataClass', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/clone/$destinationDataModelId"(controller: 'dataClass', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$source/merge/$destination"(controller: 'dataClass', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataClass/$id/inventoryDoc"(controller: 'dataClass', action: 'inventoryDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/classificationChangelog"(controller: 'dataClass', action: 'changelogDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/inventorySpreadsheet"(controller: 'dataClass', action: 'inventorySpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/referenceType"(controller: 'dataClass', action: 'referenceTypes', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataClass/$id/content"(controller: 'dataClass', action: 'content', method: HttpMethod.GET)

        // CatalogueElement
        "/api/modelCatalogue/core/catalogueElement" (controller: 'catalogueElement', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement" (controller: 'catalogueElement', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/search/$search?" (controller: 'catalogueElement', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/validate" (controller: 'catalogueElement', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/validate" (controller: 'catalogueElement', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/$id" (controller: 'catalogueElement', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id" (controller: 'catalogueElement', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/catalogueElement/$id" (controller: 'catalogueElement', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/catalogueElement/$id/outgoing/search" (controller: 'catalogueElement', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/outgoing/$type/search" (controller: 'catalogueElement', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/outgoing/$type" (controller: 'catalogueElement', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/outgoing/$type" (controller: 'catalogueElement', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/$id/outgoing/$type" (controller: 'catalogueElement', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/catalogueElement/$id/outgoing/$type" (controller: 'catalogueElement', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/catalogueElement/$id/incoming/search" (controller: 'catalogueElement', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/incoming/$type/search" (controller: 'catalogueElement', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/incoming/$type" (controller: 'catalogueElement', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/incoming/$type" (controller: 'catalogueElement', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/$id/incoming/$type" (controller: 'catalogueElement', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/catalogueElement/$id/incoming/$type" (controller: 'catalogueElement', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/catalogueElement/$id/incoming" (controller: 'catalogueElement', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/outgoing" (controller: 'catalogueElement', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/mapping/$destination" (controller: 'catalogueElement', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/$id/mapping/$destination" (controller: 'catalogueElement', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/catalogueElement/$id/mapping" (controller: 'catalogueElement', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/typeHierarchy" (controller: 'catalogueElement', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/history"(controller: 'catalogueElement', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/path"(controller: 'catalogueElement', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/catalogueElement/$id/archive"(controller: 'catalogueElement', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/$id/restore"(controller: 'catalogueElement', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/$id/finalize"(controller: 'catalogueElement', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/$id/clone/$destinationDataModelId"(controller: 'catalogueElement', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/catalogueElement/$source/merge/$destination"(controller: 'catalogueElement', action: 'merge', method: HttpMethod.POST)

        // DataType
        "/api/modelCatalogue/core/dataType" (controller: 'dataType', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType" (controller: 'dataType', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/search/$search?" (controller: 'dataType', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/validate" (controller: 'dataType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/validate" (controller: 'dataType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$id" (controller: 'dataType', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id" (controller: 'dataType', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataType/$id" (controller: 'dataType', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataType/$id/outgoing/search" (controller: 'dataType', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/outgoing/$type/search" (controller: 'dataType', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/outgoing/$type" (controller: 'dataType', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/outgoing/$type" (controller: 'dataType', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$id/outgoing/$type" (controller: 'dataType', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataType/$id/outgoing/$type" (controller: 'dataType', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataType/$id/incoming/search" (controller: 'dataType', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/incoming/$type/search" (controller: 'dataType', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/incoming/$type" (controller: 'dataType', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/incoming/$type" (controller: 'dataType', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$id/incoming/$type" (controller: 'dataType', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataType/$id/incoming/$type" (controller: 'dataType', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataType/$id/incoming" (controller: 'dataType', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/outgoing" (controller: 'dataType', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/mapping/$destination" (controller: 'dataType', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$id/mapping/$destination" (controller: 'dataType', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataType/$id/mapping" (controller: 'dataType', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/typeHierarchy" (controller: 'dataType', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/history"(controller: 'dataType', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/path"(controller: 'dataType', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/archive"(controller: 'dataType', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$id/restore"(controller: 'dataType', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$id/finalize"(controller: 'dataType', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$id/clone/$destinationDataModelId"(controller: 'dataType', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$source/merge/$destination"(controller: 'dataType', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataType/$id/dataElement"(controller: 'dataType', action: 'dataElements', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/convert/$destination"(controller: 'dataType', action: 'convert', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataType/$id/validateValue"(controller: 'dataType', action: 'validateValue', method: HttpMethod.GET)

        // EnumeratedType
        "/api/modelCatalogue/core/enumeratedType" (controller: 'enumeratedType', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType" (controller: 'enumeratedType', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/search/$search?" (controller: 'enumeratedType', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/validate" (controller: 'enumeratedType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id/setDeprecated" (controller: 'enumeratedType', action: 'setDeprecated', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/validate" (controller: 'enumeratedType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id" (controller: 'enumeratedType', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id" (controller: 'enumeratedType', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/enumeratedType/$id" (controller: 'enumeratedType', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/enumeratedType/$id/outgoing/search" (controller: 'enumeratedType', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/outgoing/$type/search" (controller: 'enumeratedType', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/outgoing/$type" (controller: 'enumeratedType', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/outgoing/$type" (controller: 'enumeratedType', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id/outgoing/$type" (controller: 'enumeratedType', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/enumeratedType/$id/outgoing/$type" (controller: 'enumeratedType', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/enumeratedType/$id/incoming/search" (controller: 'enumeratedType', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/incoming/$type/search" (controller: 'enumeratedType', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/incoming/$type" (controller: 'enumeratedType', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/incoming/$type" (controller: 'enumeratedType', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id/incoming/$type" (controller: 'enumeratedType', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/enumeratedType/$id/incoming/$type" (controller: 'enumeratedType', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/enumeratedType/$id/incoming" (controller: 'enumeratedType', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/outgoing" (controller: 'enumeratedType', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/mapping/$destination" (controller: 'enumeratedType', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id/mapping/$destination" (controller: 'enumeratedType', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/enumeratedType/$id/mapping" (controller: 'enumeratedType', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/typeHierarchy" (controller: 'enumeratedType', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/history"(controller: 'enumeratedType', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/path"(controller: 'enumeratedType', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/archive"(controller: 'enumeratedType', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id/restore"(controller: 'enumeratedType', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id/finalize"(controller: 'enumeratedType', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id/clone/$destinationDataModelId"(controller: 'enumeratedType', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$source/merge/$destination"(controller: 'enumeratedType', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/enumeratedType/$id/dataElement"(controller: 'enumeratedType', action: 'dataElements', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/convert/$destination"(controller: 'enumeratedType', action: 'convert', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/validateValue"(controller: 'enumeratedType', action: 'validateValue', method: HttpMethod.GET)
        "/api/modelCatalogue/core/enumeratedType/$id/content"(controller: 'enumeratedType', action: 'content', method: HttpMethod.GET)

        // ReferenceType
        "/api/modelCatalogue/core/referenceType" (controller: 'referenceType', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType" (controller: 'referenceType', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/search/$search?" (controller: 'referenceType', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/validate" (controller: 'referenceType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/validate" (controller: 'referenceType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$id" (controller: 'referenceType', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id" (controller: 'referenceType', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/referenceType/$id" (controller: 'referenceType', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/referenceType/$id/outgoing/search" (controller: 'referenceType', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/outgoing/$type/search" (controller: 'referenceType', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/outgoing/$type" (controller: 'referenceType', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/outgoing/$type" (controller: 'referenceType', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$id/outgoing/$type" (controller: 'referenceType', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/referenceType/$id/outgoing/$type" (controller: 'referenceType', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/referenceType/$id/incoming/search" (controller: 'referenceType', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/incoming/$type/search" (controller: 'referenceType', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/incoming/$type" (controller: 'referenceType', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/incoming/$type" (controller: 'referenceType', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$id/incoming/$type" (controller: 'referenceType', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/referenceType/$id/incoming/$type" (controller: 'referenceType', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/referenceType/$id/incoming" (controller: 'referenceType', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/outgoing" (controller: 'referenceType', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/mapping/$destination" (controller: 'referenceType', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$id/mapping/$destination" (controller: 'referenceType', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/referenceType/$id/mapping" (controller: 'referenceType', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/typeHierarchy" (controller: 'referenceType', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/history"(controller: 'referenceType', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/path"(controller: 'referenceType', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/archive"(controller: 'referenceType', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$id/restore"(controller: 'referenceType', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$id/finalize"(controller: 'referenceType', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$id/clone/$destinationDataModelId"(controller: 'referenceType', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$source/merge/$destination"(controller: 'referenceType', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/referenceType/$id/dataElement"(controller: 'referenceType', action: 'dataElements', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/convert/$destination"(controller: 'referenceType', action: 'convert', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/validateValue"(controller: 'referenceType', action: 'validateValue', method: HttpMethod.GET)
        "/api/modelCatalogue/core/referenceType/$id/content"(controller: 'referenceType', action: 'content', method: HttpMethod.GET)

        // PrimitiveType
        "/api/modelCatalogue/core/primitiveType" (controller: 'primitiveType', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType" (controller: 'primitiveType', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/search/$search?" (controller: 'primitiveType', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/validate" (controller: 'primitiveType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/validate" (controller: 'primitiveType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$id" (controller: 'primitiveType', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id" (controller: 'primitiveType', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/primitiveType/$id" (controller: 'primitiveType', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/primitiveType/$id/outgoing/search" (controller: 'primitiveType', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/outgoing/$type/search" (controller: 'primitiveType', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/outgoing/$type" (controller: 'primitiveType', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/outgoing/$type" (controller: 'primitiveType', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$id/outgoing/$type" (controller: 'primitiveType', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/primitiveType/$id/outgoing/$type" (controller: 'primitiveType', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/primitiveType/$id/incoming/search" (controller: 'primitiveType', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/incoming/$type/search" (controller: 'primitiveType', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/incoming/$type" (controller: 'primitiveType', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/incoming/$type" (controller: 'primitiveType', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$id/incoming/$type" (controller: 'primitiveType', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/primitiveType/$id/incoming/$type" (controller: 'primitiveType', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/primitiveType/$id/incoming" (controller: 'primitiveType', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/outgoing" (controller: 'primitiveType', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/mapping/$destination" (controller: 'primitiveType', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$id/mapping/$destination" (controller: 'primitiveType', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/primitiveType/$id/mapping" (controller: 'primitiveType', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/typeHierarchy" (controller: 'primitiveType', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/history"(controller: 'primitiveType', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/path"(controller: 'primitiveType', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/archive"(controller: 'primitiveType', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$id/restore"(controller: 'primitiveType', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$id/finalize"(controller: 'primitiveType', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$id/clone/$destinationDataModelId"(controller: 'primitiveType', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$source/merge/$destination"(controller: 'primitiveType', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/primitiveType/$id/dataElement"(controller: 'primitiveType', action: 'dataElements', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/convert/$destination"(controller: 'primitiveType', action: 'convert', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/validateValue"(controller: 'primitiveType', action: 'validateValue', method: HttpMethod.GET)
        "/api/modelCatalogue/core/primitiveType/$id/content"(controller: 'primitiveType', action: 'content', method: HttpMethod.GET)

        // MeasurementUnit
        "/api/modelCatalogue/core/measurementUnit" (controller: 'measurementUnit', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit" (controller: 'measurementUnit', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/search/$search?" (controller: 'measurementUnit', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/validate" (controller: 'measurementUnit', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/validate" (controller: 'measurementUnit', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$id" (controller: 'measurementUnit', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id" (controller: 'measurementUnit', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/measurementUnit/$id" (controller: 'measurementUnit', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/measurementUnit/$id/outgoing/search" (controller: 'measurementUnit', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/outgoing/$type/search" (controller: 'measurementUnit', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/outgoing/$type" (controller: 'measurementUnit', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/outgoing/$type" (controller: 'measurementUnit', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$id/outgoing/$type" (controller: 'measurementUnit', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/measurementUnit/$id/outgoing/$type" (controller: 'measurementUnit', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/measurementUnit/$id/incoming/search" (controller: 'measurementUnit', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/incoming/$type/search" (controller: 'measurementUnit', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/incoming/$type" (controller: 'measurementUnit', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/incoming/$type" (controller: 'measurementUnit', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$id/incoming/$type" (controller: 'measurementUnit', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/measurementUnit/$id/incoming/$type" (controller: 'measurementUnit', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/measurementUnit/$id/incoming" (controller: 'measurementUnit', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/outgoing" (controller: 'measurementUnit', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/mapping/$destination" (controller: 'measurementUnit', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$id/mapping/$destination" (controller: 'measurementUnit', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/measurementUnit/$id/mapping" (controller: 'measurementUnit', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/typeHierarchy" (controller: 'measurementUnit', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/history"(controller: 'measurementUnit', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/path"(controller: 'measurementUnit', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/measurementUnit/$id/archive"(controller: 'measurementUnit', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$id/restore"(controller: 'measurementUnit', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$id/finalize"(controller: 'measurementUnit', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$id/clone/$destinationDataModelId"(controller: 'measurementUnit', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$source/merge/$destination"(controller: 'measurementUnit', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/measurementUnit/$id/primitiveType"(controller: 'measurementUnit', action: 'primitiveTypes', method: HttpMethod.GET)

        // User
        "/api/modelCatalogue/core/user" (controller: 'user', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user" (controller: 'user', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/search/$search?" (controller: 'user', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/validate" (controller: 'user', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/validate" (controller: 'user', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id" (controller: 'user', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id" (controller: 'user', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/user/$id" (controller: 'user', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/user/$id/outgoing/search" (controller: 'user', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/outgoing/$type/search" (controller: 'user', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/outgoing/$type" (controller: 'user', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/outgoing/$type" (controller: 'user', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/outgoing/$type" (controller: 'user', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/user/$id/outgoing/$type" (controller: 'user', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/user/$id/incoming/search" (controller: 'user', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/incoming/$type/search" (controller: 'user', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/incoming/$type" (controller: 'user', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/incoming/$type" (controller: 'user', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/incoming/$type" (controller: 'user', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/user/$id/incoming/$type" (controller: 'user', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/user/$id/incoming" (controller: 'user', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/outgoing" (controller: 'user', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/mapping/$destination" (controller: 'user', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/mapping/$destination" (controller: 'user', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/user/$id/mapping" (controller: 'user', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/typeHierarchy" (controller: 'user', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/history"(controller: 'user', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/path"(controller: 'user', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/$id/archive"(controller: 'user', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/restore"(controller: 'user', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/finalize"(controller: 'user', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/clone/$destinationDataModelId"(controller: 'user', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$source/merge/$destination"(controller: 'user', action: 'merge', method: HttpMethod.POST)
        "/user/current"(controller: 'user', action: 'current', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/current"(controller: 'user', action: 'current', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/classifications"(controller: 'user', action: 'classifications', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/lastSeen"(controller: 'user', action: 'lastSeen', method: HttpMethod.GET)
        "/api/modelCatalogue/core/user/apikey"(controller: 'user', action: 'apiKey', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/favourite"(controller: 'user', action: 'addFavourite', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/favourite"(controller: 'user', action: 'removeFavourite', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/user/$id/enable"(controller: 'user', action: 'enable', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/disable"(controller: 'user', action: 'disable', method: HttpMethod.POST)
        "/api/modelCatalogue/core/user/$id/role/$role"(controller: 'user', action: 'role', method: HttpMethod.POST)

        // DataModel
        "/api/modelCatalogue/core/dataModel" (controller: 'dataModel', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel" (controller: 'dataModel', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/search/$search?" (controller: 'dataModel', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/validate" (controller: 'dataModel', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/validate" (controller: 'dataModel', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id" (controller: 'dataModel', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id" (controller: 'dataModel', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataModel/$id" (controller: 'dataModel', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/search" (controller: 'dataModel', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type/search" (controller: 'dataModel', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type" (controller: 'dataModel', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type" (controller: 'dataModel', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type" (controller: 'dataModel', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataModel/$id/outgoing/$type" (controller: 'dataModel', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataModel/$id/incoming/search" (controller: 'dataModel', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type/search" (controller: 'dataModel', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type" (controller: 'dataModel', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type" (controller: 'dataModel', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type" (controller: 'dataModel', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataModel/$id/incoming/$type" (controller: 'dataModel', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataModel/$id/incoming" (controller: 'dataModel', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/outgoing" (controller: 'dataModel', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/mapping/$destination" (controller: 'dataModel', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/mapping/$destination" (controller: 'dataModel', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/dataModel/$id/mapping" (controller: 'dataModel', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/typeHierarchy" (controller: 'dataModel', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/history"(controller: 'dataModel', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/path"(controller: 'dataModel', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/archive"(controller: 'dataModel', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/restore"(controller: 'dataModel', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/finalize"(controller: 'dataModel', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/clone/$destinationDataModelId"(controller: 'dataModel', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$source/merge/$destination"(controller: 'dataModel', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/preload"(controller: 'catalogue', action: 'dataModelsForPreload', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/preload"(controller: 'catalogue', action: 'importFromUrl', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/declares"(controller: 'dataModel', action: 'declares', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/containsOrImports/$other"(controller: 'dataModel', action: 'containsOrImports', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/content"(controller: 'dataModel', action: 'content', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/newVersion"(controller: 'dataModel', action: 'newVersion', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModel/$id/inventorySpreadsheet"(controller: 'dataModel', action: 'inventorySpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/gridSpreadsheet"(controller: 'dataModel', action: 'gridSpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/excelExporterSpreadsheet"(controller: 'dataModel', action: 'excelExporterSpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/inventoryDoc"(controller: 'dataModel', action: 'inventoryDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/dependents"(controller: 'dataModel', action: 'dependents', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModel/$id/reindex"(controller: 'dataModel', action: 'reindex', method: HttpMethod.POST)

        // Classification
        "/api/modelCatalogue/core/classification" (controller: 'dataModel', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification" (controller: 'dataModel', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/search/$search?" (controller: 'dataModel', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/validate" (controller: 'dataModel', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/validate" (controller: 'dataModel', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id" (controller: 'dataModel', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id" (controller: 'dataModel', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/classification/$id" (controller: 'dataModel', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/classification/$id/outgoing/search" (controller: 'dataModel', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/outgoing/$type/search" (controller: 'dataModel', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/outgoing/$type" (controller: 'dataModel', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/outgoing/$type" (controller: 'dataModel', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id/outgoing/$type" (controller: 'dataModel', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/classification/$id/outgoing/$type" (controller: 'dataModel', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/classification/$id/incoming/search" (controller: 'dataModel', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/incoming/$type/search" (controller: 'dataModel', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/incoming/$type" (controller: 'dataModel', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/incoming/$type" (controller: 'dataModel', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id/incoming/$type" (controller: 'dataModel', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/classification/$id/incoming/$type" (controller: 'dataModel', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/classification/$id/incoming" (controller: 'dataModel', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/outgoing" (controller: 'dataModel', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/mapping/$destination" (controller: 'dataModel', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id/mapping/$destination" (controller: 'dataModel', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/classification/$id/mapping" (controller: 'dataModel', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/typeHierarchy" (controller: 'dataModel', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/history"(controller: 'dataModel', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/path"(controller: 'dataModel', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/archive"(controller: 'dataModel', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id/restore"(controller: 'dataModel', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id/finalize"(controller: 'dataModel', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id/clone/$destinationDataModelId"(controller: 'dataModel', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$source/merge/$destination"(controller: 'dataModel', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/preload"(controller: 'catalogue', action: 'dataModelsForPreload', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/preload"(controller: 'catalogue', action: 'importFromUrl', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id/declares"(controller: 'dataModel', action: 'declares', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/containsOrImports/$other"(controller: 'dataModel', action: 'containsOrImports', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/content"(controller: 'dataModel', action: 'content', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/newVersion"(controller: 'dataModel', action: 'newVersion', method: HttpMethod.POST)
        "/api/modelCatalogue/core/classification/$id/inventorySpreadsheet"(controller: 'dataModel', action: 'inventorySpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/gridSpreadsheet"(controller: 'dataModel', action: 'gridSpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/excelExporterSpreadsheet"(controller: 'dataModel', action: 'excelExporterSpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/inventoryDoc"(controller: 'dataModel', action: 'inventoryDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/dependents"(controller: 'dataModel', action: 'dependents', method: HttpMethod.GET)
        "/api/modelCatalogue/core/classification/$id/reindex"(controller: 'dataModel', action: 'reindex', method: HttpMethod.POST)

        // DataClass
        "/api/modelCatalogue/core/model" (controller: 'dataClass', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model" (controller: 'dataClass', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/search/$search?" (controller: 'dataClass', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/validate" (controller: 'dataClass', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/validate" (controller: 'dataClass', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id" (controller: 'dataClass', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id" (controller: 'dataClass', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/model/$id" (controller: 'dataClass', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/model/$id/outgoing/search" (controller: 'dataClass', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/outgoing/$type/search" (controller: 'dataClass', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/outgoing/$type" (controller: 'dataClass', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/outgoing/$type" (controller: 'dataClass', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/outgoing/$type" (controller: 'dataClass', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/model/$id/outgoing/$type" (controller: 'dataClass', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/model/$id/incoming/search" (controller: 'dataClass', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/incoming/$type/search" (controller: 'dataClass', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/incoming/$type" (controller: 'dataClass', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/incoming/$type" (controller: 'dataClass', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/incoming/$type" (controller: 'dataClass', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/model/$id/incoming/$type" (controller: 'dataClass', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/model/$id/incoming" (controller: 'dataClass', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/outgoing" (controller: 'dataClass', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/mapping/$destination" (controller: 'dataClass', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/mapping/$destination" (controller: 'dataClass', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/model/$id/mapping" (controller: 'dataClass', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/typeHierarchy" (controller: 'dataClass', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/history"(controller: 'dataClass', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/path"(controller: 'dataClass', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/archive"(controller: 'dataClass', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/restore"(controller: 'dataClass', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/finalize"(controller: 'dataClass', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/clone/$destinationDataModelId"(controller: 'dataClass', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$source/merge/$destination"(controller: 'dataClass', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/model/$id/inventoryDoc"(controller: 'dataClass', action: 'inventoryDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/classificationChangelog"(controller: 'dataClass', action: 'changelogDoc', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/inventorySpreadsheet"(controller: 'dataClass', action: 'inventorySpreadsheet', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/referenceType"(controller: 'dataClass', action: 'referenceTypes', method: HttpMethod.GET)
        "/api/modelCatalogue/core/model/$id/content"(controller: 'dataClass', action: 'content', method: HttpMethod.GET)

        // ValidationRule
        "/api/modelCatalogue/core/validationRule" (controller: 'validationRule', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule" (controller: 'validationRule', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/search/$search?" (controller: 'validationRule', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/validate" (controller: 'validationRule', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/validate" (controller: 'validationRule', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$id" (controller: 'validationRule', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id" (controller: 'validationRule', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/validationRule/$id" (controller: 'validationRule', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/validationRule/$id/outgoing/search" (controller: 'validationRule', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/outgoing/$type/search" (controller: 'validationRule', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/outgoing/$type" (controller: 'validationRule', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/outgoing/$type" (controller: 'validationRule', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$id/outgoing/$type" (controller: 'validationRule', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/validationRule/$id/outgoing/$type" (controller: 'validationRule', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/validationRule/$id/incoming/search" (controller: 'validationRule', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/incoming/$type/search" (controller: 'validationRule', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/incoming/$type" (controller: 'validationRule', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/incoming/$type" (controller: 'validationRule', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$id/incoming/$type" (controller: 'validationRule', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/validationRule/$id/incoming/$type" (controller: 'validationRule', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/validationRule/$id/incoming" (controller: 'validationRule', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/outgoing" (controller: 'validationRule', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/mapping/$destination" (controller: 'validationRule', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$id/mapping/$destination" (controller: 'validationRule', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/validationRule/$id/mapping" (controller: 'validationRule', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/typeHierarchy" (controller: 'validationRule', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/history"(controller: 'validationRule', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/path"(controller: 'validationRule', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/validationRule/$id/archive"(controller: 'validationRule', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$id/restore"(controller: 'validationRule', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$id/finalize"(controller: 'validationRule', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$id/clone/$destinationDataModelId"(controller: 'validationRule', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$source/merge/$destination"(controller: 'validationRule', action: 'merge', method: HttpMethod.POST)
        "/api/modelCatalogue/core/validationRule/$id/content"(controller: 'validationRule', action: 'content', method: HttpMethod.GET)

        // Tag
        "/api/modelCatalogue/core/tag/forDataModel/$dataModelId"(controller: 'tag', action: 'forDataModel', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag" (controller: 'tag', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag" (controller: 'tag', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/search/$search?" (controller: 'tag', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/validate" (controller: 'tag', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/validate" (controller: 'tag', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/$id" (controller: 'tag', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id" (controller: 'tag', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/tag/$id" (controller: 'tag', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/tag/$id/outgoing/search" (controller: 'tag', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/outgoing/$type/search" (controller: 'tag', action: 'searchOutgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/outgoing/$type" (controller: 'tag', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/outgoing/$type" (controller: 'tag', action: 'addOutgoing', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/$id/outgoing/$type" (controller: 'tag', action: 'removeOutgoing', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/tag/$id/outgoing/$type" (controller: 'tag', action: 'reorderOutgoing', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/tag/$id/incoming/search" (controller: 'tag', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/incoming/$type/search" (controller: 'tag', action: 'searchIncoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/incoming/$type" (controller: 'tag', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/incoming/$type" (controller: 'tag', action: 'addIncoming', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/$id/incoming/$type" (controller: 'tag', action: 'removeIncoming', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/tag/$id/incoming/$type" (controller: 'tag', action: 'reorderIncoming', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/tag/$id/incoming" (controller: 'tag', action: 'incoming', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/outgoing" (controller: 'tag', action: 'outgoing', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/mapping/$destination" (controller: 'tag', action: 'addMapping', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/$id/mapping/$destination" (controller: 'tag', action: 'removeMapping', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/tag/$id/mapping" (controller: 'tag', action: 'mappings', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/typeHierarchy" (controller: 'tag', action: 'typeHierarchy', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/history"(controller: 'tag', action: 'history', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/path"(controller: 'tag', action: 'path', method: HttpMethod.GET)
        "/api/modelCatalogue/core/tag/$id/archive"(controller: 'tag', action: 'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/$id/restore"(controller: 'tag', action: 'restore', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/$id/finalize"(controller: 'tag', action: 'finalizeElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/$id/clone/$destinationDataModelId"(controller: 'tag', action: 'cloneElement', method: HttpMethod.POST)
        "/api/modelCatalogue/core/tag/$source/merge/$destination"(controller: 'tag', action: 'merge', method: HttpMethod.POST)

        // Batch
        "/api/modelCatalogue/core/batch" (controller: 'batch', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/batch" (controller: 'batch', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/batch/search/$search?" (controller: 'batch', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/batch/$id/validate" (controller: 'batch', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/batch/validate" (controller: 'batch', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/batch/$id" (controller: 'batch', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/batch/$id" (controller: 'batch', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/batch/$id" (controller: 'batch', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/batch/$id/archive"(controller: 'batch', action:  'archive', method: HttpMethod.POST)
        "/api/modelCatalogue/core/batch/$id/run"(controller: 'batch', action: 'runAll', method: HttpMethod.POST)
        "/api/modelCatalogue/core/batch/$id/actions/$state?"(controller: 'batch', action: 'listActions', method: HttpMethod.GET)
        "/api/modelCatalogue/core/batch/$id/actions/$actionId/dismiss"(controller: 'batch', action: 'dismiss', method: HttpMethod.POST)
        "/api/modelCatalogue/core/batch/$id/actions/$actionId/reactivate"(controller: 'batch', action: 'reactivate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/batch/$id/actions/$actionId/run"(controller: 'batch', action: 'run', method: HttpMethod.POST)
        "/api/modelCatalogue/core/batch/$id/actions/$actionId/parameters"(controller: 'batch', action: 'updateActionParameters', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/batch/$id/actions/$actionId/dependsOn"(controller: 'batch', action: 'removeDependency', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/batch/$id/actions/$actionId/dependsOn"(controller: 'batch', action: 'addDependency', method: HttpMethod.POST)

        // RelationshipType
        "/api/modelCatalogue/core/relationshipType" (controller: 'relationshipType', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/relationshipType" (controller: 'relationshipType', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/relationshipType/search/$search?" (controller: 'relationshipType', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/relationshipType/$id/validate" (controller: 'relationshipType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/relationshipType/validate" (controller: 'relationshipType', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/relationshipType/$id" (controller: 'relationshipType', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/relationshipType/$id" (controller: 'relationshipType', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/relationshipType/$id" (controller: 'relationshipType', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/relationshipType/elementClasses"(controller: 'relationshipType', action: 'elementClasses', method: HttpMethod.GET)

        // CsvTransformation
        "/api/modelCatalogue/core/csvTransformation" (controller: 'csvTransformation', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/csvTransformation" (controller: 'csvTransformation', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/csvTransformation/search/$search?" (controller: 'csvTransformation', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/csvTransformation/$id/validate" (controller: 'csvTransformation', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/csvTransformation/validate" (controller: 'csvTransformation', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/csvTransformation/$id" (controller: 'csvTransformation', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/csvTransformation/$id" (controller: 'csvTransformation', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/csvTransformation/$id" (controller: 'csvTransformation', action: 'delete', method: HttpMethod.DELETE)
        "/api/modelCatalogue/core/csvTransformation/$id/transform"(controller: 'csvTransformation', action: 'transform', method: HttpMethod.POST)

        // DataModelPolicy
        "/api/modelCatalogue/core/dataModelPolicy" (controller: 'dataModelPolicy', action: 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModelPolicy" (controller: 'dataModelPolicy', action: 'save', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModelPolicy/search/$search?" (controller: 'dataModelPolicy', action: 'search', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModelPolicy/$id/validate" (controller: 'dataModelPolicy', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModelPolicy/validate" (controller: 'dataModelPolicy', action: 'validate', method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataModelPolicy/$id" (controller: 'dataModelPolicy', action: 'show', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataModelPolicy/$id" (controller: 'dataModelPolicy', action: 'update', method: HttpMethod.PUT)
        "/api/modelCatalogue/core/dataModelPolicy/$id" (controller: 'dataModelPolicy', action: 'delete', method: HttpMethod.DELETE)


        // DataArchitect
        "/api/modelCatalogue/core/dataArchitect/metadataKeyCheck/$key?" (controller: "dataArchitect", action: 'metadataKeyCheck', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataArchitect/getSubModelElements/$modelId?" (controller: "dataArchitect", action: 'getSubModelElements', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataArchitect/findRelationsByMetadataKeys/$key?" (controller: "dataArchitect", action: 'findRelationsByMetadataKeys', method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataArchitect/elementsFromCSV" (controller: "dataArchitect", action: "elementsFromCSV", method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataArchitect/modelsFromCSV" (controller: "dataArchitect", action: "modelsFromCSV", method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataArchitect/generateSuggestions" (controller: "dataArchitect", action: "generateSuggestions", method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataArchitect/deleteSuggestions" (controller: "dataArchitect", action: "deleteSuggestions", method: HttpMethod.POST)
        "/api/modelCatalogue/core/dataArchitect/suggestionsNames" (controller: "dataArchitect", action: "suggestionsNames", method: HttpMethod.GET)
        "/api/modelCatalogue/core/dataArchitect/imports/upload" (controller: "dataImport", action: 'upload', method: HttpMethod.POST)


        "/"(view:"index")
        "/load"(view:"load")
        "/api/modelCatalogue/core/search/reindex" (controller:"search", action : 'reindex', method: HttpMethod.POST)
        "/api/modelCatalogue/core/search/$search?" (controller:"search", action : 'index', method: HttpMethod.GET)
        "/api/modelCatalogue/core/relationship/$id/restore" (controller:"relationship", action : 'restore', method: HttpMethod.POST)


	}
}
