/** Generated automatically from dataElementControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElementControllerIntegrationSpec'] = fixtures['dataElementControllerIntegrationSpec'] || {};
        var dataElementControllerIntegrationSpec = fixtures['dataElementControllerIntegrationSpec']

        window.fixtures.dataElementControllerIntegrationSpec.addOutgoing = {
   "id": 2,
   "source": {
      "id": 10,
      "name": "DE_author1",
      "link": "/dataElement/10"
   },
   "type": {
      "id": 3,
      "name": "relationship",
      "link": "/relationshipType/3"
   },
   "destination": {
      "id": 29,
      "name": "DE_author",
      "link": "/dataElement/29"
   }
}

    })(window)