/** Generated automatically from dataElementControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElementControllerIntegrationSpec'] = fixtures['dataElementControllerIntegrationSpec'] || {};
        var dataElementControllerIntegrationSpec = fixtures['dataElementControllerIntegrationSpec']

        window.fixtures.dataElementControllerIntegrationSpec.list4 = {
   "total": 12,
   "previous": "/dataElement/?max=4&offset=4",
   "page": 4,
   "itemType": "org.modelcatalogue.core.DataElement",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/24/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/24",
         "code": "XXX_v8",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/24/incoming"
         },
         "version": 0,
         "id": 24,
         "description": "the DE_author of the book",
         "name": "auth8",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/24/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/24/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/29/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/29",
         "code": "XXX",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/29/incoming"
         },
         "version": 0,
         "id": 29,
         "description": "the DE_author of the book",
         "name": "DE_author",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/29/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/29/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/40/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/40",
         "code": null,
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/40/incoming"
         },
         "version": 0,
         "id": 40,
         "description": "the title of the book",
         "name": "title",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/40/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/40/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/72/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/72",
         "code": null,
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/72/incoming"
         },
         "version": 0,
         "id": 72,
         "description": "the writer of the book",
         "name": "writer",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/72/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/72/outgoing/instantiation"
         },
         "versionNumber": 0.1
      }
   ],
   "offset": 8,
   "success": true,
   "size": 4
}

    })(window)