/** Generated automatically from dataElementControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElementControllerIntegrationSpec'] = fixtures['dataElementControllerIntegrationSpec'] || {};
        var dataElementControllerIntegrationSpec = fixtures['dataElementControllerIntegrationSpec']

        window.fixtures.dataElementControllerIntegrationSpec.list2 = {
   "total": 12,
   "previous": "",
   "page": 5,
   "itemType": "org.modelcatalogue.core.DataElement",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/dataElement/?max=5&offset=5",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/1/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/1",
         "code": "XXX_v9",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/1/incoming"
         },
         "version": 0,
         "id": 1,
         "description": "the DE_author of the book",
         "name": "auth9",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/1/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/1/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/10/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/10",
         "code": "XXX_1",
         "ext": {"metadata": "metadata value"},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/10/incoming"
         },
         "version": 1,
         "id": 10,
         "description": "the DE_author of the book",
         "name": "DE_author1",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/10/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/10/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/12/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/12",
         "code": "XXX_v2",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/12/incoming"
         },
         "version": 0,
         "id": 12,
         "description": "the DE_author of the book",
         "name": "AUTHOR",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/12/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/12/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/14/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/14",
         "code": "XXX_v3",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/14/incoming"
         },
         "version": 0,
         "id": 14,
         "description": "the DE_author of the book",
         "name": "auth",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/14/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/14/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/16/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/16",
         "code": "XXX_v4",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/16/incoming"
         },
         "version": 0,
         "id": 16,
         "description": "the DE_author of the book",
         "name": "auth4",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/16/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/16/outgoing/instantiation"
         },
         "versionNumber": 0.1
      }
   ],
   "offset": 0,
   "success": true,
   "size": 5
}

    })(window)