/** Generated automatically from dataElementControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElementControllerIntegrationSpec'] = fixtures['dataElementControllerIntegrationSpec'] || {};
        var dataElementControllerIntegrationSpec = fixtures['dataElementControllerIntegrationSpec']

        window.fixtures.dataElementControllerIntegrationSpec.saveOk = {
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/85/outgoing"
   },
   "status": "DRAFT",
   "link": "/dataElement/85",
   "code": "12312312308",
   "ext": {},
   "elementType": "org.modelcatalogue.core.DataElement",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/85/incoming"
   },
   "version": 0,
   "id": 85,
   "description": "the DE_author of the book",
   "name": "new data element",
   "containedIn": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/85/incoming/containment"
   },
   "elementTypeName": "Data Element",
   "instantiatedBy": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/85/outgoing/instantiation"
   },
   "versionNumber": 0.1
}

    })(window)