/** Generated automatically from dataElementControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElementControllerIntegrationSpec'] = fixtures['dataElementControllerIntegrationSpec'] || {};
        var dataElementControllerIntegrationSpec = fixtures['dataElementControllerIntegrationSpec']

        window.fixtures.dataElementControllerIntegrationSpec.updateOk = {
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/29/outgoing"
   },
   "status": "DRAFT",
   "link": "/dataElement/29",
   "code": "AA123",
   "ext": {},
   "elementType": "org.modelcatalogue.core.DataElement",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/29/incoming"
   },
   "version": 1,
   "id": 29,
   "description": "edited description",
   "name": "changedName",
   "containedIn": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/29/incoming/containment"
   },
   "elementTypeName": "Data Element",
   "instantiatedBy": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/29/outgoing/instantiation"
   },
   "versionNumber": 0.1
}

    })(window)