/** Generated automatically from model. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['model'] = fixtures['model'] || {};
        var model = fixtures['model']

        window.fixtures.model.addIncoming = {
   "id": 4267,
   "source": {
      "id": 33,
      "name": "book",
      "link": "/model/33"
   },
   "type": {
      "id": 3,
      "name": "relationship",
      "link": "/relationshipType/3"
   },
   "destination": {
      "id": 70,
      "name": "chapter1",
      "link": "/model/70"
   }
}

    })(window)