/** Generated automatically from model. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['model'] = fixtures['model'] || {};
        var model = fixtures['model']

        window.fixtures.model.addOutgoingFailed = {"errors": [{
   "field": "relationshipType",
   "message": "Property [relationshipType] of class [class org.modelcatalogue.core.Relationship] with value [RelationshipType[id: 6, name: falseRuleReturn]] does not pass custom validation",
   "rejected-value": {
      "id": 6,
      "sourceClass": "org.modelcatalogue.core.DataElement",
      "sourceToDestination": "broader term for",
      "destinationClass": "org.modelcatalogue.core.DataElement",
      "name": "falseRuleReturn",
      "link": "/relationshipType/6",
      "elementTypeName": "Relationship Type",
      "elementType": "org.modelcatalogue.core.RelationshipType",
      "destinationToSource": "narrower term for",
      "version": 0
   },
   "object": "org.modelcatalogue.core.Relationship"
}]}

    })(window)