/** Generated automatically from model. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['model'] = fixtures['model'] || {};
        var model = fixtures['model']

        window.fixtures.model.list3 = {
   "total": 12,
   "previous": "/model/?max=5&offset=0",
   "page": 5,
   "itemType": "org.modelcatalogue.core.Model",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/model/?max=5&offset=10",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/53/outgoing"
         },
         "status": "DRAFT",
         "link": "/model/53",
         "hasContextOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/53/incoming/context"
         },
         "childOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/53/incoming/hierarchy"
         },
         "contains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/53/outgoing/containment"
         },
         "ext": {},
         "elementType": "org.modelcatalogue.core.Model",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/53/incoming"
         },
         "version": 0,
         "id": 53,
         "description": "this is a model test5",
         "name": "mTest5",
         "elementTypeName": "Model",
         "parentOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/53/outgoing/hierarchy"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/54/outgoing"
         },
         "status": "DRAFT",
         "link": "/model/54",
         "hasContextOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/54/incoming/context"
         },
         "childOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/54/incoming/hierarchy"
         },
         "contains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/54/outgoing/containment"
         },
         "ext": {},
         "elementType": "org.modelcatalogue.core.Model",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/54/incoming"
         },
         "version": 0,
         "id": 54,
         "description": "this is a model test4",
         "name": "mTest4",
         "elementTypeName": "Model",
         "parentOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/54/outgoing/hierarchy"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/67/outgoing"
         },
         "status": "DRAFT",
         "link": "/model/67",
         "hasContextOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/67/incoming/context"
         },
         "childOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/67/incoming/hierarchy"
         },
         "contains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/67/outgoing/containment"
         },
         "ext": {},
         "elementType": "org.modelcatalogue.core.Model",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/67/incoming"
         },
         "version": 0,
         "id": 67,
         "description": "this is a model test2",
         "name": "mTest2",
         "elementTypeName": "Model",
         "parentOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/67/outgoing/hierarchy"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/69/outgoing"
         },
         "status": "DRAFT",
         "link": "/model/69",
         "hasContextOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/69/incoming/context"
         },
         "childOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/69/incoming/hierarchy"
         },
         "contains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/69/outgoing/containment"
         },
         "ext": {},
         "elementType": "org.modelcatalogue.core.Model",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/69/incoming"
         },
         "version": 0,
         "id": 69,
         "description": "this is a model test3",
         "name": "mTest3",
         "elementTypeName": "Model",
         "parentOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/69/outgoing/hierarchy"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/70/outgoing"
         },
         "status": "DRAFT",
         "link": "/model/70",
         "hasContextOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/70/incoming/context"
         },
         "childOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/70/incoming/hierarchy"
         },
         "contains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/70/outgoing/containment"
         },
         "ext": {},
         "elementType": "org.modelcatalogue.core.Model",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/70/incoming"
         },
         "version": 0,
         "id": 70,
         "description": "The Jabberwocky chapter for a book",
         "name": "chapter1",
         "elementTypeName": "Model",
         "parentOf": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/model/70/outgoing/hierarchy"
         },
         "versionNumber": 0.1
      }
   ],
   "offset": 5,
   "success": true,
   "size": 5
}

    })(window)