/** Generated automatically from model. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['model'] = fixtures['model'] || {};
        var model = fixtures['model']

        window.fixtures.model.outgoing1 = {
   "total": 11,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/model/33/outgoing/relationship?max=10&offset=10",
   "list": [
      {
         "id": 4407,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/47/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/47",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/47/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/47/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/47/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/47/incoming"
            },
            "version": 1,
            "id": 47,
            "description": "this is a model test9",
            "name": "mTest9",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/47/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4408,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/48/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/48",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/48/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/48/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/48/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/48/incoming"
            },
            "version": 1,
            "id": 48,
            "description": "this is a model test8",
            "name": "mTest8",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/48/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4409,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/50/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/50",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/50/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/50/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/50/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/50/incoming"
            },
            "version": 1,
            "id": 50,
            "description": "this is a model test7",
            "name": "mTest7",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/50/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4410,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/51/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/51",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/51/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/51/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/51/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/51/incoming"
            },
            "version": 1,
            "id": 51,
            "description": "this is a model test6",
            "name": "mTest6",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/51/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4411,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/53/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/53",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/53/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/53/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/53/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/53/incoming"
            },
            "version": 1,
            "id": 53,
            "description": "this is a model test5",
            "name": "mTest5",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/53/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4412,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/54/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/54",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/54/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/54/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/54/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/54/incoming"
            },
            "version": 1,
            "id": 54,
            "description": "this is a model test4",
            "name": "mTest4",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/54/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4413,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/67/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/67",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/67/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/67/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/67/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/67/incoming"
            },
            "version": 1,
            "id": 67,
            "description": "this is a model test2",
            "name": "mTest2",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/67/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4414,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/69/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/69",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/69/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/69/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/69/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/69/incoming"
            },
            "version": 1,
            "id": 69,
            "description": "this is a model test3",
            "name": "mTest3",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/69/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4415,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/70/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/70",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/70/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/70/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/70/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/70/incoming"
            },
            "version": 1,
            "id": 70,
            "description": "The Jabberwocky chapter for a book",
            "name": "chapter1",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/70/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 4416,
         "direction": "sourceToDestination",
         "removeLink": "/model/33/outgoing/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/71/outgoing"
            },
            "status": "DRAFT",
            "link": "/model/71",
            "hasContextOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/71/incoming/context"
            },
            "childOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/71/incoming/hierarchy"
            },
            "contains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/71/outgoing/containment"
            },
            "ext": {},
            "elementType": "org.modelcatalogue.core.Model",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/71/incoming"
            },
            "version": 1,
            "id": 71,
            "description": "this is a model test1",
            "name": "mTest1",
            "elementTypeName": "Model",
            "parentOf": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/model/71/outgoing/hierarchy"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)