/** Generated automatically from model. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['model'] = fixtures['model'] || {};
        var model = fixtures['model']

        window.fixtures.model.outgoingWithNonExistingType4 = {
   "total": 0,
   "previous": "",
   "page": 4,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "",
   "list": [],
   "offset": 8,
   "success": true,
   "size": 0
}

    })(window)