/** Generated automatically from model. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['model'] = fixtures['model'] || {};
        var model = fixtures['model']

        window.fixtures.model.removeNonExistingOutgoingJSON = {"id":70,"name":"chapter1","description":"The Jabberwocky chapter for a book","version":0,"elementType":"org.modelcatalogue.core.Model","elementTypeName":"Model","link":"/model/70","outgoingRelationships":{"count":0,"itemType":"org.modelcatalogue.core.Relationship","link":"/model/70/outgoing"},"incomingRelationships":{"count":0,"itemType":"org.modelcatalogue.core.Relationship","link":"/model/70/incoming"},"hasContextOf":{"count":0,"itemType":"org.modelcatalogue.core.Relationship","link":"/model/70/incoming/context"},"childOf":{"count":0,"itemType":"org.modelcatalogue.core.Relationship","link":"/model/70/incoming/hierarchy"},"contains":{"count":0,"itemType":"org.modelcatalogue.core.Relationship","link":"/model/70/outgoing/containment"},"parentOf":{"count":0,"itemType":"org.modelcatalogue.core.Relationship","link":"/model/70/outgoing/hierarchy"},"versionNumber":0.1,"status":"DRAFT","ext":{}}

    })(window)