/** Generated automatically from model. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['model'] = fixtures['model'] || {};
        var model = fixtures['model']

        window.fixtures.model.saveOk = {
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/615/outgoing"
   },
   "status": "DRAFT",
   "link": "/model/615",
   "hasContextOf": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/615/incoming/context"
   },
   "childOf": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/615/incoming/hierarchy"
   },
   "contains": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/615/outgoing/containment"
   },
   "ext": {},
   "elementType": "org.modelcatalogue.core.Model",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/615/incoming"
   },
   "version": 0,
   "id": 615,
   "description": "the model of the book",
   "name": "new model",
   "elementTypeName": "Model",
   "parentOf": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/615/outgoing/hierarchy"
   },
   "versionNumber": 0.1
}

    })(window)