/** Generated automatically from model. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['model'] = fixtures['model'] || {};
        var model = fixtures['model']

        window.fixtures.model.showOne = {
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/33/outgoing"
   },
   "status": "DRAFT",
   "link": "/model/33",
   "hasContextOf": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/33/incoming/context"
   },
   "childOf": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/33/incoming/hierarchy"
   },
   "contains": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/33/outgoing/containment"
   },
   "ext": {},
   "elementType": "org.modelcatalogue.core.Model",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/33/incoming"
   },
   "version": 0,
   "id": 33,
   "description": "this is a model of a book",
   "name": "book",
   "elementTypeName": "Model",
   "parentOf": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/model/33/outgoing/hierarchy"
   },
   "versionNumber": 0.1
}

    })(window)