/** Generated automatically from conceptualDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['conceptualDomain'] = fixtures['conceptualDomain'] || {};
        var conceptualDomain = fixtures['conceptualDomain']

        window.fixtures.conceptualDomain.addIncoming = {
   "id": 1,
   "source": {
      "id": 55,
      "name": "public libraries",
      "link": "/conceptualDomain/55"
   },
   "type": {
      "id": 3,
      "name": "relationship",
      "link": "/relationshipType/3"
   },
   "destination": {
      "id": 31,
      "name": "school libraries",
      "link": "/conceptualDomain/31"
   }
}

    })(window)