/** Generated automatically from conceptualDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['conceptualDomain'] = fixtures['conceptualDomain'] || {};
        var conceptualDomain = fixtures['conceptualDomain']

        window.fixtures.conceptualDomain.incoming1 = {
   "total": 11,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/conceptualDomain/55/incoming/relationship?max=10&offset=10",
   "list": [
      {
         "id": 207,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 4,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/4/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest9",
            "link": "/conceptualDomain/4",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/4/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/4/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/4/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 208,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 5,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/5/outgoing"
            },
            "description": "this is a container for the domain for ads libraries",
            "name": "cdtest8",
            "link": "/conceptualDomain/5",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/5/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/5/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/5/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 209,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 9,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/9/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest3",
            "link": "/conceptualDomain/9",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/9/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/9/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/9/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 210,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 12,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/12/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest2",
            "link": "/conceptualDomain/12",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/12/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/12/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/12/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 211,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 15,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/15/outgoing"
            },
            "description": "this is a container for the domain for dgas libraries",
            "name": "cdtest1",
            "link": "/conceptualDomain/15",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/15/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/15/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/15/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 212,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 20,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/20/outgoing"
            },
            "description": "this is a container for the domain for ads libraries",
            "name": "cdtest7",
            "link": "/conceptualDomain/20",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/20/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/20/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/20/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 213,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 23,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/23/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest6",
            "link": "/conceptualDomain/23",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/23/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/23/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/23/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 214,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 26,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/26/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest5",
            "link": "/conceptualDomain/26",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/26/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/26/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/26/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 215,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 28,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/28/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest4",
            "link": "/conceptualDomain/28",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/28/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/28/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/28/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 216,
         "direction": "destinationToSource",
         "removeLink": "/conceptualDomain/55/incoming/relationship",
         "relation": {
            "id": 31,
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/31/outgoing"
            },
            "description": "this is a container for the domain for university libraries",
            "name": "school libraries",
            "link": "/conceptualDomain/31",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/31/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/31/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/31/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)