/** Generated automatically from conceptualDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['conceptualDomain'] = fixtures['conceptualDomain'] || {};
        var conceptualDomain = fixtures['conceptualDomain']

        window.fixtures.conceptualDomain.list2 = {
   "total": 12,
   "previous": "",
   "page": 5,
   "itemType": "org.modelcatalogue.core.ConceptualDomain",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/conceptualDomain/?max=5&offset=5",
   "list": [
      {
         "id": 4,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/4/outgoing"
         },
         "description": "this is a container for the domain for asd libraries",
         "name": "cdtest9",
         "link": "/conceptualDomain/4",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/4/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/4/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/4/incoming"
         },
         "version": 0
      },
      {
         "id": 5,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/5/outgoing"
         },
         "description": "this is a container for the domain for ads libraries",
         "name": "cdtest8",
         "link": "/conceptualDomain/5",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/5/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/5/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/5/incoming"
         },
         "version": 0
      },
      {
         "id": 9,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/9/outgoing"
         },
         "description": "this is a container for the domain for asd libraries",
         "name": "cdtest3",
         "link": "/conceptualDomain/9",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/9/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/9/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/9/incoming"
         },
         "version": 0
      },
      {
         "id": 12,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/12/outgoing"
         },
         "description": "this is a container for the domain for asd libraries",
         "name": "cdtest2",
         "link": "/conceptualDomain/12",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/12/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/12/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/12/incoming"
         },
         "version": 0
      },
      {
         "id": 15,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/15/outgoing"
         },
         "description": "this is a container for the domain for dgas libraries",
         "name": "cdtest1",
         "link": "/conceptualDomain/15",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/15/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/15/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/15/incoming"
         },
         "version": 0
      }
   ],
   "offset": 0,
   "success": true,
   "size": 5
}

    })(window)