/** Generated automatically from conceptualDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['conceptualDomain'] = fixtures['conceptualDomain'] || {};
        var conceptualDomain = fixtures['conceptualDomain']

        window.fixtures.conceptualDomain.list4 = {
   "total": 12,
   "previous": "/conceptualDomain/?max=4&offset=4",
   "page": 4,
   "itemType": "org.modelcatalogue.core.ConceptualDomain",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "",
   "list": [
      {
         "id": 28,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/28/outgoing"
         },
         "description": "this is a container for the domain for asd libraries",
         "name": "cdtest4",
         "link": "/conceptualDomain/28",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/28/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/28/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/28/incoming"
         },
         "version": 0
      },
      {
         "id": 31,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/31/outgoing"
         },
         "description": "this is a container for the domain for university libraries",
         "name": "school libraries",
         "link": "/conceptualDomain/31",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/31/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/31/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/31/incoming"
         },
         "version": 0
      },
      {
         "id": 52,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/52/outgoing"
         },
         "description": "this is a container for the domain for university libraries",
         "name": "university libraries",
         "link": "/conceptualDomain/52",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/52/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/52/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/52/incoming"
         },
         "version": 0
      },
      {
         "id": 55,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/55/outgoing"
         },
         "description": "this is a container for the domain for public libraries",
         "name": "public libraries",
         "link": "/conceptualDomain/55",
         "isContextFor": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/55/outgoing/context"
         },
         "elementTypeName": "Conceptual Domain",
         "includes": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/55/outgoing/inclusion"
         },
         "elementType": "org.modelcatalogue.core.ConceptualDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/conceptualDomain/55/incoming"
         },
         "version": 0
      }
   ],
   "offset": 8,
   "success": true,
   "size": 4
}

    })(window)