/** Generated automatically from conceptualDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['conceptualDomain'] = fixtures['conceptualDomain'] || {};
        var conceptualDomain = fixtures['conceptualDomain']

        window.fixtures.conceptualDomain.outgoing3 = {
   "total": 11,
   "previous": "/conceptualDomain/55/outgoing/relationship?max=5&offset=0",
   "page": 5,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/conceptualDomain/55/outgoing/relationship?max=5&offset=10",
   "list": [
      {
         "id": 168,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 20,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/20/outgoing"
            },
            "description": "this is a container for the domain for ads libraries",
            "name": "cdtest7",
            "link": "/conceptualDomain/20",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/20/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/20/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/20/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 169,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 23,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/23/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest6",
            "link": "/conceptualDomain/23",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/23/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/23/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/23/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 170,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 26,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/26/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest5",
            "link": "/conceptualDomain/26",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/26/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/26/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/26/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 171,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 28,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/28/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest4",
            "link": "/conceptualDomain/28",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/28/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/28/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/28/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 172,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 31,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/31/outgoing"
            },
            "description": "this is a container for the domain for university libraries",
            "name": "school libraries",
            "link": "/conceptualDomain/31",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/31/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/31/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/31/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 5,
   "success": true,
   "size": 5
}

    })(window)