/** Generated automatically from conceptualDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['conceptualDomain'] = fixtures['conceptualDomain'] || {};
        var conceptualDomain = fixtures['conceptualDomain']

        window.fixtures.conceptualDomain.outgoing2 = {
   "total": 11,
   "previous": "",
   "page": 5,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/conceptualDomain/55/outgoing/relationship?max=5&offset=5",
   "list": [
      {
         "id": 152,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 4,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/4/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest9",
            "link": "/conceptualDomain/4",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/4/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/4/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/4/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 153,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 5,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/5/outgoing"
            },
            "description": "this is a container for the domain for ads libraries",
            "name": "cdtest8",
            "link": "/conceptualDomain/5",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/5/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/5/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/5/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 154,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 9,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/9/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest3",
            "link": "/conceptualDomain/9",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/9/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/9/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/9/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 155,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 12,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/12/outgoing"
            },
            "description": "this is a container for the domain for asd libraries",
            "name": "cdtest2",
            "link": "/conceptualDomain/12",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/12/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/12/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/12/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 156,
         "direction": "sourceToDestination",
         "removeLink": "/conceptualDomain/55/outgoing/relationship",
         "relation": {
            "id": 15,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/15/outgoing"
            },
            "description": "this is a container for the domain for dgas libraries",
            "name": "cdtest1",
            "link": "/conceptualDomain/15",
            "isContextFor": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/15/outgoing/context"
            },
            "elementTypeName": "Conceptual Domain",
            "includes": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/15/outgoing/inclusion"
            },
            "elementType": "org.modelcatalogue.core.ConceptualDomain",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/conceptualDomain/15/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 0,
   "success": true,
   "size": 5
}

    })(window)