/** Generated automatically from conceptualDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['conceptualDomain'] = fixtures['conceptualDomain'] || {};
        var conceptualDomain = fixtures['conceptualDomain']

        window.fixtures.conceptualDomain.saveOk = {
   "id": 86,
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/conceptualDomain/86/outgoing"
   },
   "description": "the ConceptualDomain of the university2",
   "name": "new ConceptualDomain",
   "link": "/conceptualDomain/86",
   "isContextFor": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/conceptualDomain/86/outgoing/context"
   },
   "elementTypeName": "Conceptual Domain",
   "includes": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/conceptualDomain/86/outgoing/inclusion"
   },
   "elementType": "org.modelcatalogue.core.ConceptualDomain",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/conceptualDomain/86/incoming"
   },
   "version": 0
}

    })(window)