/** Generated automatically from measurementUnit. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
        var measurementUnit = fixtures['measurementUnit']

        window.fixtures.measurementUnit.addIncoming = {
   "id": 3467,
   "source": {
      "id": 49,
      "name": "Degrees of Celsius",
      "link": "/measurementUnit/49"
   },
   "type": {
      "id": 3,
      "name": "relationship",
      "link": "/relationshipType/3"
   },
   "destination": {
      "id": 6,
      "name": "Kilometers per hour",
      "link": "/measurementUnit/6"
   }
}

    })(window)