/** Generated automatically from measurementUnit. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
        var measurementUnit = fixtures['measurementUnit']

        window.fixtures.measurementUnit.list1 = {
   "total": 12,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.MeasurementUnit",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/measurementUnit/?max=10&offset=10",
   "list": [
      {
         "id": 6,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/6/outgoing"
         },
         "symbol": "KPH",
         "description": null,
         "name": "Kilometers per hour",
         "link": "/measurementUnit/6",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/6/incoming"
         },
         "version": 0
      },
      {
         "id": 32,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/32/outgoing"
         },
         "symbol": "MPH",
         "description": null,
         "name": "Miles per hour",
         "link": "/measurementUnit/32",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/32/incoming"
         },
         "version": 0
      },
      {
         "id": 49,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/49/outgoing"
         },
         "symbol": "°C",
         "description": "Celsius, also known as centigrade,[1] is a scale and unit of measurement for temperature. It is named after the Swedish astronomer Anders Celsius (1701–1744), who developed a similar temperature scale. The degree Celsius (°C) can refer to a specific temperature on the Celsius scale as well as a unit to indicate a temperature interval, a difference between two temperatures or an uncertainty. The unit was known until 1948 as \"centigrade\" from the Latin centum translated as 100 and gradus translated as \"steps\".",
         "name": "Degrees of Celsius",
         "link": "/measurementUnit/49",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/49/incoming"
         },
         "version": 0
      },
      {
         "id": 58,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/58/outgoing"
         },
         "symbol": "°F",
         "description": "Fahrenheit (symbol °F) is a temperature scale based on one proposed in 1724 by the physicist Daniel Gabriel Fahrenheit (1686–1736), after whom the scale is named.[1] On Fahrenheit's original scale the lower defining point was the lowest temperature to which he could reproducibly cool brine (defining 0 degrees), while the highest was that of the average human core body temperature (defining 100 degrees). There exist several stories on the exact original definition of his scale; however, some of the specifics have been presumed lost or exaggerated with time. The scale is now usually defined by two fixed points: the temperature at which water freezes into ice is defined as 32 degrees, and the boiling point of water is defined to be 212 degrees, a 180 degree separation, as defined at sea level and standard atmospheric pressure.",
         "name": "Degrees of Fahrenheit",
         "link": "/measurementUnit/58",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/58/incoming"
         },
         "version": 0
      },
      {
         "id": 59,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/59/outgoing"
         },
         "symbol": "°2",
         "description": "test2 mu",
         "name": "test mu2",
         "link": "/measurementUnit/59",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/59/incoming"
         },
         "version": 0
      },
      {
         "id": 60,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/60/outgoing"
         },
         "symbol": "°1",
         "description": "test1 mu",
         "name": "test mu1",
         "link": "/measurementUnit/60",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/60/incoming"
         },
         "version": 0
      },
      {
         "id": 61,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/61/outgoing"
         },
         "symbol": "°4",
         "description": "test4 mu",
         "name": "test mu4",
         "link": "/measurementUnit/61",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/61/incoming"
         },
         "version": 0
      },
      {
         "id": 62,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/62/outgoing"
         },
         "symbol": "°3",
         "description": "test3 mu",
         "name": "test mu3",
         "link": "/measurementUnit/62",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/62/incoming"
         },
         "version": 0
      },
      {
         "id": 63,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/63/outgoing"
         },
         "symbol": "°6",
         "description": "test6 mu",
         "name": "test mu6",
         "link": "/measurementUnit/63",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/63/incoming"
         },
         "version": 0
      },
      {
         "id": 64,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/64/outgoing"
         },
         "symbol": "°5",
         "description": "test5 mu",
         "name": "test mu5",
         "link": "/measurementUnit/64",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/64/incoming"
         },
         "version": 0
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)