/** Generated automatically from measurementUnit. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
        var measurementUnit = fixtures['measurementUnit']

        window.fixtures.measurementUnit.list3 = {
   "total": 12,
   "previous": "/measurementUnit/?max=5&offset=0",
   "page": 5,
   "itemType": "org.modelcatalogue.core.MeasurementUnit",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/measurementUnit/?max=5&offset=10",
   "list": [
      {
         "id": 60,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/60/outgoing"
         },
         "symbol": "°1",
         "description": "test1 mu",
         "name": "test mu1",
         "link": "/measurementUnit/60",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/60/incoming"
         },
         "version": 0
      },
      {
         "id": 61,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/61/outgoing"
         },
         "symbol": "°4",
         "description": "test4 mu",
         "name": "test mu4",
         "link": "/measurementUnit/61",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/61/incoming"
         },
         "version": 0
      },
      {
         "id": 62,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/62/outgoing"
         },
         "symbol": "°3",
         "description": "test3 mu",
         "name": "test mu3",
         "link": "/measurementUnit/62",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/62/incoming"
         },
         "version": 0
      },
      {
         "id": 63,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/63/outgoing"
         },
         "symbol": "°6",
         "description": "test6 mu",
         "name": "test mu6",
         "link": "/measurementUnit/63",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/63/incoming"
         },
         "version": 0
      },
      {
         "id": 64,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/64/outgoing"
         },
         "symbol": "°5",
         "description": "test5 mu",
         "name": "test mu5",
         "link": "/measurementUnit/64",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/64/incoming"
         },
         "version": 0
      }
   ],
   "offset": 5,
   "success": true,
   "size": 5
}

    })(window)