/** Generated automatically from measurementUnit. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
        var measurementUnit = fixtures['measurementUnit']

        window.fixtures.measurementUnit.list5 = {
   "total": 12,
   "previous": "/measurementUnit/?max=10&offset=0",
   "page": 10,
   "itemType": "org.modelcatalogue.core.MeasurementUnit",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "",
   "list": [
      {
         "id": 65,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/65/outgoing"
         },
         "symbol": "°8",
         "description": "test8 mu",
         "name": "test mu8",
         "link": "/measurementUnit/65",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/65/incoming"
         },
         "version": 0
      },
      {
         "id": 66,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/66/outgoing"
         },
         "symbol": "°7",
         "description": "test7 mu",
         "name": "test mu7",
         "link": "/measurementUnit/66",
         "elementTypeName": "Measurement Unit",
         "elementType": "org.modelcatalogue.core.MeasurementUnit",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/measurementUnit/66/incoming"
         },
         "version": 0
      }
   ],
   "offset": 10,
   "success": true,
   "size": 2
}

    })(window)