/** Generated automatically from measurementUnit. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
        var measurementUnit = fixtures['measurementUnit']

        window.fixtures.measurementUnit.outgoing3 = {
   "total": 11,
   "previous": "/measurementUnit/49/outgoing/relationship?max=5&offset=0",
   "page": 5,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/measurementUnit/49/outgoing/relationship?max=5&offset=10",
   "list": [
      {
         "id": 3634,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 61,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/61/outgoing"
            },
            "symbol": "°4",
            "description": "test4 mu",
            "name": "test mu4",
            "link": "/measurementUnit/61",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/61/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3635,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 62,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/62/outgoing"
            },
            "symbol": "°3",
            "description": "test3 mu",
            "name": "test mu3",
            "link": "/measurementUnit/62",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/62/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3636,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 63,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/63/outgoing"
            },
            "symbol": "°6",
            "description": "test6 mu",
            "name": "test mu6",
            "link": "/measurementUnit/63",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/63/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3637,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 64,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/64/outgoing"
            },
            "symbol": "°5",
            "description": "test5 mu",
            "name": "test mu5",
            "link": "/measurementUnit/64",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/64/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3638,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 65,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/65/outgoing"
            },
            "symbol": "°8",
            "description": "test8 mu",
            "name": "test mu8",
            "link": "/measurementUnit/65",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/65/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 5,
   "success": true,
   "size": 5
}

    })(window)