/** Generated automatically from measurementUnit. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
        var measurementUnit = fixtures['measurementUnit']

        window.fixtures.measurementUnit.outgoing1 = {
   "total": 11,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/measurementUnit/49/outgoing/relationship?max=10&offset=10",
   "list": [
      {
         "id": 3607,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 6,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/6/outgoing"
            },
            "symbol": "KPH",
            "description": null,
            "name": "Kilometers per hour",
            "link": "/measurementUnit/6",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/6/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3608,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 32,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/32/outgoing"
            },
            "symbol": "MPH",
            "description": null,
            "name": "Miles per hour",
            "link": "/measurementUnit/32",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/32/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3609,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 58,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/58/outgoing"
            },
            "symbol": "°F",
            "description": "Fahrenheit (symbol °F) is a temperature scale based on one proposed in 1724 by the physicist Daniel Gabriel Fahrenheit (1686–1736), after whom the scale is named.[1] On Fahrenheit's original scale the lower defining point was the lowest temperature to which he could reproducibly cool brine (defining 0 degrees), while the highest was that of the average human core body temperature (defining 100 degrees). There exist several stories on the exact original definition of his scale; however, some of the specifics have been presumed lost or exaggerated with time. The scale is now usually defined by two fixed points: the temperature at which water freezes into ice is defined as 32 degrees, and the boiling point of water is defined to be 212 degrees, a 180 degree separation, as defined at sea level and standard atmospheric pressure.",
            "name": "Degrees of Fahrenheit",
            "link": "/measurementUnit/58",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/58/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3610,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 59,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/59/outgoing"
            },
            "symbol": "°2",
            "description": "test2 mu",
            "name": "test mu2",
            "link": "/measurementUnit/59",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/59/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3611,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 60,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/60/outgoing"
            },
            "symbol": "°1",
            "description": "test1 mu",
            "name": "test mu1",
            "link": "/measurementUnit/60",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/60/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3612,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 61,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/61/outgoing"
            },
            "symbol": "°4",
            "description": "test4 mu",
            "name": "test mu4",
            "link": "/measurementUnit/61",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/61/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3613,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 62,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/62/outgoing"
            },
            "symbol": "°3",
            "description": "test3 mu",
            "name": "test mu3",
            "link": "/measurementUnit/62",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/62/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3614,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 63,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/63/outgoing"
            },
            "symbol": "°6",
            "description": "test6 mu",
            "name": "test mu6",
            "link": "/measurementUnit/63",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/63/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3615,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 64,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/64/outgoing"
            },
            "symbol": "°5",
            "description": "test5 mu",
            "name": "test mu5",
            "link": "/measurementUnit/64",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/64/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 3616,
         "direction": "sourceToDestination",
         "removeLink": "/measurementUnit/49/outgoing/relationship",
         "relation": {
            "id": 65,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/65/outgoing"
            },
            "symbol": "°8",
            "description": "test8 mu",
            "name": "test mu8",
            "link": "/measurementUnit/65",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/65/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)