/** Generated automatically from measurementUnit. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
        var measurementUnit = fixtures['measurementUnit']

        window.fixtures.measurementUnit.saveOk = {
   "id": 611,
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/measurementUnit/611/outgoing"
   },
   "symbol": "FS",
   "description": "blah blah blah",
   "name": "Something",
   "link": "/measurementUnit/611",
   "elementTypeName": "Measurement Unit",
   "elementType": "org.modelcatalogue.core.MeasurementUnit",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/measurementUnit/611/incoming"
   },
   "version": 0
}

    })(window)