/** Generated automatically from measurementUnit. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
        var measurementUnit = fixtures['measurementUnit']

        window.fixtures.measurementUnit.searchElement11 = {
   "total": 1,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.MeasurementUnit",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "",
   "list": [{
      "id": 49,
      "outgoingRelationships": {
         "count": 0,
         "itemType": "org.modelcatalogue.core.Relationship",
         "link": "/measurementUnit/49/outgoing"
      },
      "symbol": "°C",
      "description": "Celsius, also known as centigrade,[1] is a scale and unit of measurement for temperature. It is named after the Swedish astronomer Anders Celsius (1701–1744), who developed a similar temperature scale. The degree Celsius (°C) can refer to a specific temperature on the Celsius scale as well as a unit to indicate a temperature interval, a difference between two temperatures or an uncertainty. The unit was known until 1948 as \"centigrade\" from the Latin centum translated as 100 and gradus translated as \"steps\".",
      "name": "Degrees of Celsius",
      "link": "/measurementUnit/49",
      "elementTypeName": "Measurement Unit",
      "elementType": "org.modelcatalogue.core.MeasurementUnit",
      "incomingRelationships": {
         "count": 0,
         "itemType": "org.modelcatalogue.core.Relationship",
         "link": "/measurementUnit/49/incoming"
      },
      "version": 0
   }],
   "offset": 0,
   "success": true,
   "size": 1
}

    })(window)