;              
CREATE USER IF NOT EXISTS SA SALT '2a5ab4392720bf4e' HASH '4542f7143fbd46546c348c1feca1ef861930d46b43e17aff5bc72999423d5989' ADMIN;            
DROP TABLE IF EXISTS PUBLIC."change" CASCADE;  
DROP TABLE IF EXISTS PUBLIC.ACL_CLASS CASCADE; 
DROP TABLE IF EXISTS PUBLIC.ACL_ENTRY CASCADE; 
DROP TABLE IF EXISTS PUBLIC.ACL_OBJECT_IDENTITY CASCADE;       
DROP TABLE IF EXISTS PUBLIC.ACL_SID CASCADE;   
DROP TABLE IF EXISTS PUBLIC.ACTION CASCADE;    
DROP TABLE IF EXISTS PUBLIC.ACTION_DEPENDENCY CASCADE;         
DROP TABLE IF EXISTS PUBLIC.ACTION_PARAMETER CASCADE;          
DROP TABLE IF EXISTS PUBLIC.ASSET CASCADE;     
DROP TABLE IF EXISTS PUBLIC.ASSET_FILE CASCADE;
DROP TABLE IF EXISTS PUBLIC.BATCH CASCADE;     
DROP TABLE IF EXISTS PUBLIC.CATALOGUE_ELEMENT CASCADE;         
DROP TABLE IF EXISTS PUBLIC.COLUMN_TRANSFORMATION_DEFINITION CASCADE;          
DROP TABLE IF EXISTS PUBLIC.CSV_TRANSFORMATION CASCADE;        
DROP TABLE IF EXISTS PUBLIC.DATA_CLASS CASCADE;
DROP TABLE IF EXISTS PUBLIC.DATA_ELEMENT CASCADE;              
DROP TABLE IF EXISTS PUBLIC.DATA_MODEL CASCADE;
DROP TABLE IF EXISTS PUBLIC.DATA_MODEL_DATA_MODEL_POLICY CASCADE;              
DROP TABLE IF EXISTS PUBLIC.DATA_MODEL_POLICY CASCADE;         
DROP TABLE IF EXISTS PUBLIC.DATA_TYPE CASCADE; 
DROP TABLE IF EXISTS PUBLIC.ENUMERATED_TYPE CASCADE;           
DROP TABLE IF EXISTS PUBLIC.EXTENSION_VALUE CASCADE;           
DROP TABLE IF EXISTS PUBLIC.MAPPING CASCADE;   
DROP TABLE IF EXISTS PUBLIC.MEASUREMENT_UNIT CASCADE;          
DROP TABLE IF EXISTS PUBLIC.OAUTHID CASCADE;   
DROP TABLE IF EXISTS PUBLIC.PRIMITIVE_TYPE CASCADE;            
DROP TABLE IF EXISTS PUBLIC.REFERENCE_TYPE CASCADE;            
DROP TABLE IF EXISTS PUBLIC.REGISTRATION_CODE CASCADE;         
DROP TABLE IF EXISTS PUBLIC.RELATIONSHIP CASCADE;              
DROP TABLE IF EXISTS PUBLIC.RELATIONSHIP_METADATA CASCADE;     
DROP TABLE IF EXISTS PUBLIC.RELATIONSHIP_TYPE CASCADE;         
DROP TABLE IF EXISTS PUBLIC.REQUESTMAP CASCADE;
DROP TABLE IF EXISTS PUBLIC.ROLE CASCADE;      
DROP TABLE IF EXISTS PUBLIC.TAG CASCADE;       
DROP TABLE IF EXISTS PUBLIC.USER CASCADE;      
DROP TABLE IF EXISTS PUBLIC.USER_ROLE CASCADE; 
DROP TABLE IF EXISTS PUBLIC.VALIDATION_RULE CASCADE;           
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B73D2D48_B9EB_408C_90B3_6B5BBD20A79C START WITH 101 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A30922A4_033F_4C06_AC65_CDDA6C684D18 START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FF10B2D8_8075_42FC_9B50_3B03281A4B70 START WITH 593 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5C09A253_1193_42F7_8A18_0E5D39EF5E5F START WITH 53 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EE1CCD12_5ABA_44B9_841B_EB946A1AF8E4 START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_986BF911_1ED6_48FD_8111_65FBF1F31C4B START WITH 680 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_28AD9A6B_6861_4FEB_B19E_1C5E409E419E START WITH 298 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_02C1CBE2_AC91_4491_BBDD_52943DB39F47 START WITH 59 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_58A3A240_EE94_4CB6_A3AA_44C7A1DED7B3 START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FA1F68A8_BD29_4CC2_884B_0CE6B5D946F4 START WITH 835 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CEF088DF_D7E8_4876_9297_5A82B37AA2D0 START WITH 100 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AB101B45_C113_477C_864A_0A77F1AA9C42 START WITH 556 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9DB6221B_ADD8_42AD_84F2_D2AB5ECF8565 START WITH 9685 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1F290E42_6C97_4A53_B1A2_266886AC63E0 START WITH 49 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_62E61E11_5898_4FBA_92E2_90CF81DDDF5A START WITH 2219 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AFD576D2_5FA8_4B88_949D_0E8E8EB21120 START WITH 6 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_48CEAAAF_2BEA_4F58_B74D_43F8F7F66F39 START WITH 7561 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A99F4BEF_4333_49FF_AB4B_73A6036EFBC1 START WITH 648 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_928C5C84_0376_43E0_9024_0058AD5666D3 START WITH 771 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F84A0490_6AE9_4FDB_9712_87B6144B0C60 START WITH 278 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D2222819_E18D_4DE8_A51B_6FF4F1051220 START WITH 192 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A026FE1B_84B2_4EDF_8553_641B5DABD8BA START WITH 206 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1B50A1AE_487D_4735_A2C9_322B1D071584 START WITH 14 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_546D4B5E_1C91_4B99_8DE6_E9279EB9FD70 START WITH 726 BELONGS_TO_TABLE;   
CREATE MEMORY TABLE PUBLIC."change"(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9DB6221B_ADD8_42AD_84F2_D2AB5ECF8565) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9DB6221B_ADD8_42AD_84F2_D2AB5ECF8565,
    AUTHOR_ID BIGINT,
    CHANGED_ID BIGINT NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    LATEST_VERSION_ID BIGINT NOT NULL,
    NEW_VALUE LONGVARCHAR,
    OLD_VALUE LONGVARCHAR,
    OTHER_SIDE BOOLEAN NOT NULL,
    PARENT_ID BIGINT,
    PROPERTY VARCHAR(255),
    SYSTEM BOOLEAN,
    TYPE VARCHAR(255) NOT NULL,
    UNDONE BOOLEAN
);     
ALTER TABLE PUBLIC."change" ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);
-- 61 +/- SELECT COUNT(*) FROM PUBLIC."change";
CREATE INDEX PUBLIC.CHANGE_IDX_4 ON PUBLIC."change"(LATEST_VERSION_ID);        
CREATE MEMORY TABLE PUBLIC.ACL_CLASS(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CEF088DF_D7E8_4876_9297_5A82B37AA2D0) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CEF088DF_D7E8_4876_9297_5A82B37AA2D0,
    CLASS VARCHAR(255) NOT NULL
);     
ALTER TABLE PUBLIC.ACL_CLASS ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);               
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ACL_CLASS;
CREATE MEMORY TABLE PUBLIC.ACL_ENTRY(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FA1F68A8_BD29_4CC2_884B_0CE6B5D946F4) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FA1F68A8_BD29_4CC2_884B_0CE6B5D946F4,
    ACE_ORDER INTEGER NOT NULL,
    ACL_OBJECT_IDENTITY BIGINT NOT NULL,
    AUDIT_FAILURE BOOLEAN NOT NULL,
    AUDIT_SUCCESS BOOLEAN NOT NULL,
    GRANTING BOOLEAN NOT NULL,
    MASK INTEGER NOT NULL,
    SID BIGINT NOT NULL
);  
ALTER TABLE PUBLIC.ACL_ENTRY ADD CONSTRAINT PUBLIC.CONSTRAINT_2F PRIMARY KEY(ID);              
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ACL_ENTRY;
CREATE MEMORY TABLE PUBLIC.ACL_OBJECT_IDENTITY(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_928C5C84_0376_43E0_9024_0058AD5666D3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_928C5C84_0376_43E0_9024_0058AD5666D3,
    OBJECT_ID_CLASS BIGINT NOT NULL,
    ENTRIES_INHERITING BOOLEAN NOT NULL,
    OBJECT_ID_IDENTITY BIGINT NOT NULL,
    OWNER_SID BIGINT,
    PARENT_OBJECT BIGINT
);      
ALTER TABLE PUBLIC.ACL_OBJECT_IDENTITY ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);     
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ACL_OBJECT_IDENTITY;      
CREATE MEMORY TABLE PUBLIC.ACL_SID(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B73D2D48_B9EB_408C_90B3_6B5BBD20A79C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B73D2D48_B9EB_408C_90B3_6B5BBD20A79C,
    PRINCIPAL BOOLEAN NOT NULL,
    SID VARCHAR(255) NOT NULL
);         
ALTER TABLE PUBLIC.ACL_SID ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ID); 
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ACL_SID;  
CREATE MEMORY TABLE PUBLIC.ACTION(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_28AD9A6B_6861_4FEB_B19E_1C5E409E419E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_28AD9A6B_6861_4FEB_B19E_1C5E409E419E,
    BATCH_ID BIGINT NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL,
    OUTCOME VARCHAR(10000),
    RESULT VARCHAR(1000),
    STATE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL
);          
ALTER TABLE PUBLIC.ACTION ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACTION;   
CREATE MEMORY TABLE PUBLIC.ACTION_DEPENDENCY(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AFD576D2_5FA8_4B88_949D_0E8E8EB21120) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AFD576D2_5FA8_4B88_949D_0E8E8EB21120,
    VERSION BIGINT NOT NULL,
    DEPENDANT_ID BIGINT NOT NULL,
    PROVIDER_ID BIGINT NOT NULL,
    ROLE VARCHAR(100) NOT NULL
);              
ALTER TABLE PUBLIC.ACTION_DEPENDENCY ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACTION_DEPENDENCY;        
CREATE MEMORY TABLE PUBLIC.ACTION_PARAMETER(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FF10B2D8_8075_42FC_9B50_3B03281A4B70) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FF10B2D8_8075_42FC_9B50_3B03281A4B70,
    VERSION BIGINT NOT NULL,
    ACTION_ID BIGINT NOT NULL,
    EXTENSION_VALUE VARCHAR(1000),
    NAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.ACTION_PARAMETER ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACTION_PARAMETER;         
CREATE MEMORY TABLE PUBLIC.ASSET(
    ID BIGINT NOT NULL,
    CONTENT_TYPE VARCHAR(255),
    MD5 VARCHAR(32),
    ORIGINAL_FILE_NAME VARCHAR(255),
    SIZE BIGINT
);          
ALTER TABLE PUBLIC.ASSET ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSET;    
CREATE MEMORY TABLE PUBLIC.ASSET_FILE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A30922A4_033F_4C06_AC65_CDDA6C684D18) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A30922A4_033F_4C06_AC65_CDDA6C684D18,
    VERSION BIGINT NOT NULL,
    CONTENT BLOB NOT NULL,
    PATH VARCHAR(255) NOT NULL
);             
ALTER TABLE PUBLIC.ASSET_FILE ADD CONSTRAINT PUBLIC.CONSTRAINT_9D PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSET_FILE;               
CREATE MEMORY TABLE PUBLIC.BATCH(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F84A0490_6AE9_4FDB_9712_87B6144B0C60) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F84A0490_6AE9_4FDB_9712_87B6144B0C60,
    VERSION BIGINT NOT NULL,
    ARCHIVED BOOLEAN NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(2000),
    LAST_UPDATED TIMESTAMP NOT NULL,
    NAME VARCHAR(255) NOT NULL
);     
ALTER TABLE PUBLIC.BATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_3C PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BATCH;    
CREATE MEMORY TABLE PUBLIC.CATALOGUE_ELEMENT(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_48CEAAAF_2BEA_4F58_B74D_43F8F7F66F39) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_48CEAAAF_2BEA_4F58_B74D_43F8F7F66F39,
    VERSION BIGINT NOT NULL,
    DATA_MODEL_ID BIGINT,
    DATE_CREATED TIMESTAMP NOT NULL,
    DESCRIPTION LONGVARCHAR,
    LAST_UPDATED TIMESTAMP NOT NULL,
    LATEST_VERSION_ID BIGINT,
    MODEL_CATALOGUE_ID VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    VERSION_CREATED TIMESTAMP NOT NULL,
    VERSION_NUMBER INTEGER NOT NULL
);              
ALTER TABLE PUBLIC.CATALOGUE_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);       
-- 16 +/- SELECT COUNT(*) FROM PUBLIC.CATALOGUE_ELEMENT;       
CREATE INDEX PUBLIC.CTLGELEMENT_LATESTVERSIONID_IDX ON PUBLIC.CATALOGUE_ELEMENT(LATEST_VERSION_ID);            
CREATE INDEX PUBLIC.CTLGELEMENT_MODELCATALOGUEID_IDX ON PUBLIC.CATALOGUE_ELEMENT(MODEL_CATALOGUE_ID);          
CREATE INDEX PUBLIC.CTLGELEMENT_NAME_IDX ON PUBLIC.CATALOGUE_ELEMENT(NAME);    
CREATE MEMORY TABLE PUBLIC.COLUMN_TRANSFORMATION_DEFINITION(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D2222819_E18D_4DE8_A51B_6FF4F1051220) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D2222819_E18D_4DE8_A51B_6FF4F1051220,
    VERSION BIGINT NOT NULL,
    DESTINATION_ID BIGINT,
    HEADER VARCHAR(255),
    SOURCE_ID BIGINT NOT NULL,
    TRANSFORMATION_ID BIGINT NOT NULL,
    COLUMN_DEFINITIONS_IDX INTEGER
);    
ALTER TABLE PUBLIC.COLUMN_TRANSFORMATION_DEFINITION ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COLUMN_TRANSFORMATION_DEFINITION;         
CREATE MEMORY TABLE PUBLIC.CSV_TRANSFORMATION(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1F290E42_6C97_4A53_B1A2_266886AC63E0) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1F290E42_6C97_4A53_B1A2_266886AC63E0,
    VERSION BIGINT NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(255),
    LAST_UPDATED TIMESTAMP NOT NULL,
    NAME VARCHAR(255) NOT NULL
);        
ALTER TABLE PUBLIC.CSV_TRANSFORMATION ADD CONSTRAINT PUBLIC.CONSTRAINT_D3 PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CSV_TRANSFORMATION;       
CREATE MEMORY TABLE PUBLIC.DATA_CLASS(
    ID BIGINT NOT NULL
);               
ALTER TABLE PUBLIC.DATA_CLASS ADD CONSTRAINT PUBLIC.CONSTRAINT_B3 PRIMARY KEY(ID);             
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.DATA_CLASS;               
CREATE MEMORY TABLE PUBLIC.DATA_ELEMENT(
    ID BIGINT NOT NULL,
    DATA_TYPE_ID BIGINT
);    
ALTER TABLE PUBLIC.DATA_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);            
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.DATA_ELEMENT;             
CREATE MEMORY TABLE PUBLIC.DATA_MODEL(
    ID BIGINT NOT NULL,
    REVISION_NOTES VARCHAR(2000),
    SEMANTIC_VERSION VARCHAR(20)
);           
ALTER TABLE PUBLIC.DATA_MODEL ADD CONSTRAINT PUBLIC.CONSTRAINT_B3B PRIMARY KEY(ID);            
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.DATA_MODEL;               
CREATE MEMORY TABLE PUBLIC.DATA_MODEL_DATA_MODEL_POLICY(
    DATA_MODEL_POLICIES_ID BIGINT,
    DATA_MODEL_POLICY_ID BIGINT
); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DATA_MODEL_DATA_MODEL_POLICY;             
CREATE MEMORY TABLE PUBLIC.DATA_MODEL_POLICY(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AB101B45_C113_477C_864A_0A77F1AA9C42) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AB101B45_C113_477C_864A_0A77F1AA9C42,
    VERSION BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    POLICY_TEXT VARCHAR(10000) NOT NULL
);        
ALTER TABLE PUBLIC.DATA_MODEL_POLICY ADD CONSTRAINT PUBLIC.CONSTRAINT_2D PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DATA_MODEL_POLICY;        
CREATE MEMORY TABLE PUBLIC.DATA_TYPE(
    ID BIGINT NOT NULL,
    RULE VARCHAR(10000)
);       
ALTER TABLE PUBLIC.DATA_TYPE ADD CONSTRAINT PUBLIC.CONSTRAINT_92 PRIMARY KEY(ID);              
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.DATA_TYPE;
CREATE MEMORY TABLE PUBLIC.ENUMERATED_TYPE(
    ID BIGINT NOT NULL,
    ENUM_AS_STRING LONGVARCHAR
);          
ALTER TABLE PUBLIC.ENUMERATED_TYPE ADD CONSTRAINT PUBLIC.CONSTRAINT_63 PRIMARY KEY(ID);        
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ENUMERATED_TYPE;          
CREATE MEMORY TABLE PUBLIC.EXTENSION_VALUE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_986BF911_1ED6_48FD_8111_65FBF1F31C4B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_986BF911_1ED6_48FD_8111_65FBF1F31C4B,
    VERSION BIGINT NOT NULL,
    ELEMENT_ID BIGINT NOT NULL,
    EXTENSION_VALUE VARCHAR(10000),
    NAME VARCHAR(255) NOT NULL,
    ORDER_INDEX BIGINT NOT NULL
);              
ALTER TABLE PUBLIC.EXTENSION_VALUE ADD CONSTRAINT PUBLIC.CONSTRAINT_DE PRIMARY KEY(ID);        
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.EXTENSION_VALUE;          
CREATE MEMORY TABLE PUBLIC.MAPPING(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A026FE1B_84B2_4EDF_8553_641B5DABD8BA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A026FE1B_84B2_4EDF_8553_641B5DABD8BA,
    VERSION BIGINT NOT NULL,
    DESTINATION_ID BIGINT NOT NULL,
    MAPPING VARCHAR(10000) NOT NULL,
    SOURCE_ID BIGINT NOT NULL
);   
ALTER TABLE PUBLIC.MAPPING ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MAPPING;  
CREATE MEMORY TABLE PUBLIC.MEASUREMENT_UNIT(
    ID BIGINT NOT NULL,
    SYMBOL VARCHAR(100)
);
ALTER TABLE PUBLIC.MEASUREMENT_UNIT ADD CONSTRAINT PUBLIC.CONSTRAINT_20 PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEASUREMENT_UNIT;         
CREATE MEMORY TABLE PUBLIC.OAUTHID(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_58A3A240_EE94_4CB6_A3AA_44C7A1DED7B3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_58A3A240_EE94_4CB6_A3AA_44C7A1DED7B3,
    VERSION BIGINT NOT NULL,
    ACCESS_TOKEN VARCHAR(255) NOT NULL,
    PROVIDER VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL
);  
ALTER TABLE PUBLIC.OAUTHID ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OAUTHID;  
CREATE INDEX PUBLIC.IDENTITY_IDX ON PUBLIC.OAUTHID(ACCESS_TOKEN, PROVIDER);    
CREATE MEMORY TABLE PUBLIC.PRIMITIVE_TYPE(
    ID BIGINT NOT NULL,
    MEASUREMENT_UNIT_ID BIGINT
);           
ALTER TABLE PUBLIC.PRIMITIVE_TYPE ADD CONSTRAINT PUBLIC.CONSTRAINT_24 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRIMITIVE_TYPE;           
CREATE MEMORY TABLE PUBLIC.REFERENCE_TYPE(
    ID BIGINT NOT NULL,
    DATA_CLASS_ID BIGINT
); 
ALTER TABLE PUBLIC.REFERENCE_TYPE ADD CONSTRAINT PUBLIC.CONSTRAINT_E8 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REFERENCE_TYPE;           
CREATE MEMORY TABLE PUBLIC.REGISTRATION_CODE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EE1CCD12_5ABA_44B9_841B_EB946A1AF8E4) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EE1CCD12_5ABA_44B9_841B_EB946A1AF8E4,
    DATE_CREATED TIMESTAMP NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL
);    
ALTER TABLE PUBLIC.REGISTRATION_CODE ADD CONSTRAINT PUBLIC.CONSTRAINT_AC PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REGISTRATION_CODE;        
CREATE MEMORY TABLE PUBLIC.RELATIONSHIP(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A99F4BEF_4333_49FF_AB4B_73A6036EFBC1) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A99F4BEF_4333_49FF_AB4B_73A6036EFBC1,
    VERSION BIGINT NOT NULL,
    ARCHIVED BOOLEAN NOT NULL,
    DATA_MODEL_ID BIGINT,
    DESTINATION_ID BIGINT NOT NULL,
    INCOMING_INDEX BIGINT NOT NULL,
    INHERITED BOOLEAN NOT NULL,
    OUTGOING_INDEX BIGINT NOT NULL,
    RELATIONSHIP_TYPE_ID BIGINT NOT NULL,
    SOURCE_ID BIGINT NOT NULL
);        
ALTER TABLE PUBLIC.RELATIONSHIP ADD CONSTRAINT PUBLIC.CONSTRAINT_7A PRIMARY KEY(ID);           
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.RELATIONSHIP;             
CREATE MEMORY TABLE PUBLIC.RELATIONSHIP_METADATA(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1B50A1AE_487D_4735_A2C9_322B1D071584) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1B50A1AE_487D_4735_A2C9_322B1D071584,
    VERSION BIGINT NOT NULL,
    EXTENSION_VALUE VARCHAR(10000),
    NAME VARCHAR(255) NOT NULL,
    ORDER_INDEX BIGINT NOT NULL,
    RELATIONSHIP_ID BIGINT NOT NULL
);   
ALTER TABLE PUBLIC.RELATIONSHIP_METADATA ADD CONSTRAINT PUBLIC.CONSTRAINT_29 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RELATIONSHIP_METADATA;    
CREATE MEMORY TABLE PUBLIC.RELATIONSHIP_TYPE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_62E61E11_5898_4FBA_92E2_90CF81DDDF5A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_62E61E11_5898_4FBA_92E2_90CF81DDDF5A,
    VERSION BIGINT NOT NULL,
    BIDIRECTIONAL BOOLEAN NOT NULL,
    DESTINATION_CLASS VARCHAR(255) NOT NULL,
    DESTINATION_TO_SOURCE VARCHAR(255) NOT NULL,
    DESTINATION_TO_SOURCE_DESCRIPTION VARCHAR(2000),
    METADATA_HINTS LONGVARCHAR,
    NAME VARCHAR(255) NOT NULL,
    RULE LONGVARCHAR,
    SEARCHABLE BOOLEAN DEFAULT FALSE NOT NULL,
    SOURCE_CLASS VARCHAR(255) NOT NULL,
    SOURCE_TO_DESTINATION VARCHAR(255) NOT NULL,
    SOURCE_TO_DESTINATION_DESCRIPTION VARCHAR(2000),
    SYSTEM BOOLEAN NOT NULL,
    VERSION_SPECIFIC BOOLEAN NOT NULL
);   
ALTER TABLE PUBLIC.RELATIONSHIP_TYPE ADD CONSTRAINT PUBLIC.CONSTRAINT_6B PRIMARY KEY(ID);      
-- 15 +/- SELECT COUNT(*) FROM PUBLIC.RELATIONSHIP_TYPE;       
CREATE INDEX PUBLIC.RELATIONTYPE_DESTINATIONCLASS_IDX ON PUBLIC.RELATIONSHIP_TYPE(DESTINATION_CLASS);          
CREATE INDEX PUBLIC.RELATIONTYPE_NAME_IDX ON PUBLIC.RELATIONSHIP_TYPE(NAME);   
CREATE MEMORY TABLE PUBLIC.REQUESTMAP(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_546D4B5E_1C91_4B99_8DE6_E9279EB9FD70) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_546D4B5E_1C91_4B99_8DE6_E9279EB9FD70,
    VERSION BIGINT NOT NULL,
    CONFIG_ATTRIBUTE VARCHAR(255) NOT NULL,
    HTTP_METHOD VARCHAR(255),
    URL VARCHAR(255) NOT NULL
);               
ALTER TABLE PUBLIC.REQUESTMAP ADD CONSTRAINT PUBLIC.CONSTRAINT_1F PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REQUESTMAP;               
CREATE MEMORY TABLE PUBLIC.ROLE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_5C09A253_1193_42F7_8A18_0E5D39EF5E5F) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5C09A253_1193_42F7_8A18_0E5D39EF5E5F,
    VERSION BIGINT NOT NULL,
    AUTHORITY VARCHAR(255) NOT NULL
);         
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_26 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;     
CREATE MEMORY TABLE PUBLIC.TAG(
    ID BIGINT NOT NULL
);      
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG;      
CREATE MEMORY TABLE PUBLIC.USER(
    ID BIGINT NOT NULL,
    ACCOUNT_EXPIRED BOOLEAN,
    ACCOUNT_LOCKED BOOLEAN,
    API_KEY VARCHAR(255),
    EMAIL VARCHAR(255),
    ENABLED BOOLEAN,
    "password" VARCHAR(255),
    PASSWORD_EXPIRED BOOLEAN,
    USERNAME VARCHAR(255)
);               
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;     
CREATE MEMORY TABLE PUBLIC.USER_ROLE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_02C1CBE2_AC91_4491_BBDD_52943DB39F47) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_02C1CBE2_AC91_4491_BBDD_52943DB39F47,
    ROLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);            
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_BC PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_ROLE;
CREATE MEMORY TABLE PUBLIC.VALIDATION_RULE(
    ID BIGINT NOT NULL,
    COMPONENT VARCHAR(255),
    ERROR_CONDITION VARCHAR(255),
    ISSUE_RECORD VARCHAR(255),
    NOTIFICATION VARCHAR(255),
    NOTIFICATION_TARGET VARCHAR(255),
    RULE VARCHAR(10000),
    RULE_FOCUS VARCHAR(255),
    RULE_TRIGGER VARCHAR(255)
);   
ALTER TABLE PUBLIC.VALIDATION_RULE ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VALIDATION_RULE;          
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_OB8KQYQQGMEFL0ACO34AKDTPE UNIQUE(EMAIL);      
ALTER TABLE PUBLIC.ACL_CLASS ADD CONSTRAINT PUBLIC.UK_IY7UA5FSO3IL3U3YMOC4UF35W UNIQUE(CLASS); 
ALTER TABLE PUBLIC.REQUESTMAP ADD CONSTRAINT PUBLIC.UNIQUE_URL UNIQUE(HTTP_METHOD, URL);       
ALTER TABLE PUBLIC.ACL_ENTRY ADD CONSTRAINT PUBLIC.UNIQUE_ACE_ORDER UNIQUE(ACL_OBJECT_IDENTITY, ACE_ORDER);    
ALTER TABLE PUBLIC.ACL_OBJECT_IDENTITY ADD CONSTRAINT PUBLIC.UNIQUE_OBJECT_ID_IDENTITY UNIQUE(OBJECT_ID_CLASS, OBJECT_ID_IDENTITY);            
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_SB8BBOUER5WAK8VYIIY4PF2BX UNIQUE(USERNAME);   
ALTER TABLE PUBLIC.DATA_MODEL_POLICY ADD CONSTRAINT PUBLIC.UK_AGEAWCASIUSOJ14YW6VLO8R42 UNIQUE(NAME);          
ALTER TABLE PUBLIC.ACL_SID ADD CONSTRAINT PUBLIC.UNIQUE_PRINCIPAL UNIQUE(SID, PRINCIPAL);      
ALTER TABLE PUBLIC.OAUTHID ADD CONSTRAINT PUBLIC.UK_2HY0ON28ORON3V471PLRNU1K0 UNIQUE(ACCESS_TOKEN);            
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.UK_IRSAMGNERA6ANGM0PRQ1KEMT2 UNIQUE(AUTHORITY);  
ALTER TABLE PUBLIC.MAPPING ADD CONSTRAINT PUBLIC.UNIQUE_SOURCE_ID UNIQUE(DESTINATION_ID, SOURCE_ID);           
ALTER TABLE PUBLIC.RELATIONSHIP_TYPE ADD CONSTRAINT PUBLIC.UK_ISXYGYCHIH5K3D3W0ADSA8DMU UNIQUE(NAME);          
ALTER TABLE PUBLIC.DATA_MODEL_DATA_MODEL_POLICY ADD CONSTRAINT PUBLIC.FK_4D8RTY3536PL29P4TTXC4T634 FOREIGN KEY(DATA_MODEL_POLICIES_ID) REFERENCES PUBLIC.DATA_MODEL(ID) NOCHECK;               
ALTER TABLE PUBLIC.PRIMITIVE_TYPE ADD CONSTRAINT PUBLIC.FK_R1K58XVVHL5TFR5ERT737MCRW FOREIGN KEY(ID) REFERENCES PUBLIC.DATA_TYPE(ID) NOCHECK;  
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.FK_IT77EQ964JHFQTU54081EBTIO FOREIGN KEY(ROLE_ID) REFERENCES PUBLIC.ROLE(ID) NOCHECK;       
ALTER TABLE PUBLIC.ACL_OBJECT_IDENTITY ADD CONSTRAINT PUBLIC.FK_NXV5WE2ION9FWEDBKGE7SYOC3 FOREIGN KEY(OWNER_SID) REFERENCES PUBLIC.ACL_SID(ID) NOCHECK;        
ALTER TABLE PUBLIC.ACTION_DEPENDENCY ADD CONSTRAINT PUBLIC.FK_H5T41RH141W87KY6Y3RFDW1TA FOREIGN KEY(DEPENDANT_ID) REFERENCES PUBLIC.ACTION(ID) NOCHECK;        
ALTER TABLE PUBLIC.OAUTHID ADD CONSTRAINT PUBLIC.FK_M55D9KULBI1H29T7XS23OHD0W FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;         
ALTER TABLE PUBLIC.RELATIONSHIP ADD CONSTRAINT PUBLIC.FK_DXXUJFNNEBSKGVSR3PSW7TKQK FOREIGN KEY(DESTINATION_ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;
ALTER TABLE PUBLIC.MAPPING ADD CONSTRAINT PUBLIC.FK_FV0146PRJRJGBW0AX4AC2RYOB FOREIGN KEY(DESTINATION_ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;     
ALTER TABLE PUBLIC.ASSET ADD CONSTRAINT PUBLIC.FK_K73V5HFIBQ49PRM2R9PAXXQPC FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;   
ALTER TABLE PUBLIC.VALIDATION_RULE ADD CONSTRAINT PUBLIC.FK_1XYALG15G7I1TRPB9GRLLT2LD FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;         
ALTER TABLE PUBLIC.RELATIONSHIP ADD CONSTRAINT PUBLIC.FK_HKP4M9EJTK95R55U0GN4OMP8C FOREIGN KEY(DATA_MODEL_ID) REFERENCES PUBLIC.DATA_MODEL(ID) NOCHECK;        
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.FK_8QTPNV06ELXURYEUV1AC4XIMM FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;    
ALTER TABLE PUBLIC.DATA_ELEMENT ADD CONSTRAINT PUBLIC.FK_J2HO6CWLJA2404DWXHCQ332J3 FOREIGN KEY(DATA_TYPE_ID) REFERENCES PUBLIC.DATA_TYPE(ID) NOCHECK;          
ALTER TABLE PUBLIC.ACTION ADD CONSTRAINT PUBLIC.FK_5GT5S8LEE1XU7KE2PFFTMJ5HW FOREIGN KEY(BATCH_ID) REFERENCES PUBLIC.BATCH(ID) NOCHECK;        
ALTER TABLE PUBLIC.DATA_MODEL ADD CONSTRAINT PUBLIC.FK_RVEFKTVB22U3Y4RO3S85TP575 FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;              
ALTER TABLE PUBLIC.MEASUREMENT_UNIT ADD CONSTRAINT PUBLIC.FK_KGU5RJODUT97DGIBTGJGWHFWQ FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;        
ALTER TABLE PUBLIC.PRIMITIVE_TYPE ADD CONSTRAINT PUBLIC.FK_SV8SL9V1BB9TOUKIK1IHXFNLO FOREIGN KEY(MEASUREMENT_UNIT_ID) REFERENCES PUBLIC.MEASUREMENT_UNIT(ID) NOCHECK;          
ALTER TABLE PUBLIC.ACL_OBJECT_IDENTITY ADD CONSTRAINT PUBLIC.FK_6C3UGMK053UY27BK2SRED31LF FOREIGN KEY(OBJECT_ID_CLASS) REFERENCES PUBLIC.ACL_CLASS(ID) NOCHECK;
ALTER TABLE PUBLIC.ACL_ENTRY ADD CONSTRAINT PUBLIC.FK_I6XYFCCD4Y3WLWHGWPO4A9RM1 FOREIGN KEY(SID) REFERENCES PUBLIC.ACL_SID(ID) NOCHECK;        
ALTER TABLE PUBLIC.DATA_TYPE ADD CONSTRAINT PUBLIC.FK_8YH1HG0SLPPDJM9HKS745RVLC FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;               
ALTER TABLE PUBLIC.COLUMN_TRANSFORMATION_DEFINITION ADD CONSTRAINT PUBLIC.FK_3UCA158DL954JHRY8JACWPS2H FOREIGN KEY(DESTINATION_ID) REFERENCES PUBLIC.DATA_ELEMENT(ID) NOCHECK; 
ALTER TABLE PUBLIC.ENUMERATED_TYPE ADD CONSTRAINT PUBLIC.FK_8D8J21OTR9D2NX5JDAUJ3NEFQ FOREIGN KEY(ID) REFERENCES PUBLIC.DATA_TYPE(ID) NOCHECK; 
ALTER TABLE PUBLIC.MAPPING ADD CONSTRAINT PUBLIC.FK_9XB05XT14PHOR5RDRBWKE7D5V FOREIGN KEY(SOURCE_ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;          
ALTER TABLE PUBLIC.ACL_ENTRY ADD CONSTRAINT PUBLIC.FK_FHUOESMJEF3MRV0GPJA4SHVCR FOREIGN KEY(ACL_OBJECT_IDENTITY) REFERENCES PUBLIC.ACL_OBJECT_IDENTITY(ID) NOCHECK;            
ALTER TABLE PUBLIC.ACL_OBJECT_IDENTITY ADD CONSTRAINT PUBLIC.FK_6OAP2K8Q5BL33YQ3YFFRWEDHF FOREIGN KEY(PARENT_OBJECT) REFERENCES PUBLIC.ACL_OBJECT_IDENTITY(ID) NOCHECK;        
ALTER TABLE PUBLIC.ACTION_DEPENDENCY ADD CONSTRAINT PUBLIC.FK_RVC4BRAHQTB99WJEXIEB53NWB FOREIGN KEY(PROVIDER_ID) REFERENCES PUBLIC.ACTION(ID) NOCHECK;         
ALTER TABLE PUBLIC.REFERENCE_TYPE ADD CONSTRAINT PUBLIC.FK_AWJ86V8KGP9DNIUUNRBPLUAXC FOREIGN KEY(DATA_CLASS_ID) REFERENCES PUBLIC.DATA_CLASS(ID) NOCHECK;      
ALTER TABLE PUBLIC.DATA_ELEMENT ADD CONSTRAINT PUBLIC.FK_1AV6343F8NM7CA7OPAF4G9KNM FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;            
ALTER TABLE PUBLIC.RELATIONSHIP ADD CONSTRAINT PUBLIC.FK_K7IT79F0G0W8U9IDH2D6HJT2 FOREIGN KEY(SOURCE_ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;      
ALTER TABLE PUBLIC.EXTENSION_VALUE ADD CONSTRAINT PUBLIC.FK_1PCTQ5R5A3UOKWDBMBN12JT7F FOREIGN KEY(ELEMENT_ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK; 
ALTER TABLE PUBLIC.RELATIONSHIP ADD CONSTRAINT PUBLIC.FK_7SHSJYUHMA7QXSUWMDPSKKJEO FOREIGN KEY(RELATIONSHIP_TYPE_ID) REFERENCES PUBLIC.RELATIONSHIP_TYPE(ID) NOCHECK;          
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.FK_F7D8J93M1NTNR8WJ1THN34XJW FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;     
ALTER TABLE PUBLIC.CATALOGUE_ELEMENT ADD CONSTRAINT PUBLIC.FK_638SIV71XPEVTCA95WEBCRK50 FOREIGN KEY(DATA_MODEL_ID) REFERENCES PUBLIC.DATA_MODEL(ID) NOCHECK;   
ALTER TABLE PUBLIC.DATA_MODEL_DATA_MODEL_POLICY ADD CONSTRAINT PUBLIC.FK_IA4FKOPYLOM9PD0FRH0UPOTT1 FOREIGN KEY(DATA_MODEL_POLICY_ID) REFERENCES PUBLIC.DATA_MODEL_POLICY(ID) NOCHECK;          
ALTER TABLE PUBLIC.COLUMN_TRANSFORMATION_DEFINITION ADD CONSTRAINT PUBLIC.FK_DC9IXIEVJJI8RN9GMGUXESRTU FOREIGN KEY(SOURCE_ID) REFERENCES PUBLIC.DATA_ELEMENT(ID) NOCHECK;      
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.FK_APCC8LXK2XNUG8377FATVBN04 FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;       
ALTER TABLE PUBLIC.ACTION_PARAMETER ADD CONSTRAINT PUBLIC.FK_5US3SSCKQY9ARPGE6JFIEXIOS FOREIGN KEY(ACTION_ID) REFERENCES PUBLIC.ACTION(ID) NOCHECK;            
ALTER TABLE PUBLIC.REFERENCE_TYPE ADD CONSTRAINT PUBLIC.FK_RBX2592NT72IVN7SH8K7NR1NL FOREIGN KEY(ID) REFERENCES PUBLIC.DATA_TYPE(ID) NOCHECK;  
ALTER TABLE PUBLIC.DATA_CLASS ADD CONSTRAINT PUBLIC.FK_FS9S7LKEG7VDLG7GKWAMCV2LE FOREIGN KEY(ID) REFERENCES PUBLIC.CATALOGUE_ELEMENT(ID) NOCHECK;              
ALTER TABLE PUBLIC.RELATIONSHIP_METADATA ADD CONSTRAINT PUBLIC.FK_D9KE242J0CBNB8YU6FTANBN25 FOREIGN KEY(RELATIONSHIP_ID) REFERENCES PUBLIC.RELATIONSHIP(ID) NOCHECK;           
ALTER TABLE PUBLIC.COLUMN_TRANSFORMATION_DEFINITION ADD CONSTRAINT PUBLIC.FK_P2US4XJND5HRSR4R06G4MN1AT FOREIGN KEY(TRANSFORMATION_ID) REFERENCES PUBLIC.CSV_TRANSFORMATION(ID) NOCHECK;        
