/** Generated automatically from class uk.co.mc.core.DataElementControllerSpec. Do not edit this file manually! */
(function (window) {
    window['fixtures'] = window['fixtures'] || {};
    var fixtures = window['fixtures']
    fixtures['dataElement'] = fixtures['dataElement'] || {};
    var dataElement = fixtures['dataElement']

    window.fixtures.dataElement.showOne = {
   "id": 1,
   "outgoingRelationships": {
      "count": 1,
      "link": "/dataElement/outgoing/1"
   },
   "description": "the DE_author of the book",
   "name": "Author",
   "code": "XXX",
   "incomingRelationships": {
      "count": 0,
      "link": "/dataElement/incoming/1"
   },
   "version": 0
}

})(window)