/** Generated automatically from relationshipTypeControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipTypeControllerIntegrationSpec'] = fixtures['relationshipTypeControllerIntegrationSpec'] || {};
        var relationshipTypeControllerIntegrationSpec = fixtures['relationshipTypeControllerIntegrationSpec']

        window.fixtures.relationshipTypeControllerIntegrationSpec.createInput = {
   "sourceClass": "org.modelcatalogue.core.DataElement",
   "sourceToDestination": "NewInstanceAntonymWith",
   "destinationClass": "org.modelcatalogue.core.DataElement",
   "name": "NewInstanceAntonym",
   "destinationToSource": "NewInstanceAntonymWith"
}

    })(window)