/** Generated automatically from relationshipTypeControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipTypeControllerIntegrationSpec'] = fixtures['relationshipTypeControllerIntegrationSpec'] || {};
        var relationshipTypeControllerIntegrationSpec = fixtures['relationshipTypeControllerIntegrationSpec']

        window.fixtures.relationshipTypeControllerIntegrationSpec.list4 = {
   "total": 12,
   "previous": "/relationshipType/?max=4&offset=4",
   "page": 4,
   "itemType": "org.modelcatalogue.core.RelationshipType",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "",
   "list": [
      {
         "id": 9,
         "sourceClass": "org.modelcatalogue.core.Model",
         "sourceToDestination": "parent of",
         "destinationClass": "org.modelcatalogue.core.Model",
         "name": "hierarchy",
         "link": "/relationshipType/9",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "child of",
         "version": 0
      },
      {
         "id": 10,
         "sourceClass": "org.modelcatalogue.core.ConceptualDomain",
         "sourceToDestination": "includes",
         "destinationClass": "org.modelcatalogue.core.ValueDomain",
         "name": "inclusion",
         "link": "/relationshipType/10",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "included in",
         "version": 0
      },
      {
         "id": 11,
         "sourceClass": "org.modelcatalogue.core.DataElement",
         "sourceToDestination": "instantiated by",
         "destinationClass": "org.modelcatalogue.core.ValueDomain",
         "name": "instantiation",
         "link": "/relationshipType/11",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "instantiates",
         "version": 0
      },
      {
         "id": 12,
         "sourceClass": "org.modelcatalogue.core.PublishedElement",
         "sourceToDestination": "superseded by",
         "destinationClass": "org.modelcatalogue.core.PublishedElement",
         "name": "supersession",
         "link": "/relationshipType/12",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "supersedes",
         "version": 0
      }
   ],
   "offset": 8,
   "success": true,
   "size": 4
}

    })(window)