/** Generated automatically from relationshipTypeControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipTypeControllerIntegrationSpec'] = fixtures['relationshipTypeControllerIntegrationSpec'] || {};
        var relationshipTypeControllerIntegrationSpec = fixtures['relationshipTypeControllerIntegrationSpec']

        window.fixtures.relationshipTypeControllerIntegrationSpec.list1 = {
   "total": 12,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.RelationshipType",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/relationshipType/?max=10&offset=10",
   "list": [
      {
         "id": 1,
         "sourceClass": "org.modelcatalogue.core.DataElement",
         "sourceToDestination": "SynonymousWith",
         "destinationClass": "org.modelcatalogue.core.DataElement",
         "name": "Synonym",
         "link": "/relationshipType/1",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "SynonymousWith",
         "version": 0
      },
      {
         "id": 2,
         "sourceClass": "org.modelcatalogue.core.DataElement",
         "sourceToDestination": "AntonymousWith",
         "destinationClass": "org.modelcatalogue.core.DataElement",
         "name": "Antonym",
         "link": "/relationshipType/2",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "AntonymousWith",
         "version": 0
      },
      {
         "id": 3,
         "sourceClass": "org.modelcatalogue.core.CatalogueElement",
         "sourceToDestination": "relates to",
         "destinationClass": "org.modelcatalogue.core.CatalogueElement",
         "name": "relationship",
         "link": "/relationshipType/3",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "is relationship of",
         "version": 0
      },
      {
         "id": 4,
         "sourceClass": "org.modelcatalogue.core.PublishedElement",
         "sourceToDestination": "relates to",
         "destinationClass": "org.modelcatalogue.core.PublishedElement",
         "name": "pubRelationship",
         "link": "/relationshipType/4",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "is relationship of",
         "version": 0
      },
      {
         "id": 5,
         "sourceClass": "org.modelcatalogue.core.DataElement",
         "sourceToDestination": "relatedTo",
         "destinationClass": "org.modelcatalogue.core.DataElement",
         "name": "RelatedTerm",
         "link": "/relationshipType/5",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "relatedTo",
         "version": 0
      },
      {
         "id": 6,
         "sourceClass": "org.modelcatalogue.core.DataElement",
         "sourceToDestination": "broader term for",
         "destinationClass": "org.modelcatalogue.core.DataElement",
         "name": "falseRuleReturn",
         "link": "/relationshipType/6",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "narrower term for",
         "version": 0
      },
      {
         "id": 7,
         "sourceClass": "org.modelcatalogue.core.Model",
         "sourceToDestination": "contains",
         "destinationClass": "org.modelcatalogue.core.DataElement",
         "name": "containment",
         "link": "/relationshipType/7",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "contained in",
         "version": 0
      },
      {
         "id": 8,
         "sourceClass": "org.modelcatalogue.core.ConceptualDomain",
         "sourceToDestination": "provides context for",
         "destinationClass": "org.modelcatalogue.core.Model",
         "name": "context",
         "link": "/relationshipType/8",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "has context of",
         "version": 0
      },
      {
         "id": 9,
         "sourceClass": "org.modelcatalogue.core.Model",
         "sourceToDestination": "parent of",
         "destinationClass": "org.modelcatalogue.core.Model",
         "name": "hierarchy",
         "link": "/relationshipType/9",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "child of",
         "version": 0
      },
      {
         "id": 10,
         "sourceClass": "org.modelcatalogue.core.ConceptualDomain",
         "sourceToDestination": "includes",
         "destinationClass": "org.modelcatalogue.core.ValueDomain",
         "name": "inclusion",
         "link": "/relationshipType/10",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "included in",
         "version": 0
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)