/** Generated automatically from relationshipTypeControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipTypeControllerIntegrationSpec'] = fixtures['relationshipTypeControllerIntegrationSpec'] || {};
        var relationshipTypeControllerIntegrationSpec = fixtures['relationshipTypeControllerIntegrationSpec']

        window.fixtures.relationshipTypeControllerIntegrationSpec.list6 = {
   "total": 12,
   "previous": "/relationshipType/?max=2&offset=8",
   "page": 2,
   "itemType": "org.modelcatalogue.core.RelationshipType",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "",
   "list": [
      {
         "id": 11,
         "sourceClass": "org.modelcatalogue.core.DataElement",
         "sourceToDestination": "instantiated by",
         "destinationClass": "org.modelcatalogue.core.ValueDomain",
         "name": "instantiation",
         "link": "/relationshipType/11",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "instantiates",
         "version": 0
      },
      {
         "id": 12,
         "sourceClass": "org.modelcatalogue.core.PublishedElement",
         "sourceToDestination": "superseded by",
         "destinationClass": "org.modelcatalogue.core.PublishedElement",
         "name": "supersession",
         "link": "/relationshipType/12",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "supersedes",
         "version": 0
      }
   ],
   "offset": 10,
   "success": true,
   "size": 2
}

    })(window)