/** Generated automatically from relationshipTypeControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipTypeControllerIntegrationSpec'] = fixtures['relationshipTypeControllerIntegrationSpec'] || {};
        var relationshipTypeControllerIntegrationSpec = fixtures['relationshipTypeControllerIntegrationSpec']

        window.fixtures.relationshipTypeControllerIntegrationSpec.saveOk = {
   "id": 15,
   "sourceClass": "org.modelcatalogue.core.DataElement",
   "sourceToDestination": "NewInstanceAntonymWith",
   "destinationClass": "org.modelcatalogue.core.DataElement",
   "name": "NewInstanceAntonym",
   "link": "/relationshipType/15",
   "elementTypeName": "Relationship Type",
   "elementType": "org.modelcatalogue.core.RelationshipType",
   "destinationToSource": "NewInstanceAntonymWith",
   "version": 0
}

    })(window)