/** Generated automatically from relationshipTypeControllerIntegrationSpec. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipTypeControllerIntegrationSpec'] = fixtures['relationshipTypeControllerIntegrationSpec'] || {};
        var relationshipTypeControllerIntegrationSpec = fixtures['relationshipTypeControllerIntegrationSpec']

        window.fixtures.relationshipTypeControllerIntegrationSpec.updateErrors = {"errors": [{
   "field": "name",
   "message": "Property [name] of class [class org.modelcatalogue.core.RelationshipType] with value [gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg] exceeds the maximum size of [255]",
   "rejected-value": "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
   "object": "org.modelcatalogue.core.RelationshipType"
}]}

    })(window)