/** Generated automatically from valueDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['valueDomain'] = fixtures['valueDomain'] || {};
        var valueDomain = fixtures['valueDomain']

        window.fixtures.valueDomain.addIncoming = {
   "id": 5095,
   "source": {
      "id": 74,
      "name": "value domain Celsius",
      "link": "/valueDomain/74"
   },
   "type": {
      "id": 3,
      "name": "relationship",
      "link": "/relationshipType/3"
   },
   "destination": {
      "id": 73,
      "name": "value domain Fahrenheit",
      "link": "/valueDomain/73"
   }
}

    })(window)