/** Generated automatically from valueDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['valueDomain'] = fixtures['valueDomain'] || {};
        var valueDomain = fixtures['valueDomain']

        window.fixtures.valueDomain.createInput = {
   "dataType": {
      "id": 3,
      "outgoingRelationships": {
         "count": 0,
         "link": "/dataType/3/outgoing",
         "itemType": "org.modelcatalogue.core.Relationship"
      },
      "valueDomains": {
         "count": 7,
         "link": "/dataType/3/valueDomain",
         "itemType": "org.modelcatalogue.core.ValueDomain"
      },
      "description": "an integer",
      "link": "/dataType/3",
      "name": "integer",
      "elementTypeName": "Data Type",
      "incomingRelationships": {
         "count": 0,
         "link": "/dataType/3/incoming",
         "itemType": "org.modelcatalogue.core.Relationship"
      },
      "elementType": "org.modelcatalogue.core.DataType",
      "version": 7
   },
   "description": "the ground speed of the moving vehicle",
   "name": "ground_speed2",
   "regexDef": "[+-]?(?=\\d*[.eE])(?=\\.?\\d)\\d*\\.?\\d*(?:[eE][+-]?\\d+)?",
   "unitOfMeasure": {
      "id": 32,
      "outgoingRelationships": {
         "count": 0,
         "link": "/measurementUnit/32/outgoing",
         "itemType": "org.modelcatalogue.core.Relationship"
      },
      "symbol": "MPH",
      "description": null,
      "link": "/measurementUnit/32",
      "name": "Miles per hour",
      "elementTypeName": "Measurement Unit",
      "incomingRelationships": {
         "count": 0,
         "link": "/measurementUnit/32/incoming",
         "itemType": "org.modelcatalogue.core.Relationship"
      },
      "elementType": "org.modelcatalogue.core.MeasurementUnit",
      "version": 0
   }
}

    })(window)