/** Generated automatically from valueDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['valueDomain'] = fixtures['valueDomain'] || {};
        var valueDomain = fixtures['valueDomain']

        window.fixtures.valueDomain.mapping5 = {
   "total": 11,
   "previous": "/valueDomain/74/mapping?max=10&offset=0",
   "page": 10,
   "itemType": "org.modelcatalogue.core.Mapping",
   "listType": "org.modelcatalogue.core.util.Mappings",
   "next": "",
   "list": [{
      "id": 57,
      "mapping": "x",
      "destination": {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/84/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/84/incoming/inclusion"
         },
         "link": "/valueDomain/84",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/84/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/84/incoming"
         },
         "version": 0,
         "id": 84,
         "dataType": {
            "id": 3,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/3/outgoing"
            },
            "valueDomains": {
               "count": 7,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/3/valueDomain"
            },
            "description": "an integer",
            "name": "integer",
            "link": "/dataType/3",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/3/incoming"
            },
            "version": 7
         },
         "description": null,
         "name": "value domain test6",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/84/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": {
            "id": 49,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/49/outgoing"
            },
            "symbol": "°C",
            "description": "Celsius, also known as centigrade,[1] is a scale and unit of measurement for temperature. It is named after the Swedish astronomer Anders Celsius (1701–1744), who developed a similar temperature scale. The degree Celsius (°C) can refer to a specific temperature on the Celsius scale as well as a unit to indicate a temperature interval, a difference between two temperatures or an uncertainty. The unit was known until 1948 as \"centigrade\" from the Latin centum translated as 100 and gradus translated as \"steps\".",
            "name": "Degrees of Celsius",
            "link": "/measurementUnit/49",
            "elementTypeName": "Measurement Unit",
            "elementType": "org.modelcatalogue.core.MeasurementUnit",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/measurementUnit/49/incoming"
            },
            "version": 0
         }
      }
   }],
   "offset": 10,
   "success": true,
   "size": 1
}

    })(window)