/** Generated automatically from valueDomain. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['valueDomain'] = fixtures['valueDomain'] || {};
        var valueDomain = fixtures['valueDomain']

        window.fixtures.valueDomain.updateInput = {
   "description": "edited description ",
   "name": "changedName"
}

    })(window)