angular.module('mc.core.ui.states.controllers', [
  # depends on
  'mc.util'
  'mc.core.ui'
  # list of modules
  'mc.core.ui.states.controllers.DashboardCtrl'
  'mc.core.ui.states.controllers.ShowCtrl'
  'mc.core.ui.states.controllers.BatchCtrl'
  'mc.core.ui.states.controllers.BatchOnlyCtrl'
  'mc.core.ui.states.controllers.CsvTransformationCtrl'
  'mc.core.ui.states.controllers.FavoritesCtrl'
  'mc.core.ui.states.controllers.FeedbackCtrl'
  'mc.core.ui.states.controllers.DiffCtrl'
  'mc.core.ui.states.controllers.ListCtrl'
  'mc.core.ui.states.controllers.ListWithDataModelCtrl'
  'mc.core.ui.states.controllers.UserCtrl'
  'mc.core.ui.states.controllers.FastActionsCtrl'
  'mc.core.ui.states.controllers.ElementCtrl'
  'mc.core.ui.states.controllers.ElementWithDataModelCtrl'
  'mc.core.ui.states.controllers.ElementsCtrl'
  'mc.core.ui.states.controllers.DataModelTreeCtrl'
  'mc.core.ui.states.controllers.DataModelCtrl'
  'mc.core.ui.states.controllers.PanelsCtrl'
  'mc.core.ui.states.controllers.DataModelsCtrl'
  'mc.core.ui.states.controllers.XmlEditorCtrl'
])
