/** Generated automatically from class uk.co.mc.core.MeasurementUnitControllerSpec. Do not edit this file manually! */
(function (window) {
    window['fixtures'] = window['fixtures'] || {};
    var fixtures = window['fixtures']
    fixtures['measurementUnit'] = fixtures['measurementUnit'] || {};
    var measurementUnit = fixtures['measurementUnit']

    window.fixtures.measurementUnit.showOne = {
   "id": 1,
   "outgoingRelationships": {
      "count": 1,
      "link": "/measurementUnit/outgoing/1"
   },
   "symbol": "°C",
   "description": "Celsius, also known as centigrade,[1] is a scale and unit of measurement for temperature. It is named after the Swedish astronomer Anders Celsius (1701–1744), who developed a similar temperature scale. The degree Celsius (°C) can refer to a specific temperature on the Celsius scale as well as a unit to indicate a temperature interval, a difference between two temperatures or an uncertainty. The unit was known until 1948 as \"centigrade\" from the Latin centum translated as 100 and gradus translated as \"steps\".",
   "name": "Degrees of Celsius",
   "incomingRelationships": {
      "count": 0,
      "link": "/measurementUnit/incoming/1"
   },
   "version": 0
}

})(window)