package org.modelcatalogue.core.audit

/**
 * Created by ladin on 17.02.15.
 */
enum ChangeType {

    NEW_ELEMENT_CREATED,
    NEW_VERSION_CREATED,
    PROPERTY_CHANGED,
    ELEMENT_UPDATED,
    ELEMENT_DELETED,
    METADATA_CREATED,
    METADATA_UPDATED,
    METADATA_DELETED,
    RELATIONSHIP_CREATED,
    RELATIONSHIP_DELETED,
    RELATIONSHIP_METADATA_CREATED,
    RELATIONSHIP_METADATA_UPDATED,
    RELATIONSHIP_METADATA_DELETED,
}
