/** Generated automatically from dataElement. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElement'] = fixtures['dataElement'] || {};
        var dataElement = fixtures['dataElement']

        window.fixtures.dataElement.addIncoming = {
   "id": 801,
   "source": {
      "id": 34,
      "name": "DE_author",
      "link": "/dataElement/34"
   },
   "type": {
      "id": 3,
      "name": "relationship",
      "link": "/relationshipType/3"
   },
   "destination": {
      "id": 11,
      "name": "DE_author1",
      "link": "/dataElement/11"
   }
}

    })(window)