/** Generated automatically from dataElement. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElement'] = fixtures['dataElement'] || {};
        var dataElement = fixtures['dataElement']

        window.fixtures.dataElement.createInput = {
   "description": "the DE_author of the book",
   "name": "new data element",
   "code": "12312312308"
}

    })(window)