/** Generated automatically from dataElement. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElement'] = fixtures['dataElement'] || {};
        var dataElement = fixtures['dataElement']

        window.fixtures.dataElement.incoming2 = {
   "total": 11,
   "previous": "",
   "page": 5,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/dataElement/34/incoming/relationship?max=5&offset=5",
   "list": [
      {
         "id": 1018,
         "direction": "destinationToSource",
         "removeLink": "/dataElement/34/incoming/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/1/outgoing"
            },
            "status": "DRAFT",
            "link": "/dataElement/1",
            "code": "XXX_v9",
            "ext": {},
            "elementType": "org.modelcatalogue.core.DataElement",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/1/incoming"
            },
            "version": 1,
            "id": 1,
            "description": "the DE_author of the book",
            "name": "auth9",
            "containedIn": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/1/incoming/containment"
            },
            "elementTypeName": "Data Element",
            "instantiatedBy": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/1/outgoing/instantiation"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1019,
         "direction": "destinationToSource",
         "removeLink": "/dataElement/34/incoming/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/11/outgoing"
            },
            "status": "DRAFT",
            "link": "/dataElement/11",
            "code": "XXX_1",
            "ext": {"metadata": "metadata value"},
            "elementType": "org.modelcatalogue.core.DataElement",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/11/incoming"
            },
            "version": 2,
            "id": 11,
            "description": "the DE_author of the book",
            "name": "DE_author1",
            "containedIn": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/11/incoming/containment"
            },
            "elementTypeName": "Data Element",
            "instantiatedBy": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/11/outgoing/instantiation"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1020,
         "direction": "destinationToSource",
         "removeLink": "/dataElement/34/incoming/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/14/outgoing"
            },
            "status": "DRAFT",
            "link": "/dataElement/14",
            "code": "XXX_v2",
            "ext": {},
            "elementType": "org.modelcatalogue.core.DataElement",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/14/incoming"
            },
            "version": 1,
            "id": 14,
            "description": "the DE_author of the book",
            "name": "AUTHOR",
            "containedIn": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/14/incoming/containment"
            },
            "elementTypeName": "Data Element",
            "instantiatedBy": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/14/outgoing/instantiation"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1021,
         "direction": "destinationToSource",
         "removeLink": "/dataElement/34/incoming/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/17/outgoing"
            },
            "status": "DRAFT",
            "link": "/dataElement/17",
            "code": "XXX_v3",
            "ext": {},
            "elementType": "org.modelcatalogue.core.DataElement",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/17/incoming"
            },
            "version": 1,
            "id": 17,
            "description": "the DE_author of the book",
            "name": "auth",
            "containedIn": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/17/incoming/containment"
            },
            "elementTypeName": "Data Element",
            "instantiatedBy": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/17/outgoing/instantiation"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1022,
         "direction": "destinationToSource",
         "removeLink": "/dataElement/34/incoming/relationship",
         "relation": {
            "outgoingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/19/outgoing"
            },
            "status": "DRAFT",
            "link": "/dataElement/19",
            "code": "XXX_v4",
            "ext": {},
            "elementType": "org.modelcatalogue.core.DataElement",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/19/incoming"
            },
            "version": 1,
            "id": 19,
            "description": "the DE_author of the book",
            "name": "auth4",
            "containedIn": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/19/incoming/containment"
            },
            "elementTypeName": "Data Element",
            "instantiatedBy": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataElement/19/outgoing/instantiation"
            },
            "versionNumber": 0.1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 0,
   "success": true,
   "size": 5
}

    })(window)