/** Generated automatically from dataElement. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElement'] = fixtures['dataElement'] || {};
        var dataElement = fixtures['dataElement']

        window.fixtures.dataElement.list1 = {
   "total": 12,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.DataElement",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/dataElement/?max=10&offset=10",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/1/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/1",
         "code": "XXX_v9",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/1/incoming"
         },
         "version": 0,
         "id": 1,
         "description": "the DE_author of the book",
         "name": "auth9",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/1/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/1/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/11/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/11",
         "code": "XXX_1",
         "ext": {"metadata": "metadata value"},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/11/incoming"
         },
         "version": 1,
         "id": 11,
         "description": "the DE_author of the book",
         "name": "DE_author1",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/11/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/11/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/14/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/14",
         "code": "XXX_v2",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/14/incoming"
         },
         "version": 0,
         "id": 14,
         "description": "the DE_author of the book",
         "name": "AUTHOR",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/14/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/14/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/17/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/17",
         "code": "XXX_v3",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/17/incoming"
         },
         "version": 0,
         "id": 17,
         "description": "the DE_author of the book",
         "name": "auth",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/17/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/17/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/19/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/19",
         "code": "XXX_v4",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/19/incoming"
         },
         "version": 0,
         "id": 19,
         "description": "the DE_author of the book",
         "name": "auth4",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/19/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/19/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/22/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/22",
         "code": "XXX_v5",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/22/incoming"
         },
         "version": 0,
         "id": 22,
         "description": "the DE_author of the book",
         "name": "auth5",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/22/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/22/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/25/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/25",
         "code": "XXX_v6",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/25/incoming"
         },
         "version": 0,
         "id": 25,
         "description": "the DE_author of the book",
         "name": "auth6",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/25/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/25/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/27/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/27",
         "code": "XXX_v7",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/27/incoming"
         },
         "version": 0,
         "id": 27,
         "description": "the DE_author of the book",
         "name": "auth7",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/27/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/27/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/30/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/30",
         "code": "XXX_v8",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/30/incoming"
         },
         "version": 0,
         "id": 30,
         "description": "the DE_author of the book",
         "name": "auth8",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/30/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/30/outgoing/instantiation"
         },
         "versionNumber": 0.1
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/34/outgoing"
         },
         "status": "DRAFT",
         "link": "/dataElement/34",
         "code": "XXX",
         "ext": {},
         "elementType": "org.modelcatalogue.core.DataElement",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/34/incoming"
         },
         "version": 0,
         "id": 34,
         "description": "the DE_author of the book",
         "name": "DE_author",
         "containedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/34/incoming/containment"
         },
         "elementTypeName": "Data Element",
         "instantiatedBy": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/dataElement/34/outgoing/instantiation"
         },
         "versionNumber": 0.1
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)