/** Generated automatically from dataElement. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataElement'] = fixtures['dataElement'] || {};
        var dataElement = fixtures['dataElement']

        window.fixtures.dataElement.saveOk = {
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/90/outgoing"
   },
   "status": "DRAFT",
   "link": "/dataElement/90",
   "code": "12312312308",
   "ext": {},
   "elementType": "org.modelcatalogue.core.DataElement",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/90/incoming"
   },
   "version": 0,
   "id": 90,
   "description": "the DE_author of the book",
   "name": "new data element",
   "containedIn": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/90/incoming/containment"
   },
   "elementTypeName": "Data Element",
   "instantiatedBy": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataElement/90/outgoing/instantiation"
   },
   "versionNumber": 0.1
}

    })(window)