package org.modelcatalogue.core.dataarchitect;

/**
 * Created by adammilward on 18/04/2014.
 */
public enum ActionType {
    RESOLVE_ERROR, DECISION, MANDATORY_DECISION,
    CREATE_DATA_ELEMENT, UPDATE_DATA_ELEMENT, DELETE_DATA_ELEMENT,
    CREATE_VALUE_DOMAIN, UPDATE_VALUE_DOMAIN, DELETE_VALUE_DOMAIN,
    CREATE_DATA_TYPE, UPDATE_DATA_TYPE, DELETE_DATA_TYPE,
    CREATE_CONTAINING_MODEL, CREATE_PARENT_MODEL, UPDATE_CONTAINING_MODEL,
    UPDATE_PARENT_MODEL, CREATE_CONCEPTUAL_DOMAIN, MODEL_ONLY_ROW
}
