/** Generated automatically from dataType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataType'] = fixtures['dataType'] || {};
        var dataType = fixtures['dataType']

        window.fixtures.dataType.addIncoming = {
   "id": 1603,
   "source": {
      "id": 36,
      "name": "boolean",
      "link": "/dataType/36"
   },
   "type": {
      "id": 3,
      "name": "relationship",
      "link": "/relationshipType/3"
   },
   "destination": {
      "id": 57,
      "name": "double",
      "link": "/dataType/57"
   }
}

    })(window)