/** Generated automatically from dataType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataType'] = fixtures['dataType'] || {};
        var dataType = fixtures['dataType']

        window.fixtures.dataType.incomingWithNonExistingType3 = {
   "total": 0,
   "previous": "",
   "page": 5,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "",
   "list": [],
   "offset": 5,
   "success": true,
   "size": 0
}

    })(window)