/** Generated automatically from dataType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataType'] = fixtures['dataType'] || {};
        var dataType = fixtures['dataType']

        window.fixtures.dataType.outgoing1 = {
   "total": 11,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/dataType/36/outgoing/relationship?max=10&offset=10",
   "list": [
      {
         "id": 1743,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 2,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/2/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/2/valueDomain"
            },
            "description": null,
            "name": "etTest1",
            "link": "/enumeratedType/2",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/2/incoming"
            },
            "version": 1,
            "enumerations": {
               "m1": "test1",
               "m2": "test2"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1744,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 3,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/3/outgoing"
            },
            "valueDomains": {
               "count": 7,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/3/valueDomain"
            },
            "description": "an integer",
            "name": "integer",
            "link": "/dataType/3",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/3/incoming"
            },
            "version": 8
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1745,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 7,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/7/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/7/valueDomain"
            },
            "description": "a string",
            "name": "string",
            "link": "/dataType/7",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/7/incoming"
            },
            "version": 1
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1746,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 8,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/8/outgoing"
            },
            "valueDomains": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/8/valueDomain"
            },
            "description": null,
            "name": "sub2",
            "link": "/enumeratedType/8",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/8/incoming"
            },
            "version": 2,
            "enumerations": {
               "HISTORY": "history",
               "POLITICS": "politics",
               "SCIENCE": "science"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1747,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 10,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/10/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/10/valueDomain"
            },
            "description": null,
            "name": "etTest3",
            "link": "/enumeratedType/10",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/10/incoming"
            },
            "version": 1,
            "enumerations": {
               "m22m": "test22",
               "m3m": "test3"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1748,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 13,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/13/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/13/valueDomain"
            },
            "description": null,
            "name": "etTest2",
            "link": "/enumeratedType/13",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/13/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m3m": "test3"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1749,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 16,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/16/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/16/valueDomain"
            },
            "description": null,
            "name": "etTest5",
            "link": "/enumeratedType/16",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/16/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m5m": "test5"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1750,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 18,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/18/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/18/valueDomain"
            },
            "description": null,
            "name": "etTest4",
            "link": "/enumeratedType/18",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/18/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m4m": "test4"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1751,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 21,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/21/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/21/valueDomain"
            },
            "description": null,
            "name": "etTest7",
            "link": "/enumeratedType/21",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/21/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m7m": "test7"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 1752,
         "direction": "sourceToDestination",
         "removeLink": "/dataType/36/outgoing/relationship",
         "relation": {
            "id": 24,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/24/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/24/valueDomain"
            },
            "description": null,
            "name": "etTest6",
            "link": "/enumeratedType/24",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/24/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m6m": "test6"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)