/** Generated automatically from dataType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataType'] = fixtures['dataType'] || {};
        var dataType = fixtures['dataType']

        window.fixtures.dataType.updateOk = {
   "id": 36,
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataType/36/outgoing"
   },
   "valueDomains": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.ValueDomain",
      "link": "/dataType/36/valueDomain"
   },
   "description": "edited description",
   "name": "changedName",
   "link": "/dataType/36",
   "elementTypeName": "Data Type",
   "elementType": "org.modelcatalogue.core.DataType",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/dataType/36/incoming"
   },
   "version": 1
}

    })(window)