/** Generated automatically from dataType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataType'] = fixtures['dataType'] || {};
        var dataType = fixtures['dataType']

        window.fixtures.dataType.updateErrors = {"errors": [{
   "field": "name",
   "message": "Property [name] of class [class org.modelcatalogue.core.DataType] with value [gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg] does not fall within the valid size range from [2] to [255]",
   "rejected-value": "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
   "object": "org.modelcatalogue.core.DataType"
}]}

    })(window)