/** Generated automatically from dataType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataType'] = fixtures['dataType'] || {};
        var dataType = fixtures['dataType']

        window.fixtures.dataType.valueDomains1 = {
   "total": 12,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.ValueDomain",
   "listType": "org.modelcatalogue.core.util.ValueDomains",
   "next": "/dataType/36/valueDomain?max=10&offset=10",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/108/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/108/incoming/inclusion"
         },
         "link": "/valueDomain/108",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/108/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/108/incoming"
         },
         "version": 0,
         "id": 108,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain9",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/108/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/109/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/109/incoming/inclusion"
         },
         "link": "/valueDomain/109",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/109/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/109/incoming"
         },
         "version": 0,
         "id": 109,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain10",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/109/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/104/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/104/incoming/inclusion"
         },
         "link": "/valueDomain/104",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/104/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/104/incoming"
         },
         "version": 0,
         "id": 104,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain5",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/104/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/110/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/110/incoming/inclusion"
         },
         "link": "/valueDomain/110",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/110/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/110/incoming"
         },
         "version": 0,
         "id": 110,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain11",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/110/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/102/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/102/incoming/inclusion"
         },
         "link": "/valueDomain/102",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/102/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/102/incoming"
         },
         "version": 0,
         "id": 102,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain3",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/102/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/100/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/100/incoming/inclusion"
         },
         "link": "/valueDomain/100",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/100/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/100/incoming"
         },
         "version": 0,
         "id": 100,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain1",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/100/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/106/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/106/incoming/inclusion"
         },
         "link": "/valueDomain/106",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/106/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/106/incoming"
         },
         "version": 0,
         "id": 106,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain7",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/106/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/107/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/107/incoming/inclusion"
         },
         "link": "/valueDomain/107",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/107/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/107/incoming"
         },
         "version": 0,
         "id": 107,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain8",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/107/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/101/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/101/incoming/inclusion"
         },
         "link": "/valueDomain/101",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/101/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/101/incoming"
         },
         "version": 0,
         "id": 101,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain2",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/101/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/103/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/103/incoming/inclusion"
         },
         "link": "/valueDomain/103",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/103/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/103/incoming"
         },
         "version": 0,
         "id": 103,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain4",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/103/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)