/** Generated automatically from dataType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['dataType'] = fixtures['dataType'] || {};
        var dataType = fixtures['dataType']

        window.fixtures.dataType.valueDomains5 = {
   "total": 12,
   "previous": "/dataType/36/valueDomain?max=10&offset=0",
   "page": 10,
   "itemType": "org.modelcatalogue.core.ValueDomain",
   "listType": "org.modelcatalogue.core.util.ValueDomains",
   "next": "",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/147/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/147/incoming/inclusion"
         },
         "link": "/valueDomain/147",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/147/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/147/incoming"
         },
         "version": 0,
         "id": 147,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain0",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/147/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/157/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/157/incoming/inclusion"
         },
         "link": "/valueDomain/157",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/157/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/157/incoming"
         },
         "version": 0,
         "id": 157,
         "dataType": {
            "id": 36,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/dataType/36/valueDomain"
            },
            "description": "a boolean xdfxdf",
            "name": "boolean",
            "link": "/dataType/36",
            "elementTypeName": "Data Type",
            "elementType": "org.modelcatalogue.core.DataType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/dataType/36/incoming"
            },
            "version": 0
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain10",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/157/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      }
   ],
   "offset": 10,
   "success": true,
   "size": 2
}

    })(window)