/** Generated automatically from badSearch. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['badSearch'] = fixtures['badSearch'] || {};
        var badSearch = fixtures['badSearch']

        window.fixtures.badSearch.list2 = {"errors": "No query string to search on"}

    })(window)