/** Generated automatically from relationshipType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipType'] = fixtures['relationshipType'] || {};
        var relationshipType = fixtures['relationshipType']

        window.fixtures.relationshipType.createInput = {
   "sourceClass": "org.modelcatalogue.core.DataElement",
   "sourceToDestination": "NewInstanceAntonymWith",
   "destinationClass": "org.modelcatalogue.core.DataElement",
   "name": "NewInstanceAntonym",
   "destinationToSource": "NewInstanceAntonymWith"
}

    })(window)