/** Generated automatically from relationshipType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipType'] = fixtures['relationshipType'] || {};
        var relationshipType = fixtures['relationshipType']

        window.fixtures.relationshipType.saveOk = {
   "id": 159,
   "sourceClass": "org.modelcatalogue.core.DataElement",
   "sourceToDestination": "NewInstanceAntonymWith",
   "destinationClass": "org.modelcatalogue.core.DataElement",
   "name": "NewInstanceAntonym",
   "link": "/relationshipType/159",
   "elementTypeName": "Relationship Type",
   "elementType": "org.modelcatalogue.core.RelationshipType",
   "destinationToSource": "NewInstanceAntonymWith",
   "version": 0
}

    })(window)