/** Generated automatically from relationshipType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipType'] = fixtures['relationshipType'] || {};
        var relationshipType = fixtures['relationshipType']

        window.fixtures.relationshipType.searchElement17 = {
   "total": 1,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.RelationshipType",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "",
   "list": [{
      "id": 8,
      "sourceClass": "org.modelcatalogue.core.ConceptualDomain",
      "sourceToDestination": "provides context for",
      "destinationClass": "org.modelcatalogue.core.Model",
      "name": "context",
      "link": "/relationshipType/8",
      "elementTypeName": "Relationship Type",
      "elementType": "org.modelcatalogue.core.RelationshipType",
      "destinationToSource": "has context of",
      "version": 0
   }],
   "offset": 0,
   "success": true,
   "size": 1
}

    })(window)