/** Generated automatically from relationshipType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipType'] = fixtures['relationshipType'] || {};
        var relationshipType = fixtures['relationshipType']

        window.fixtures.relationshipType.updateInput = {
   "sourceClass": "org.modelcatalogue.core.PublishedElement",
   "destinationClass": "org.modelcatalogue.core.PublishedElement",
   "name": "changedName"
}

    })(window)