/** Generated automatically from relationshipType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipType'] = fixtures['relationshipType'] || {};
        var relationshipType = fixtures['relationshipType']

        window.fixtures.relationshipType.updateOk = {
   "id": 2,
   "sourceClass": "org.modelcatalogue.core.PublishedElement",
   "sourceToDestination": "AntonymousWith",
   "destinationClass": "org.modelcatalogue.core.PublishedElement",
   "name": "changedName",
   "link": "/relationshipType/2",
   "elementTypeName": "Relationship Type",
   "elementType": "org.modelcatalogue.core.RelationshipType",
   "destinationToSource": "AntonymousWith",
   "version": 1
}

    })(window)