/** Generated automatically from relationshipType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['relationshipType'] = fixtures['relationshipType'] || {};
        var relationshipType = fixtures['relationshipType']

        window.fixtures.relationshipType.validateErrors = {"errors": [{
   "field": "name",
   "message": "Property [name] of class [class org.modelcatalogue.core.RelationshipType] with value [tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt] exceeds the maximum size of [255]",
   "rejected-value": "tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt",
   "object": "org.modelcatalogue.core.RelationshipType"
}]}

    })(window)