/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.incomingWithNonExistingType1 = {
   "total": 0,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "",
   "list": [],
   "offset": 0,
   "success": true,
   "size": 0
}

    })(window)