/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.incoming5 = {
   "total": 11,
   "previous": "/enumeratedType/56/incoming/relationship?max=10&offset=0",
   "page": 10,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "",
   "list": [{
      "id": 2927,
      "direction": "destinationToSource",
      "removeLink": "/enumeratedType/56/incoming/relationship",
      "relation": {
         "id": 43,
         "outgoingRelationships": {
            "count": 1,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/43/outgoing"
         },
         "valueDomains": {
            "count": 1,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/43/valueDomain"
         },
         "description": null,
         "name": "sub3",
         "link": "/enumeratedType/43",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/43/incoming"
         },
         "version": 2,
         "enumerations": {
            "p": "politics",
            "sci": "science",
            "h": "history"
         }
      },
      "type": {
         "id": 3,
         "sourceClass": "org.modelcatalogue.core.CatalogueElement",
         "sourceToDestination": "relates to",
         "destinationClass": "org.modelcatalogue.core.CatalogueElement",
         "name": "relationship",
         "link": "/relationshipType/3",
         "elementTypeName": "Relationship Type",
         "elementType": "org.modelcatalogue.core.RelationshipType",
         "destinationToSource": "is relationship of",
         "version": 0
      }
   }],
   "offset": 10,
   "success": true,
   "size": 1
}

    })(window)