/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.list1 = {
   "total": 12,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.EnumeratedType",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "/enumeratedType/?max=10&offset=10",
   "list": [
      {
         "id": 2,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/2/outgoing"
         },
         "valueDomains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/2/valueDomain"
         },
         "description": null,
         "name": "etTest1",
         "link": "/enumeratedType/2",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/2/incoming"
         },
         "version": 0,
         "enumerations": {
            "m1": "test1",
            "m2": "test2"
         }
      },
      {
         "id": 8,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/8/outgoing"
         },
         "valueDomains": {
            "count": 1,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/8/valueDomain"
         },
         "description": null,
         "name": "sub2",
         "link": "/enumeratedType/8",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/8/incoming"
         },
         "version": 1,
         "enumerations": {
            "HISTORY": "history",
            "POLITICS": "politics",
            "SCIENCE": "science"
         }
      },
      {
         "id": 10,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/10/outgoing"
         },
         "valueDomains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/10/valueDomain"
         },
         "description": null,
         "name": "etTest3",
         "link": "/enumeratedType/10",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/10/incoming"
         },
         "version": 0,
         "enumerations": {
            "m22m": "test22",
            "m3m": "test3"
         }
      },
      {
         "id": 13,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/13/outgoing"
         },
         "valueDomains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/13/valueDomain"
         },
         "description": null,
         "name": "etTest2",
         "link": "/enumeratedType/13",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/13/incoming"
         },
         "version": 0,
         "enumerations": {
            "m2m": "test2",
            "m3m": "test3"
         }
      },
      {
         "id": 16,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/16/outgoing"
         },
         "valueDomains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/16/valueDomain"
         },
         "description": null,
         "name": "etTest5",
         "link": "/enumeratedType/16",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/16/incoming"
         },
         "version": 0,
         "enumerations": {
            "m2m": "test2",
            "m5m": "test5"
         }
      },
      {
         "id": 18,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/18/outgoing"
         },
         "valueDomains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/18/valueDomain"
         },
         "description": null,
         "name": "etTest4",
         "link": "/enumeratedType/18",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/18/incoming"
         },
         "version": 0,
         "enumerations": {
            "m2m": "test2",
            "m4m": "test4"
         }
      },
      {
         "id": 21,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/21/outgoing"
         },
         "valueDomains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/21/valueDomain"
         },
         "description": null,
         "name": "etTest7",
         "link": "/enumeratedType/21",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/21/incoming"
         },
         "version": 0,
         "enumerations": {
            "m2m": "test2",
            "m7m": "test7"
         }
      },
      {
         "id": 24,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/24/outgoing"
         },
         "valueDomains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/24/valueDomain"
         },
         "description": null,
         "name": "etTest6",
         "link": "/enumeratedType/24",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/24/incoming"
         },
         "version": 0,
         "enumerations": {
            "m2m": "test2",
            "m6m": "test6"
         }
      },
      {
         "id": 29,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/29/outgoing"
         },
         "valueDomains": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/29/valueDomain"
         },
         "description": null,
         "name": "etTest8",
         "link": "/enumeratedType/29",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/29/incoming"
         },
         "version": 0,
         "enumerations": {
            "m2m": "test2",
            "m8m": "test8"
         }
      },
      {
         "id": 35,
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/35/outgoing"
         },
         "valueDomains": {
            "count": 2,
            "itemType": "org.modelcatalogue.core.ValueDomain",
            "link": "/enumeratedType/35/valueDomain"
         },
         "description": null,
         "name": "sub1",
         "link": "/enumeratedType/35",
         "elementTypeName": "Enumerated Type",
         "elementType": "org.modelcatalogue.core.EnumeratedType",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/enumeratedType/35/incoming"
         },
         "version": 2,
         "enumerations": {
            "GEO": "geography",
            "P": "politics",
            "SCI": "science",
            "H": "history"
         }
      }
   ],
   "offset": 0,
   "success": true,
   "size": 10
}

    })(window)