/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.outgoing3 = {
   "total": 11,
   "previous": "/enumeratedType/56/outgoing/relationship?max=5&offset=0",
   "page": 5,
   "itemType": "org.modelcatalogue.core.Relationship",
   "listType": "org.modelcatalogue.core.util.Relationships",
   "next": "/enumeratedType/56/outgoing/relationship?max=5&offset=10",
   "list": [
      {
         "id": 2834,
         "direction": "sourceToDestination",
         "removeLink": "/enumeratedType/56/outgoing/relationship",
         "relation": {
            "id": 18,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/18/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/18/valueDomain"
            },
            "description": null,
            "name": "etTest4",
            "link": "/enumeratedType/18",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/18/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m4m": "test4"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 2835,
         "direction": "sourceToDestination",
         "removeLink": "/enumeratedType/56/outgoing/relationship",
         "relation": {
            "id": 21,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/21/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/21/valueDomain"
            },
            "description": null,
            "name": "etTest7",
            "link": "/enumeratedType/21",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/21/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m7m": "test7"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 2836,
         "direction": "sourceToDestination",
         "removeLink": "/enumeratedType/56/outgoing/relationship",
         "relation": {
            "id": 24,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/24/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/24/valueDomain"
            },
            "description": null,
            "name": "etTest6",
            "link": "/enumeratedType/24",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/24/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m6m": "test6"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 2837,
         "direction": "sourceToDestination",
         "removeLink": "/enumeratedType/56/outgoing/relationship",
         "relation": {
            "id": 29,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/29/outgoing"
            },
            "valueDomains": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/29/valueDomain"
            },
            "description": null,
            "name": "etTest8",
            "link": "/enumeratedType/29",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/29/incoming"
            },
            "version": 1,
            "enumerations": {
               "m2m": "test2",
               "m8m": "test8"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      },
      {
         "id": 2838,
         "direction": "sourceToDestination",
         "removeLink": "/enumeratedType/56/outgoing/relationship",
         "relation": {
            "id": 35,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/35/outgoing"
            },
            "valueDomains": {
               "count": 2,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/35/valueDomain"
            },
            "description": null,
            "name": "sub1",
            "link": "/enumeratedType/35",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 1,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/35/incoming"
            },
            "version": 3,
            "enumerations": {
               "GEO": "geography",
               "P": "politics",
               "SCI": "science",
               "H": "history"
            }
         },
         "type": {
            "id": 3,
            "sourceClass": "org.modelcatalogue.core.CatalogueElement",
            "sourceToDestination": "relates to",
            "destinationClass": "org.modelcatalogue.core.CatalogueElement",
            "name": "relationship",
            "link": "/relationshipType/3",
            "elementTypeName": "Relationship Type",
            "elementType": "org.modelcatalogue.core.RelationshipType",
            "destinationToSource": "is relationship of",
            "version": 0
         }
      }
   ],
   "offset": 5,
   "success": true,
   "size": 5
}

    })(window)