/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.removeNonExistingIncomingJSON = {"id":35,"name":"sub1","description":null,"version":2,"elementType":"org.modelcatalogue.core.EnumeratedType","elementTypeName":"Enumerated Type","link":"/enumeratedType/35","outgoingRelationships":{"count":0,"itemType":"org.modelcatalogue.core.Relationship","link":"/enumeratedType/35/outgoing"},"incomingRelationships":{"count":0,"itemType":"org.modelcatalogue.core.Relationship","link":"/enumeratedType/35/incoming"},"valueDomains":{"count":2,"itemType":"org.modelcatalogue.core.ValueDomain","link":"/enumeratedType/35/valueDomain"},"enumerations":{"GEO":"geography","H":"history","P":"politics","SCI":"science"}}

    })(window)