/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.searchElement9 = {
   "total": 1,
   "previous": "",
   "page": 10,
   "itemType": "org.modelcatalogue.core.EnumeratedType",
   "listType": "org.modelcatalogue.core.util.Elements",
   "next": "",
   "list": [{
      "id": 35,
      "outgoingRelationships": {
         "count": 0,
         "itemType": "org.modelcatalogue.core.Relationship",
         "link": "/enumeratedType/35/outgoing"
      },
      "valueDomains": {
         "count": 2,
         "itemType": "org.modelcatalogue.core.ValueDomain",
         "link": "/enumeratedType/35/valueDomain"
      },
      "description": null,
      "name": "sub1",
      "link": "/enumeratedType/35",
      "elementTypeName": "Enumerated Type",
      "elementType": "org.modelcatalogue.core.EnumeratedType",
      "incomingRelationships": {
         "count": 0,
         "itemType": "org.modelcatalogue.core.Relationship",
         "link": "/enumeratedType/35/incoming"
      },
      "version": 2,
      "enumerations": {
         "GEO": "geography",
         "P": "politics",
         "SCI": "science",
         "H": "history"
      }
   }],
   "offset": 0,
   "success": true,
   "size": 1
}

    })(window)