/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.updateOk = {
   "id": 56,
   "outgoingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/enumeratedType/56/outgoing"
   },
   "valueDomains": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.ValueDomain",
      "link": "/enumeratedType/56/valueDomain"
   },
   "description": "edited description",
   "name": "changedName",
   "link": "/enumeratedType/56",
   "elementTypeName": "Enumerated Type",
   "elementType": "org.modelcatalogue.core.EnumeratedType",
   "incomingRelationships": {
      "count": 0,
      "itemType": "org.modelcatalogue.core.Relationship",
      "link": "/enumeratedType/56/incoming"
   },
   "version": 1,
   "enumerations": {
      "sadf": "asdgsadg",
      "d26": "test28"
   }
}

    })(window)