/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.validateErrors = {"errors": [
   {
      "field": "name",
      "message": "Property [name] of class [class org.modelcatalogue.core.EnumeratedType] with value [tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt] does not fall within the valid size range from [2] to [255]",
      "rejected-value": "tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt",
      "object": "org.modelcatalogue.core.EnumeratedType"
   },
   {
      "field": "enumAsString",
      "message": "Property [enumAsString] of class [class org.modelcatalogue.core.EnumeratedType] cannot be null",
      "rejected-value": null,
      "object": "org.modelcatalogue.core.EnumeratedType"
   }
]}

    })(window)