/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.valueDomains2 = {
   "total": 12,
   "previous": "",
   "page": 5,
   "itemType": "org.modelcatalogue.core.ValueDomain",
   "listType": "org.modelcatalogue.core.util.ValueDomains",
   "next": "/enumeratedType/56/valueDomain?max=5&offset=5",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/489/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/489/incoming/inclusion"
         },
         "link": "/valueDomain/489",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/489/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/489/incoming"
         },
         "version": 0,
         "id": 489,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain10",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/489/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/486/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/486/incoming/inclusion"
         },
         "link": "/valueDomain/486",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/486/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/486/incoming"
         },
         "version": 0,
         "id": 486,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain7",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/486/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/479/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/479/incoming/inclusion"
         },
         "link": "/valueDomain/479",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/479/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/479/incoming"
         },
         "version": 0,
         "id": 479,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain0",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/479/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/488/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/488/incoming/inclusion"
         },
         "link": "/valueDomain/488",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/488/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/488/incoming"
         },
         "version": 0,
         "id": 488,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain9",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/488/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/484/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/484/incoming/inclusion"
         },
         "link": "/valueDomain/484",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/484/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/484/incoming"
         },
         "version": 0,
         "id": 484,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain5",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/484/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      }
   ],
   "offset": 0,
   "success": true,
   "size": 5
}

    })(window)