/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.valueDomains4 = {
   "total": 12,
   "previous": "/enumeratedType/56/valueDomain?max=4&offset=4",
   "page": 4,
   "itemType": "org.modelcatalogue.core.ValueDomain",
   "listType": "org.modelcatalogue.core.util.ValueDomains",
   "next": "",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/506/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/506/incoming/inclusion"
         },
         "link": "/valueDomain/506",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/506/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/506/incoming"
         },
         "version": 0,
         "id": 506,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain3",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/506/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/503/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/503/incoming/inclusion"
         },
         "link": "/valueDomain/503",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/503/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/503/incoming"
         },
         "version": 0,
         "id": 503,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain0",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/503/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/509/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/509/incoming/inclusion"
         },
         "link": "/valueDomain/509",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/509/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/509/incoming"
         },
         "version": 0,
         "id": 509,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain6",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/509/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/514/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/514/incoming/inclusion"
         },
         "link": "/valueDomain/514",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/514/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/514/incoming"
         },
         "version": 0,
         "id": 514,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain11",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/514/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      }
   ],
   "offset": 8,
   "success": true,
   "size": 4
}

    })(window)