/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.valueDomains3 = {
   "total": 12,
   "previous": "/enumeratedType/56/valueDomain?max=5&offset=0",
   "page": 5,
   "itemType": "org.modelcatalogue.core.ValueDomain",
   "listType": "org.modelcatalogue.core.util.ValueDomains",
   "next": "/enumeratedType/56/valueDomain?max=5&offset=10",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/492/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/492/incoming/inclusion"
         },
         "link": "/valueDomain/492",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/492/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/492/incoming"
         },
         "version": 0,
         "id": 492,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain1",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/492/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/502/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/502/incoming/inclusion"
         },
         "link": "/valueDomain/502",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/502/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/502/incoming"
         },
         "version": 0,
         "id": 502,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain11",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/502/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/500/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/500/incoming/inclusion"
         },
         "link": "/valueDomain/500",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/500/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/500/incoming"
         },
         "version": 0,
         "id": 500,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain9",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/500/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/501/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/501/incoming/inclusion"
         },
         "link": "/valueDomain/501",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/501/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/501/incoming"
         },
         "version": 0,
         "id": 501,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain10",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/501/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/491/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/491/incoming/inclusion"
         },
         "link": "/valueDomain/491",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/491/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/491/incoming"
         },
         "version": 0,
         "id": 491,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain0",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/491/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      }
   ],
   "offset": 5,
   "success": true,
   "size": 5
}

    })(window)