/** Generated automatically from enumeratedType. Do not edit this file manually! */
    (function (window) {
        window['fixtures'] = window['fixtures'] || {};
        var fixtures = window['fixtures']
        fixtures['enumeratedType'] = fixtures['enumeratedType'] || {};
        var enumeratedType = fixtures['enumeratedType']

        window.fixtures.enumeratedType.valueDomains6 = {
   "total": 12,
   "previous": "/enumeratedType/56/valueDomain?max=2&offset=8",
   "page": 2,
   "itemType": "org.modelcatalogue.core.ValueDomain",
   "listType": "org.modelcatalogue.core.util.ValueDomains",
   "next": "",
   "list": [
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/528/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/528/incoming/inclusion"
         },
         "link": "/valueDomain/528",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/528/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/528/incoming"
         },
         "version": 0,
         "id": 528,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain1",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/528/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      },
      {
         "outgoingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/537/outgoing"
         },
         "includedIn": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/537/incoming/inclusion"
         },
         "link": "/valueDomain/537",
         "instantiates": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/537/incoming/instantiation"
         },
         "elementType": "org.modelcatalogue.core.ValueDomain",
         "incomingRelationships": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Relationship",
            "link": "/valueDomain/537/incoming"
         },
         "version": 0,
         "id": 537,
         "dataType": {
            "id": 56,
            "outgoingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/outgoing"
            },
            "valueDomains": {
               "count": 12,
               "itemType": "org.modelcatalogue.core.ValueDomain",
               "link": "/enumeratedType/56/valueDomain"
            },
            "description": null,
            "name": "gender",
            "link": "/enumeratedType/56",
            "elementTypeName": "Enumerated Type",
            "elementType": "org.modelcatalogue.core.EnumeratedType",
            "incomingRelationships": {
               "count": 0,
               "itemType": "org.modelcatalogue.core.Relationship",
               "link": "/enumeratedType/56/incoming"
            },
            "version": 0,
            "enumerations": {
               "f": "female",
               "ns": "not specified",
               "u": "unknown",
               "m": "male"
            }
         },
         "description": "the ground speed of the moving vehicle",
         "name": "dataTypeValueDomain10",
         "mappings": {
            "count": 0,
            "itemType": "org.modelcatalogue.core.Mapping",
            "link": "/valueDomain/537/mapping"
         },
         "rule": null,
         "elementTypeName": "Value Domain",
         "unitOfMeasure": null
      }
   ],
   "offset": 10,
   "success": true,
   "size": 2
}

    })(window)