package org.modelcatalogue.core

import groovy.transform.CompileStatic

@CompileStatic
enum DeleteBlockerReason {
    CATALOGUE_ELEMENT,
    SOURCE_BELONGS_TO_DIFFERENT_DATAMODEL,
    DESTINATION_BELONGS_TO_DIFFERENT_DATAMODEL,
    BELONGS_TO_DIFFERENT_DATAMODEL,
    INCOMING_RELATION_AT_DIFFERENT_DATAMODEL,
    OUTGOING_RELATION_AT_DIFFERENT_DATAMODEL
}
